//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QASmartClass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QASmartClass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff &amp; Teacher Portal.
        /// </summary>
        public static string Login_PortalHeader {
            get {
                return ResourceManager.GetString("Login_PortalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff / Teacher Code.
        /// </summary>
        public static string Login_StaffCode {
            get {
                return ResourceManager.GetString("Login_StaffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Login - SmartSchool.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVENTS LOGGED.
        /// </summary>
        public static string Overview_CardEvents {
            get {
                return ResourceManager.GetString("Overview_CardEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDING REQUESTS.
        /// </summary>
        public static string Overview_CardPending {
            get {
                return ResourceManager.GetString("Overview_CardPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANTEEN REVENUE.
        /// </summary>
        public static string Overview_CardRevenue {
            get {
                return ResourceManager.GetString("Overview_CardRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE STAFF.
        /// </summary>
        public static string Overview_CardStaff {
            get {
                return ResourceManager.GetString("Overview_CardStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM STUDENTS.
        /// </summary>
        public static string Overview_CardStudents {
            get {
                return ResourceManager.GetString("Overview_CardStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Operation Management • .
        /// </summary>
        public static string Overview_SubHeader {
            get {
                return ResourceManager.GetString("Overview_SubHeader", resourceCulture);
            }
        }
    }
}
