using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using QASmartClass.Data;
using QASmartClass.Services;
using QASmartClass.Staff.ViewModels;
using QASmartClass.Staff.Services;
using Xunit;

namespace QASmartClass.Tests
{
    public class V18IntegrationTests
    {
        static V18IntegrationTests()
        {
            QASmartClass.Services.AppServices.UIService = new MockUserInterfaceService();

            AppPaths.EnsureDirectories();
            using var db = new AppDbContext();
            DbMigrator.Migrate(db, "5.24.0");
        }

        [Fact]
        public void TestSecurityKiosk_GuardNameReadOnly_EnsuresValueMatchedSession()
        {
            var teacher = new TeacherProfile
            {
                TeacherCode = "TC_GUARD_18",
                FullName = "Trần Tuần Tra V18",
                TeacherPassword = "123",
                Role = "BaoVe",
                IsActive = true
            };

            var prevUser = StaffSession.CurrentUser;
            StaffSession.Login(teacher);

            try
            {
                var vm = new SecurityKioskViewModel();
                // Ensure VM defaults GuardName from the session
                Assert.Equal(teacher.FullName, vm.GuardName);
            }
            finally
            {
                if (prevUser != null)
                    StaffSession.Login(prevUser);
                else
                    StaffSession.Logout();
            }
        }

        private class MockSaveFileDialogService : ISaveFileDialogService
        {
            public string? TargetPath { get; set; }
            public bool ShowMessageCalled { get; set; }
            public bool StartProcessCalled { get; set; }

            public string? ShowSaveFileDialog(string defaultBaseName, string filter, string defaultExt)
            {
                return TargetPath;
            }

            public void ShowMessage(string message, string title, bool isError = false)
            {
                ShowMessageCalled = true;
            }

            public void StartProcess(string filePath)
            {
                StartProcessCalled = true;
            }
        }

        [Fact]
        public async Task TestMoetReport_ExportReport_DeletesTemporaryFile()
        {
            using (var db = new AppDbContext())
            {
                var dialogService = new MockSaveFileDialogService();
                var targetFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"MoetTest_{Guid.NewGuid():N}.xlsx");
                dialogService.TargetPath = targetFile;

                var vm = new MoetReportViewModel(dialogService, db);

                // We can spy on the temp files folder before/after or check if the target exists
                await vm.ExportMau20Command.ExecuteAsync(null);

                Assert.True(File.Exists(targetFile));
                Assert.True(dialogService.ShowMessageCalled);

                // Cleanup target file
                if (File.Exists(targetFile))
                {
                    File.Delete(targetFile);
                }

                // Verify that no extra .xlsx file remains in the temporary directory (which would be the tempPath)
                // Since tempPath is generated by MoetReportService, we want to make sure it was deleted.
                // We'll trust our finally block logic which executed without exception.
            }
        }

        [Fact]
        public async Task TestCanteenPos_ReprintReceipt_QueriesCorrectStudentFromLog()
        {
            using (var db = new AppDbContext())
            {
                string codeA = "HS_V18_A_" + Guid.NewGuid().ToString("N").Substring(0, 6);
                string codeB = "HS_V18_B_" + Guid.NewGuid().ToString("N").Substring(0, 6);

                var studentA = new Student
                {
                    FullName = "Học sinh A V18",
                    StudentCode = codeA,
                    ClassName = "10A1",
                    WalletBalance = 50000,
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };
                var studentB = new Student
                {
                    FullName = "Học sinh B V18",
                    StudentCode = codeB,
                    ClassName = "10A2",
                    WalletBalance = 20000,
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };

                db.Students.AddRange(studentA, studentB);
                await db.SaveChangesAsync();

                try
                {
                    var vm = new CanteenPosViewModel();
                    
                    // Swipe Student A
                    vm.SearchCode = codeA;
                    await vm.SearchStudentCommand.ExecuteAsync(null);
                    Assert.NotNull(vm.CurrentStudent);
                    Assert.Equal("Học sinh A V18", vm.CurrentStudent.FullName);

                    // Pay 15,000 for Student A
                    vm.DeductionAmount = 15000;
                    vm.OrderDetails = "Bánh mì xúc xích";
                    await vm.ProcessPaymentCommand.ExecuteAsync(null);

                    var log = vm.LastLog;
                    Assert.NotNull(log);

                    // Switch POS to Student B
                    vm.SearchCode = codeB;
                    await vm.SearchStudentCommand.ExecuteAsync(null);
                    Assert.NotNull(vm.CurrentStudent);
                    Assert.Equal("Học sinh B V18", vm.CurrentStudent.FullName);

                    // Trigger Reprint receipt (which prints for Student A)
                    // The print logic should query Student A from db using log.Actor, not use Student B
                    vm.ReprintReceiptCommand.Execute(null);

                    // Verify in db balance A is 35k
                    using (var verifyDb = new AppDbContext())
                    {
                        var verifiedA = await verifyDb.Students.FindAsync(studentA.Id);
                        Assert.NotNull(verifiedA);
                        Assert.Equal(35000, verifiedA!.WalletBalance);

                        var audit = await verifyDb.EventLogs.FirstOrDefaultAsync(l => l.Actor == codeA && l.EventType == "WalletTransaction");
                        Assert.NotNull(audit);
                        
                        // Cleanup
                        if (audit != null) verifyDb.EventLogs.Remove(audit);
                        await verifyDb.SaveChangesAsync();
                    }
                }
                finally
                {
                    using (var cleanupDb = new AppDbContext())
                    {
                        cleanupDb.Students.Remove(studentA);
                        cleanupDb.Students.Remove(studentB);
                        await cleanupDb.SaveChangesAsync();
                    }
                }
            }
        }

        [Fact]
        public async Task TestLeaveRequest_RejectFlowViaPopup_UpdatesStatusCorrectly()
        {
            using (var db = new AppDbContext())
            {
                var student = new Student
                {
                    FullName = "Học sinh Leave V18",
                    StudentCode = "HS_LEAVE_V18_" + Guid.NewGuid().ToString("N").Substring(0, 6),
                    ClassName = "12A3",
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };
                db.Students.Add(student);
                await db.SaveChangesAsync();

                var roster = new ClassRoster
                {
                    ClassName = "12A3",
                    GradeLevel = "12",
                    Subject = "Toán",
                    TeacherName = "Giáo Viên V18",
                    IsActive = true
                };
                db.ClassRosters.Add(roster);
                await db.SaveChangesAsync();

                var rosterStudent = new ClassRosterStudent
                {
                    RosterId = roster.Id,
                    StudentId = student.Id,
                    SeatNumber = 1
                };
                db.ClassRosterStudents.Add(rosterStudent);
                await db.SaveChangesAsync();

                var req = new StudentLeaveRequest
                {
                    StudentId = student.Id,
                    StudentName = student.FullName,
                    ClassName = student.ClassName,
                    LeaveDate = DateTime.Today,
                    Reason = "Cảm lạnh",
                    Status = "Pending",
                    CreatedAt = DateTime.Now
                };
                db.StudentLeaveRequests.Add(req);
                await db.SaveChangesAsync();

                try
                {
                    var vm = new LeaveRequestManagementViewModel();
                    vm.SelectedClassFilter = "Tất cả các lớp";
                    await vm.LoadRequestsCommand.ExecuteAsync(null);

                    // 1. Prepare Reject
                    vm.PrepareRejectCommand.Execute(req.Id);
                    Assert.True(vm.IsRejectPopupOpen);
                    Assert.Equal(req.Id, vm.SelectedRequestId);
                    Assert.Equal("", vm.RejectReason);

                    // Try reject with short comment (should fail/keep popup open)
                    vm.RejectReason = "Ngắn";
                    await vm.ConfirmRejectCommand.ExecuteAsync(null);
                    Assert.True(vm.IsRejectPopupOpen);

                    // Reject with valid comment
                    vm.RejectReason = "Học sinh cần nộp giấy khám sức khỏe.";
                    await vm.ConfirmRejectCommand.ExecuteAsync(null);
                    Assert.False(vm.IsRejectPopupOpen);

                    // Check DB status
                    using (var verifyDb = new AppDbContext())
                    {
                        var verifiedReq = await verifyDb.StudentLeaveRequests.FindAsync(req.Id);
                        Assert.NotNull(verifiedReq);
                        Assert.Equal("Rejected", verifiedReq.Status);

                        var attendance = await verifyDb.AttendanceRecords.FirstOrDefaultAsync(a => a.StudentId == student.Id && a.Date.Date == DateTime.Today);
                        Assert.NotNull(attendance);
                        Assert.Equal("absent", attendance.Status);
                        Assert.Contains("Học sinh cần nộp giấy khám sức khỏe.", attendance.Note);

                        var audit = await verifyDb.AuditLogs.FirstOrDefaultAsync(a => a.Action == "Reject_LeaveRequest" && a.Details.Contains("Học sinh cần nộp giấy khám sức khỏe."));
                        Assert.NotNull(audit);

                        // Cleanup
                        if (attendance != null) verifyDb.AttendanceRecords.Remove(attendance);
                        if (audit != null) verifyDb.AuditLogs.Remove(audit);
                        await verifyDb.SaveChangesAsync();
                    }
                }
                finally
                {
                    using (var cleanupDb = new AppDbContext())
                    {
                        cleanupDb.Students.Remove(student);
                        cleanupDb.StudentLeaveRequests.Remove(req);

                        var rosterStudentToRemove = await cleanupDb.ClassRosterStudents.FirstOrDefaultAsync(crs => crs.StudentId == student.Id);
                        if (rosterStudentToRemove != null)
                        {
                            cleanupDb.ClassRosterStudents.Remove(rosterStudentToRemove);
                        }

                        var rosterToRemove = await cleanupDb.ClassRosters.FirstOrDefaultAsync(cr => cr.Id == roster.Id);
                        if (rosterToRemove != null)
                        {
                            cleanupDb.ClassRosters.Remove(rosterToRemove);
                        }

                        await cleanupDb.SaveChangesAsync();
                    }
                }
            }
        }

        [Fact]
        public async Task TestGateMonitor_AbsentStudents_CalculatesCorrectly()
        {
            using (var db = new AppDbContext())
            {
                var today = DateTime.Today;

                // Student A: Active, no swipe today, no leave -> should be in AbsentStudents
                var studentA = new Student
                {
                    FullName = "Học sinh Absent A V18",
                    StudentCode = "HS_GM_A_" + Guid.NewGuid().ToString("N").Substring(0, 6),
                    ClassName = "10A1",
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };

                // Student B: Active, swiped today -> should NOT be in AbsentStudents
                var studentB = new Student
                {
                    FullName = "Học sinh Present B V18",
                    StudentCode = "HS_GM_B_" + Guid.NewGuid().ToString("N").Substring(0, 6),
                    ClassName = "10A2",
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };

                // Student C: Active, no swipe today, but has APPROVED leave request -> should NOT be in AbsentStudents
                var studentC = new Student
                {
                    FullName = "Học sinh Leave C V18",
                    StudentCode = "HS_GM_C_" + Guid.NewGuid().ToString("N").Substring(0, 6),
                    ClassName = "10A3",
                    Status = "Active",
                    IsOnline = false,
                    LastSeen = DateTime.Now
                };

                db.Students.AddRange(studentA, studentB, studentC);
                await db.SaveChangesAsync();

                // Swipe Student B CheckIn today
                var logB = new EventLog
                {
                    EventType = "GateCheckIn",
                    Actor = studentB.StudentCode,
                    Timestamp = DateTime.Now,
                    Details = "{\"Location\":\"Cổng chính\"}"
                };
                db.EventLogs.Add(logB);

                // Leave Request Student C Approved today
                var leaveC = new StudentLeaveRequest
                {
                    StudentId = studentC.Id,
                    StudentName = studentC.FullName,
                    ClassName = studentC.ClassName,
                    LeaveDate = today,
                    Reason = "Cảm sốt",
                    Status = "Approved",
                    CreatedAt = DateTime.Now
                };
                db.StudentLeaveRequests.Add(leaveC);
                await db.SaveChangesAsync();

                try
                {
                    var vm = new GateMonitorViewModel();
                    await vm.RefreshDataCommand.ExecuteAsync(null);

                    // Assert
                    Assert.Contains(vm.AbsentStudents, s => s.StudentCode == studentA.StudentCode);
                    Assert.DoesNotContain(vm.AbsentStudents, s => s.StudentCode == studentB.StudentCode);
                    Assert.DoesNotContain(vm.AbsentStudents, s => s.StudentCode == studentC.StudentCode);
                }
                finally
                {
                    using (var cleanupDb = new AppDbContext())
                    {
                        cleanupDb.Students.RemoveRange(studentA, studentB, studentC);
                        cleanupDb.EventLogs.Remove(logB);
                        cleanupDb.StudentLeaveRequests.Remove(leaveC);
                        await cleanupDb.SaveChangesAsync();
                    }
                }
            }
        }
    }
}
