using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.Selection.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 17121-18925
// #region Object Selection Event Handlers
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Object Selection Event Handlers

        /// <summary>
        /// Called when selection changes (single object selected/deselected)
        /// </summary>
        private void OnSelectionChanged(object? sender, SelectableObject? selectedObject)
        {
            _selectionManager?.HideAllAdorners();

            if (selectedObject != null)
            {
                System.Diagnostics.Debug.WriteLine($"🎯 OnSelectionChanged: Object selected");
                System.Diagnostics.Debug.WriteLine($"   Type: {selectedObject.Type}");
                System.Diagnostics.Debug.WriteLine($"   Bounds: {selectedObject.Bounds}");
                System.Diagnostics.Debug.WriteLine($"   Position: {selectedObject.Position}");
                System.Diagnostics.Debug.WriteLine($"   Size: {selectedObject.Size}");
                System.Diagnostics.Debug.WriteLine($"   Element: {selectedObject.Element?.GetType().Name ?? "null"}");
                
                // Show selection box
                if (_selectionBox != null)
                {
                    System.Diagnostics.Debug.WriteLine($"   Calling _selectionBox.AttachTo()...");
                    _selectionBox.AttachTo(selectedObject);
                    System.Diagnostics.Debug.WriteLine($"   SelectionBox Visibility: {_selectionBox.Visibility}");
                    System.Diagnostics.Debug.WriteLine($"   SelectionBox Width: {_selectionBox.Width}");
                    System.Diagnostics.Debug.WriteLine($"   SelectionBox Height: {_selectionBox.Height}");
                    System.Diagnostics.Debug.WriteLine($"   SelectionBox Left: {Canvas.GetLeft(_selectionBox)}");
                    System.Diagnostics.Debug.WriteLine($"   SelectionBox Top: {Canvas.GetTop(_selectionBox)}");
                }
                else
                {
                    System.Diagnostics.Debug.WriteLine($"   ❌ _selectionBox is NULL!");
                }
                
                // ✅ G2.1: Auto-Flip toolbar position
                var bounds = selectedObject.Bounds;
                var toolbarPosition = CalculateOptimalToolbarPosition(bounds);
                _contextToolbar?.ShowAt(toolbarPosition, selectedObject);
                
                // Update toolbar UI
                _contextToolbar?.UpdateLockIcon(selectedObject.IsLocked);
                _contextToolbar?.UpdateColorPreview(selectedObject.StrokeColor);
                
                System.Diagnostics.Debug.WriteLine($"✅ Selected: {selectedObject.Id}, Type: {selectedObject.Type}");
            }
            else
            {
                // Hide all selection UI
                _selectionBox?.Detach();
                _contextToolbar?.Hide();
                _thicknessPicker?.Hide();
                _colorPicker?.Hide();
                _moreMenu?.Hide();
                _floatingTouchKeyboard?.HideKeyboard();
                
                System.Diagnostics.Debug.WriteLine("❌ Selection cleared");
            }
        }

        /// <summary>
        /// Called when multiple objects are selected
        /// </summary>
        private void OnMultiSelectionChanged(object? sender, List<SelectableObject> selectedObjects)
        {
            if (selectedObjects == null || selectedObjects.Count == 0)
            {
                _selectionBox?.Detach();
                _contextToolbar?.Hide();
                System.Diagnostics.Debug.WriteLine("📦 Multi-selection: 0 objects - hiding selection box & toolbar");
                return;
            }

            System.Diagnostics.Debug.WriteLine($"📦 Multi-selection: {selectedObjects.Count} objects");

            try
            {
                if (selectedObjects.Count == 1)
                {
                    var singleObj = selectedObjects[0];
                    singleObj.UpdateBounds();

                    // Đảm bảo Bounds và Size chính xác trước khi Attach SelectionBox
                    if (singleObj.Bounds.IsEmpty || singleObj.Size.Width <= 0 || singleObj.Size.Height <= 0)
                    {
                        if (singleObj.Element is FrameworkElement fe)
                        {
                            double left = Canvas.GetLeft(fe);
                            double top = Canvas.GetTop(fe);
                            if (double.IsNaN(left)) left = 0;
                            if (double.IsNaN(top)) top = 0;
                            double w = fe.ActualWidth > 0 ? fe.ActualWidth : (double.IsNaN(fe.Width) ? 30 : fe.Width);
                            double h = fe.ActualHeight > 0 ? fe.ActualHeight : (double.IsNaN(fe.Height) ? 30 : fe.Height);
                            
                            singleObj.Position = new Point(left, top);
                            singleObj.Size = new Size(w, h);
                            singleObj.Bounds = new Rect(left, top, w, h);
                        }
                    }

                    if (_selectionBox != null)
                    {
                        _selectionBox.AttachTo(singleObj);
                    }
                    if (_contextToolbar != null)
                    {
                        var bounds = singleObj.Bounds;
                        var position = CalculateOptimalToolbarPosition(bounds);
                        _contextToolbar.ShowAt(position, singleObj);
                    }
                }
                else
                {
                    // Multi-selection (2 or more objects)
                    double minX = double.MaxValue;
                    double minY = double.MaxValue;
                    double maxX = double.MinValue;
                    double maxY = double.MinValue;

                    foreach (var obj in selectedObjects)
                    {
                        obj.UpdateBounds();
                        var bounds = obj.Bounds;
                        if (!bounds.IsEmpty)
                        {
                            minX = Math.Min(minX, bounds.Left);
                            minY = Math.Min(minY, bounds.Top);
                            maxX = Math.Max(maxX, bounds.Right);
                            maxY = Math.Max(maxY, bounds.Bottom);
                        }
                    }

                    if (minX < double.MaxValue && minY < double.MaxValue)
                    {
                        var groupRect = new Rect(minX, minY, maxX - minX, maxY - minY);
                        
                        // Tạo đối tượng ảo đại diện cho nhóm để hiển thị SelectionBox bao ngoài
                        var groupContainer = new SelectableObject
                        {
                            Position = new Point(groupRect.X, groupRect.Y),
                            Size = new Size(groupRect.Width, groupRect.Height),
                            Bounds = groupRect,
                            Type = ObjectType.Group,
                            IsGroup = true,
                            GroupMembers = selectedObjects.ToList()
                        };

                        if (_selectionBox != null)
                        {
                            _selectionBox.AttachTo(groupContainer);
                        }

                        if (_contextToolbar != null)
                        {
                            var position = CalculateOptimalToolbarPosition(groupRect);
                            _contextToolbar.ShowAt(position, selectedObjects[0]);
                            _contextToolbar.UpdateLockIcon(selectedObjects.All(o => o.IsLocked));
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Error in OnMultiSelectionChanged: {ex.Message}");
            }
        }

        #region Transform Snapshot Helpers for Canvas Drag & Toolbar

        private System.Collections.Generic.Dictionary<SelectableObject, ElementTransformState> _canvasDragInitialStates = new();

        /// <summary>
        /// Chụp lại snapshot trạng thái hình học của toàn bộ các đối tượng đang được chọn
        /// </summary>
        private System.Collections.Generic.Dictionary<SelectableObject, ElementTransformState> CaptureSelectedObjectsTransformStates()
        {
            var dict = new System.Collections.Generic.Dictionary<SelectableObject, ElementTransformState>();
            var selected = _selectionManager?.GetSelectedObjects();
            if (selected != null && selected.Count > 0)
            {
                foreach (var obj in selected)
                {
                    if (obj != null)
                    {
                        if (obj.IsGroup && obj.GroupMembers != null && obj.GroupMembers.Count > 0)
                        {
                            foreach (var m in obj.GroupMembers)
                            {
                                if (m != null) dict[m] = ElementTransformState.Create(m);
                            }
                        }
                        else
                        {
                            dict[obj] = ElementTransformState.Create(obj);
                        }
                    }
                }
            }
            else if (_draggedSelectionObject != null)
            {
                if (_draggedSelectionObject.IsGroup && _draggedSelectionObject.GroupMembers != null && _draggedSelectionObject.GroupMembers.Count > 0)
                {
                    foreach (var m in _draggedSelectionObject.GroupMembers)
                    {
                        if (m != null) dict[m] = ElementTransformState.Create(m);
                    }
                }
                else
                {
                    dict[_draggedSelectionObject] = ElementTransformState.Create(_draggedSelectionObject);
                }
            }
            return dict;
        }

        /// <summary>
        /// Chụp snapshot cho một đối tượng đơn hoặc toàn bộ thành viên nếu là nhóm
        /// </summary>
        private System.Collections.Generic.Dictionary<SelectableObject, ElementTransformState> CaptureTargetTransformStates(SelectableObject? targetObj)
        {
            var dict = new System.Collections.Generic.Dictionary<SelectableObject, ElementTransformState>();
            if (targetObj == null) return dict;

            if (targetObj.IsGroup || targetObj.Type == ObjectType.Group || (targetObj.GroupMembers != null && targetObj.GroupMembers.Count > 0))
            {
                foreach (var m in targetObj.GroupMembers)
                {
                    if (m != null) dict[m] = ElementTransformState.Create(m);
                }
            }
            else
            {
                dict[targetObj] = ElementTransformState.Create(targetObj);
            }
            return dict;
        }

        /// <summary>
        /// Xử lý khi SelectionBox hoàn thành thao tác Move/Resize/Rotate
        /// </summary>
        private void OnSelectionBoxTransformCompleted(object? sender, SelectionBox.TransformCompletedEventArgs e)
        {
            if (e != null && e.InitialStates != null && e.FinalStates != null && e.InitialStates.Count > 0)
            {
                RecordTransformAction(e.InitialStates, e.FinalStates, e.Description);
            }
        }

        #endregion

        /// <summary>
        /// Mouse down handler for object selection & rectangle selection
        /// </summary>
        private void MainBoard_SelectionMouseDown(object sender, MouseButtonEventArgs e)
        {
            if (!_objectSelectionMode || _selectionManager == null || _isLassoMode)
                return;

            // ✅ QC_4.2_TOUCH_TELEPORT_FIX: Safety guard
            // Đảm bảo reset trạng thái drag cũ trước khi xử lý click mới, tránh lỗi Teleport
            if (_draggedSelectionObject != null)
            {
                _draggedSelectionObject = null;
                _isDraggingSelection = false;
            }

            Point clickPoint = e.GetPosition(MainInteractiveBoard);
            bool isCtrlPressed = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);
            var hitObject = _selectionManager.HitTest(clickPoint);
            
            // 🪄 Magic Wand Mode handling (N27 FIX: Support both Single Click Wand & Drag Rectangle Wand)
            if (_isMagicWandMode)
            {
                _rectangleSelectionStartPoint = clickPoint;
                _isRectangleSelecting = false;
                _draggedSelectionObject = null;
                _pendingHitObject = hitObject;
                _pendingIsCtrl = isCtrlPressed;
                _isPreparingRectangleSelection = true; // ✅ Mở khóa bảo vệ
                return;
            }
            
            // ✅ QC_4.2_WIDGET_DRAG_FIX: Kiểm tra xem người dùng có bấm vào đối tượng ĐÃ ĐƯỢC CHỌN hay không
            // Ưu tiên cho phép kéo di chuyển đối tượng/bảng/widget (Data Table, 3D Graph...) bất kể chạm vào cell hay nội dung bên trong!
            var currentSelection = _selectionManager.GetSelectedObjects();
            bool isClickOnSelectedObject = hitObject != null && currentSelection != null && currentSelection.Contains(hitObject);

            // ✅ FIX CẢM ỨNG: Nếu chạm vào bất kỳ đâu bên trong khung SelectionBox đang hiển thị,
            // xác định chắc chắn là thao tác kéo di chuyển vùng chọn hiện tại (kể cả chạm vào khoảng trống giữa các nét)
            if (!isClickOnSelectedObject && _selectionBox != null && _selectionBox.Visibility == Visibility.Visible && _selectionBox.AttachedObject != null)
            {
                if (_selectionBox.AttachedObject.Bounds.Contains(clickPoint))
                {
                    isClickOnSelectedObject = true;
                    hitObject = _selectionBox.AttachedObject;
                }
            }

            if (isClickOnSelectedObject && !isCtrlPressed)
            {
                // Nếu bấm vào nút chức năng cụ thể (như nút Edit ✏️, Move 🖐️ hay Delete ❌), nhường event cho nút xử lý
                if (e.OriginalSource is DependencyObject depObj && QASmartTouch.Utilities.InputValidationHelper.IsEventFromButton(depObj, MainInteractiveBoard))
                {
                    _isDraggingSelection = false;
                    _draggedSelectionObject = null;
                    _isPreparingRectangleSelection = false; // ✅ Khóa vẽ vùng chọn
                    return;
                }

                // ✅ QC_4.2_TABLE_BODY_NO_DRAG: Nếu là Bảng dữ liệu / Container dạng StackPanel, 
                // chạm vào thân bảng sẽ HIỂN THỊ nút thao tác và cho phép viết/vẽ, KHÔNG di chuyển bảng khi quệt thân!
                // Muốn di chuyển thì giáo viên click giữ nút Di chuyển 🖐️ trên thanh thao tác.
                if (hitObject != null && hitObject.Element is StackPanel)
                {
                    _draggedSelectionObject = null;
                    _isDraggingSelection = false;
                    _pendingHitObject = null;
                    _isPreparingRectangleSelection = false; // ✅ Khóa vẽ vùng chọn
                    return;
                }

                // Với đối tượng vẽ thông thường: Click vào đối tượng ĐÃ CHỌN -> Chuẩn bị kéo di chuyển
                _draggedSelectionObject = hitObject;
                _selectionDragStartPoint = clickPoint;
                _isDraggingSelection = false;
                _pendingHitObject = null;
                _isPreparingRectangleSelection = false; // ✅ Khóa vẽ vùng chọn
                _canvasDragInitialStates = CaptureSelectedObjectsTransformStates();
                System.Diagnostics.Debug.WriteLine($"🔒 Dragging existing selection - anchor: {hitObject.Type}");
                return;
            }

            // Nếu chạm vào thanh công cụ / hệ thống ngoài canvas, không vẽ vùng chọn rectangle
            if (QASmartTouch.Utilities.InputValidationHelper.IsEventFromInteractiveControl(e.OriginalSource, MainInteractiveBoard))
            {
                _isDraggingSelection = false;
                _draggedSelectionObject = null;
                _isPreparingRectangleSelection = false; // ✅ Khóa vẽ vùng chọn
                return;
            }

            // Otherwise (clicked empty space OR clicked an unselected object):
            // Prepare for potential Rectangle Selection OR single-click selection
            _rectangleSelectionStartPoint = clickPoint;
            _isRectangleSelecting = false;
            _draggedSelectionObject = null;
            _pendingHitObject = hitObject;
            _pendingIsCtrl = isCtrlPressed;
            _isPreparingRectangleSelection = true; // ✅ Mở khóa để cho phép vẽ vùng chọn
            
            System.Diagnostics.Debug.WriteLine($"🖱️ Selection click at ({clickPoint.X:F0}, {clickPoint.Y:F0}), hit={hitObject?.Type.ToString() ?? "null"}, Ctrl={isCtrlPressed}");
        }
        
        /// <summary>
        /// ✅ GĐ1-FIX: Helper method di chuyển 1 SelectableObject theo dragVector
        /// Hỗ trợ Polyline, Line, FrameworkElement (Rectangle, Ellipse, Image, TextBlock, Border)
        /// </summary>
        private void MoveSelectableObject(SelectableObject obj, Vector dragVector)
        {
            if (obj == null) return;
            
            // Xử lý nhóm đối tượng (Group / Multi-selection) kể cả khi Element == null
            if (obj.IsGroup || obj.Type == ObjectType.Group || (obj.GroupMembers != null && obj.GroupMembers.Count > 0))
            {
                foreach (var member in obj.GroupMembers)
                {
                    if (member == null || member.IsLocked) continue;
                    MoveSelectableObject(member, dragVector);
                }
                obj.UpdateBounds();
                return;
            }

            if (obj.Element == null) return;
            
            if (obj.Element is Polyline polyline)
            {
                // Di chuyển tất cả points
                for (int i = 0; i < polyline.Points.Count; i++)
                {
                    Point oldPoint = polyline.Points[i];
                    polyline.Points[i] = new Point(oldPoint.X + dragVector.X, oldPoint.Y + dragVector.Y);
                }
                // Recalculate bounds
                if (polyline.Points.Count > 0)
                {
                    double minX = double.MaxValue, minY = double.MaxValue;
                    double maxX = double.MinValue, maxY = double.MinValue;
                    foreach (var p in polyline.Points)
                    {
                        minX = Math.Min(minX, p.X); minY = Math.Min(minY, p.Y);
                        maxX = Math.Max(maxX, p.X); maxY = Math.Max(maxY, p.Y);
                    }
                    obj.Position = new Point(minX, minY);
                    obj.Size = new Size(maxX - minX, maxY - minY);
                }
            }
            else if (obj.Element is Polygon polygon)
            {
                if (polygon.Points != null && polygon.Points.Count > 0)
                {
                    for (int i = 0; i < polygon.Points.Count; i++)
                    {
                        Point oldPoint = polygon.Points[i];
                        polygon.Points[i] = new Point(oldPoint.X + dragVector.X, oldPoint.Y + dragVector.Y);
                    }
                    double minX = double.MaxValue, minY = double.MaxValue;
                    double maxX = double.MinValue, maxY = double.MinValue;
                    foreach (var p in polygon.Points)
                    {
                        minX = Math.Min(minX, p.X); minY = Math.Min(minY, p.Y);
                        maxX = Math.Max(maxX, p.X); maxY = Math.Max(maxY, p.Y);
                    }
                    if (!double.IsNaN(Canvas.GetLeft(polygon))) Canvas.SetLeft(polygon, double.NaN);
                    if (!double.IsNaN(Canvas.GetTop(polygon))) Canvas.SetTop(polygon, double.NaN);

                    obj.Position = new Point(minX, minY);
                    obj.Size = new Size(maxX - minX, maxY - minY);
                    obj.Bounds = new Rect(minX, minY, maxX - minX, maxY - minY);
                }
            }
            else if (obj.Element is System.Windows.Shapes.Line line)
            {
                // Di chuyển Line endpoints
                line.X1 += dragVector.X; line.Y1 += dragVector.Y;
                line.X2 += dragVector.X; line.Y2 += dragVector.Y;
                double minX = Math.Min(line.X1, line.X2);
                double minY = Math.Min(line.Y1, line.Y2);
                double w = Math.Max(Math.Abs(line.X2 - line.X1), line.StrokeThickness);
                double h = Math.Max(Math.Abs(line.Y2 - line.Y1), line.StrokeThickness);

                if (!double.IsNaN(Canvas.GetLeft(line))) Canvas.SetLeft(line, double.NaN);
                if (!double.IsNaN(Canvas.GetTop(line))) Canvas.SetTop(line, double.NaN);

                obj.Position = new Point(minX, minY);
                obj.Size = new Size(w, h);
                obj.Bounds = new Rect(minX, minY, w, h);
            }
            else if (obj.Element is System.Windows.Shapes.Path path && path.Data != null)
            {
                // ✅ QC_4.2_TOUCH_MOVE_FIX: Di chuyển TranslateTransform cho Path
                if (path.RenderTransform is TransformGroup tg)
                {
                    var tt = tg.Children.OfType<TranslateTransform>().FirstOrDefault();
                    if (tt == null)
                    {
                        tt = new TranslateTransform();
                        tg.Children.Add(tt);
                    }
                    tt.X += dragVector.X;
                    tt.Y += dragVector.Y;
                }
                else if (path.RenderTransform is TranslateTransform tt)
                {
                    tt.X += dragVector.X;
                    tt.Y += dragVector.Y;
                }
                else
                {
                    var tgNew = new TransformGroup();
                    if (path.RenderTransform != null && path.RenderTransform != Transform.Identity)
                        tgNew.Children.Add(path.RenderTransform);
                    tgNew.Children.Add(new TranslateTransform(dragVector.X, dragVector.Y));
                    path.RenderTransform = tgNew;
                }
                obj.Position = new Point(obj.Position.X + dragVector.X, obj.Position.Y + dragVector.Y);
            }
            else if (obj.Element is FrameworkElement fe)
            {
                // Di chuyển Canvas position (Rectangle, Ellipse, Image, TextBlock, Border)
                double cX = Canvas.GetLeft(fe), cY = Canvas.GetTop(fe);
                if (double.IsNaN(cX)) cX = 0;
                if (double.IsNaN(cY)) cY = 0;
                double newX = cX + dragVector.X, newY = cY + dragVector.Y;
                Canvas.SetLeft(fe, newX);
                Canvas.SetTop(fe, newY);
                obj.Position = new Point(newX, newY);
            }
            obj.UpdateBounds();
        }

        /// <summary>
        /// Handle mouse move for dragging selected objects or drawing rectangle selection
        /// </summary>
        private void MainBoard_SelectionMouseMove(object sender, MouseEventArgs e)
        {
            if (!_objectSelectionMode || _isLassoMode)
                return;

            Point currentPoint = e.GetPosition(MainInteractiveBoard);
            
            // 1. Handle object drag & drop (moving ALREADY SELECTED objects)
            if (_draggedSelectionObject != null && e.LeftButton == MouseButtonState.Pressed)
            {
                Vector dragVector = currentPoint - _selectionDragStartPoint;
                if (!_isDraggingSelection && (Math.Abs(dragVector.X) > 3 || Math.Abs(dragVector.Y) > 3))
                {
                    _isDraggingSelection = true;
                    System.Diagnostics.Debug.WriteLine($"🎯 Started dragging object: {_draggedSelectionObject.Type}");
                }
                
                if (_isDraggingSelection && _draggedSelectionObject.Element != null)
                {
                    var selectedObjects = _selectionManager?.GetSelectedObjects();
                    bool isMultiDrag = selectedObjects != null && selectedObjects.Count > 1;
                    
                    if (isMultiDrag)
                    {
                        foreach (var obj in selectedObjects!)
                        {
                            MoveSelectableObject(obj, dragVector);
                        }
                        System.Diagnostics.Debug.WriteLine(
                            $"🎯 Group moved: {selectedObjects.Count} objects by ({dragVector.X:F0}, {dragVector.Y:F0})");
                    }
                    else
                    {
                        MoveSelectableObject(_draggedSelectionObject, dragVector);
                        System.Diagnostics.Debug.WriteLine(
                            $"🎯 {_draggedSelectionObject.Type} moved by ({dragVector.X:F0}, {dragVector.Y:F0})");
                    }
                    
                    _selectionDragStartPoint = currentPoint;
                    
                    if (isMultiDrag)
                    {
                        _selectionManager?.RefreshGroupAdorner();
                        
                        double gMinX = double.MaxValue, gMinY = double.MaxValue;
                        double gMaxX = double.MinValue, gMaxY = double.MinValue;
                        foreach (var obj in selectedObjects!)
                        {
                            var b = obj.Bounds;
                            gMinX = Math.Min(gMinX, b.Left);  gMinY = Math.Min(gMinY, b.Top);
                            gMaxX = Math.Max(gMaxX, b.Right);  gMaxY = Math.Max(gMaxY, b.Bottom);
                        }
                        var groupRect = new Rect(gMinX, gMinY, gMaxX - gMinX, gMaxY - gMinY);

                        // ✅ QC_4.2_TOUCH_MOVE_FIX: Cập nhật vị trí & kích thước cho groupObject đang được attach với _selectionBox
                        if (_selectionBox != null && _selectionBox.Visibility == Visibility.Visible)
                        {
                            var attachedGroup = _selectionBox.AttachedObject;
                            if (attachedGroup != null && (attachedGroup.IsGroup || attachedGroup.Type == ObjectType.Group))
                            {
                                attachedGroup.Position = new Point(gMinX, gMinY);
                                attachedGroup.Size = new Size(groupRect.Width, groupRect.Height);
                                attachedGroup.Bounds = groupRect;
                            }
                            _selectionBox.UpdatePosition();
                        }

                        var toolbarPos = CalculateOptimalToolbarPosition(groupRect);
                        _contextToolbar?.ShowAt(toolbarPos, _draggedSelectionObject);
                    }
                    else
                    {
                        _selectionBox?.UpdatePosition();
                        if (_draggedSelectionObject.Bounds != Rect.Empty)
                        {
                            var bounds = _draggedSelectionObject.Bounds;
                            var toolbarPosition = CalculateOptimalToolbarPosition(bounds);
                            _contextToolbar?.ShowAt(toolbarPosition, _draggedSelectionObject);
                        }
                    }
                }
                return;
            }

            // ✅ QC_4.2_WIDGET_DRAG_FIX: Chỉ kiểm tra IsEventFromInteractiveControl nếu KHÔNG đang kéo di chuyển đối tượng
            if (QASmartTouch.Utilities.InputValidationHelper.IsEventFromInteractiveControl(e.OriginalSource, MainInteractiveBoard))
            {
                _isDraggingSelection = false;
                _draggedSelectionObject = null;
                if (MainInteractiveBoard.IsMouseCaptured)
                    MainInteractiveBoard.ReleaseMouseCapture();
                return;
            }
            
            // 2. Handle Rectangle Selection Drag (when dragging on canvas)
            if (e.LeftButton == MouseButtonState.Pressed && _draggedSelectionObject == null && _isPreparingRectangleSelection)
            {
                // ✅ CRITICAL FIX: Đang kéo chốt resize hoặc xoay SelectionBox -> Không tạo khung khoanh vùng chọn rectangle
                if (_selectionBox != null && _selectionBox.IsTransforming)
                {
                    if (_rectangleSelectionPreview != null)
                    {
                        MainInteractiveBoard.Children.Remove(_rectangleSelectionPreview);
                        _rectangleSelectionPreview = null;
                    }
                    _isRectangleSelecting = false;
                    return;
                }

                Vector dragVector = currentPoint - _rectangleSelectionStartPoint;
                if (!_isRectangleSelecting && (Math.Abs(dragVector.X) > 5 || Math.Abs(dragVector.Y) > 5))
                {
                    _isRectangleSelecting = true;
                    
                    // Create preview rectangle if needed
                    if (_rectangleSelectionPreview == null)
                    {
                        _rectangleSelectionPreview = new Rectangle
                        {
                            Stroke = new SolidColorBrush(Color.FromRgb(52, 152, 219)), // Dodger blue
                            StrokeThickness = 2,
                            StrokeDashArray = new DoubleCollection { 5, 3 },
                            Fill = new SolidColorBrush(Color.FromArgb(30, 52, 152, 219)),
                            RadiusX = 3,
                            RadiusY = 3
                        };
                        MainInteractiveBoard.Children.Add(_rectangleSelectionPreview);
                        Canvas.SetZIndex(_rectangleSelectionPreview, 9999);
                    }
                }
                
                if (_isRectangleSelecting && _rectangleSelectionPreview != null)
                {
                    double left = Math.Min(_rectangleSelectionStartPoint.X, currentPoint.X);
                    double top = Math.Min(_rectangleSelectionStartPoint.Y, currentPoint.Y);
                    double width = Math.Abs(currentPoint.X - _rectangleSelectionStartPoint.X);
                    double height = Math.Abs(currentPoint.Y - _rectangleSelectionStartPoint.Y);
                    
                    Canvas.SetLeft(_rectangleSelectionPreview, left);
                    Canvas.SetTop(_rectangleSelectionPreview, top);
                    _rectangleSelectionPreview.Width = width;
                    _rectangleSelectionPreview.Height = height;
                }
            }
        }
        
        /// <summary>
        /// Handle mouse up to complete drag operation or rectangle selection
        /// </summary>
        private void MainBoard_SelectionMouseUp(object sender, MouseButtonEventArgs e)
        {
            if (_isLassoMode)
                return;
            // 1. Handle Rectangle Selection completion
            if (_rectangleSelectionPreview != null || _isRectangleSelecting)
            {
                Point endPoint = e.GetPosition(MainInteractiveBoard);
                
                double left = Math.Min(_rectangleSelectionStartPoint.X, endPoint.X);
                double top = Math.Min(_rectangleSelectionStartPoint.Y, endPoint.Y);
                double right = Math.Max(_rectangleSelectionStartPoint.X, endPoint.X);
                double bottom = Math.Max(_rectangleSelectionStartPoint.Y, endPoint.Y);
                Rect selectionRect = new Rect(left, top, right - left, bottom - top);
                _lastDraggedSelectionRect = selectionRect;
                
                double rectW = right - left;
                double rectH = bottom - top;

                // Remove preview rectangle
                if (_rectangleSelectionPreview != null)
                {
                    MainInteractiveBoard.Children.Remove(_rectangleSelectionPreview);
                    _rectangleSelectionPreview = null;
                }
                _isRectangleSelecting = false;

                if (rectW > 5 || rectH > 5)
                {
                    // Dragged rectangle selection
                    var objectsInRect = _selectionManager?.GetObjectsInRect(selectionRect);
                    if (objectsInRect != null && objectsInRect.Count > 0)
                    {
                        _selectionManager?.SelectMultiple(objectsInRect);
                        System.Diagnostics.Debug.WriteLine($"📐 Rectangle selection: {objectsInRect.Count} object(s) selected");
                    }
                    else
                    {
                        _selectionManager?.DeselectAll();
                        System.Diagnostics.Debug.WriteLine("📐 Rectangle selection: No objects found, deselected all");
                    }
                    _pendingHitObject = null;

                    // Trigger pending smart action if user initiated OCR/Translate/Read/Search/AIChat
                    if (_pendingSmartAction.HasValue)
                    {
                        var pendingAction = _pendingSmartAction.Value;
                        _pendingSmartAction = null;
                        _ = Dispatcher.BeginInvoke(new Action(async () =>
                        {
                            await ExecuteSmartActionAsync(pendingAction);
                        }), System.Windows.Threading.DispatcherPriority.Background);
                    }

                    return;
                }
            }
            
            // 2. Xử lý kết thúc thao tác với đối tượng đã chọn (Kéo di chuyển hoặc Chạm giữ)
            if (_draggedSelectionObject != null)
            {
                if (_isDraggingSelection)
                {
                    // ✅ N23 FIX: Rebuild QuadTree spatial index ngay khi kết thúc kéo di chuyển
                    _selectionManager?.RebuildQuadTree();
                    var finalStates = CaptureSelectedObjectsTransformStates();
                    RecordTransformAction(_canvasDragInitialStates, finalStates, "Move object(s)");
                    System.Diagnostics.Debug.WriteLine("🌳 Selection drag ended: Rebuilt QuadTree & recorded Undo action.");
                }

                // Reset toàn bộ cờ kéo di chuyển
                _isDraggingSelection = false;
                _draggedSelectionObject = null;
                _isPreparingRectangleSelection = false;
                _pendingHitObject = null;
                _canvasDragInitialStates.Clear();

                // ✅ FIX TRIỆT ĐỂ: Thao tác trên đối tượng đã chọn xong thì RETURN NGAY,
                // TUYỆT ĐỐI KHÔNG để rơi xuống nhánh DeselectAll() bên dưới!
                return;
            }

            if (_isMagicWandMode && !_isRectangleSelecting)
            {
                Point clickPoint = e.GetPosition(MainInteractiveBoard);
                PerformMagicWandSelection(clickPoint);
                return;
            }

            // 3. Xử lý Single Click Selection (khi người dùng click chọn đối tượng mới hoặc click ra ngoài để hủy chọn)
            if (_pendingHitObject != null)
            {
                if (_pendingIsCtrl)
                {
                    _selectionManager?.ToggleSelection(_pendingHitObject);
                }
                else
                {
                    _selectionManager?.SelectObject(_pendingHitObject);
                }
            }
            else
            {
                if (!_pendingIsCtrl)
                {
                    _selectionManager?.DeselectAll();
                }
            }
            
            // Cleanup drag states
            _isDraggingSelection = false;
            _draggedSelectionObject = null;
            _pendingHitObject = null;
            _isPreparingRectangleSelection = false; // ✅ Khóa lại cờ hiệu sau khi xong việc
        }

        /// <summary>
        /// Called when user transforms object via SelectionBox handles
        /// </summary>
        private void OnObjectTransformed(object? sender, SelectableObject transformedObject)
        {
            // ✅ Rebuild QuadTree spatial index ngay sau khi transform (kéo di chuyển, resize, rotate)
            _selectionManager?.RebuildQuadTree();

            // Refresh context toolbar position after transform
            var targetObj = _selectionManager?.SelectedObject ?? transformedObject;
            if (targetObj != null && targetObj.Bounds != Rect.Empty)
            {
                var bounds = targetObj.Bounds;
                // ✅ G2.1: Auto-Flip toolbar position
                var toolbarPosition = CalculateOptimalToolbarPosition(bounds);
                _contextToolbar?.ShowAt(toolbarPosition, targetObj);
            }
        }

        // ContextToolbar button handlers
        private void OnToolbarCopyClicked(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine($"🔍 OnToolbarCopyClicked called");
            System.Diagnostics.Debug.WriteLine($"   _selectionManager = {(_selectionManager != null ? "EXISTS" : "NULL")}");
            System.Diagnostics.Debug.WriteLine($"   SelectedObject = {(_selectionManager?.SelectedObject != null ? _selectionManager.SelectedObject.Type.ToString() : "NULL")}");
            
            var copied = _selectionManager?.CopySelectedObject();
            if (copied != null)
            {
                System.Diagnostics.Debug.WriteLine($"✅ Copied to clipboard: {copied.Type} - Click anywhere to paste");
                
                // Deselect current object so user can click to paste
                _selectionManager?.DeselectAll();
            }
            else
            {
                System.Diagnostics.Debug.WriteLine($"❌ Copy failed: No object copied");
            }
        }

        private async void OnToolbarRecognizeHandwritingClicked(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine($"✍️ OnToolbarRecognizeHandwritingClicked called");
            
            try
            {
                if (_captureService == null)
                {
                    _captureService = new SelectionCaptureService();
                }

                // Get selection bounds
                Rect selectionBounds;
                if (_selectionManager?.SelectedObject != null)
                {
                    // Single object selected
                    selectionBounds = _selectionManager.SelectedObject.Bounds;
                }
                else if (_selectionManager?.GetSelectedObjects()?.Count > 0)
                {
                    // Multiple objects selected - get combined bounds
                    selectionBounds = _selectionManager.GetMultiSelectionBounds();
                }
                else
                {
                    MessageBox.Show(
                        "Vui lòng chọn vùng chứa chữ viết trước.",
                        "Thông báo",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    return;
                }

                if (selectionBounds.IsEmpty || selectionBounds.Width <= 0 || selectionBounds.Height <= 0)
                {
                    MessageBox.Show("Vùng chọn không hợp lệ.", "Thông báo", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                System.Diagnostics.Debug.WriteLine($"📐 Selection bounds: {selectionBounds}");

                // Create and show dialog
                var dialog = new HandwritingRecognitionDialog
                {
                    Owner = this
                };
                dialog.ShowLoading();

                // Sử dụng TaskCompletionSource để chờ user đóng dialog trong chế độ non-modal
                var dialogClosedTcs = new TaskCompletionSource<bool>();
                dialog.Closed += (s, args) => dialogClosedTcs.TrySetResult(dialog.UserAccepted);
                dialog.Show();

                // Capture selection area as clean image (temporarily hides SelectionBox & ContextToolbar for pure stroke image)
                var (bitmap, imageBytes) = CaptureCleanSelectionArea(selectionBounds);
                if (bitmap == null && imageBytes == null)
                {
                    dialog.Close();
                    MessageBox.Show("Lỗi khi capture vùng chọn.", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                List<HandwritingRecognitionResult> results = new List<HandwritingRecognitionResult>();

                // 1. Thử Google Cloud Vision API nếu service đã được khởi tạo
                if (_handwritingService != null && _handwritingService.IsInitialized && imageBytes != null)
                {
                    try
                    {
                        results = await _handwritingService.RecognizeHandwritingAsync(imageBytes, maxResults: 5);
                    }
                    catch (Exception gEx)
                    {
                        System.Diagnostics.Debug.WriteLine($"⚠️ Google Vision API error ({gEx.Message}). Falling back to Windows OCR Service...");
                    }
                }

                // 2. Nếu Google Vision API không trả kết quả hoặc gặp lỗi (PermissionDenied / Cloud Vision API disabled) -> Tự động chuyển sang Windows OCR Offline
                if ((results == null || results.Count == 0) && bitmap != null)
                {
                    if (_windowsOcrService == null)
                    {
                        _windowsOcrService = new WindowsOCRService();
                    }

                    var ocrRes = await _windowsOcrService.RecognizeTextAsync(bitmap);
                    if (ocrRes != null && ocrRes.IsSuccess && !string.IsNullOrWhiteSpace(ocrRes.Text))
                    {
                        results = new List<HandwritingRecognitionResult>
                        {
                            new HandwritingRecognitionResult
                            {
                                Text = ocrRes.Text.Trim(),
                                Confidence = 0.95f,
                                Rank = 0,
                                DetectedLanguage = "vi"
                            }
                        };
                    }
                }

                // 3. Thử Heuristic / Geometry Recognition fallback nếu cả 2 công cụ OCR không nhận diện được (ví dụ: chữ số 1 hoặc dấu đơn)
                if (results == null || results.Count == 0)
                {
                    var targetObject = _selectionManager?.SelectedObject ?? _selectionManager?.GetSelectedObjects()?.FirstOrDefault();
                    results = RecognizeStrokeGeometryFallback(targetObject);
                }

                if (results == null || results.Count == 0)
                {
                    dialog.ShowError("Không tìm thấy chữ viết rõ ràng trong vùng chọn.");
                    return;
                }

                // Kiểm tra nếu user đã đóng dialog trong lúc chờ
                if (dialogClosedTcs.Task.IsCompleted)
                {
                    return;
                }

                // Hiển thị ứng viên từ loại và kết quả trên dialog
                var candidates = _smartHandwritingRecognitionService.GenerateSpacingCandidates(results[0].Text);
                if (candidates.Count > 0 && _contextToolbar != null)
                {
                    _contextToolbar.ShowHandwritingCandidates(candidates);
                }

                // Show results in dialog
                dialog.ShowResults(results);

                // Chờ user bấm Insert hoặc Cancel (đóng dialog)
                bool userAccepted = await dialogClosedTcs.Task;
                
                if (userAccepted && dialog.SelectedResult != null)
                {
                    // User selected a result - insert text
                    InsertRecognizedText(
                        dialog.SelectedResult.Text,
                        selectionBounds,
                        dialog.ReplaceStrokes);
                    
                    System.Diagnostics.Debug.WriteLine($"✅ Inserted text: {dialog.SelectedResult.Text}");
                    ShowSmartStatusBadge($"☑ Đã chèn văn bản: \"{dialog.SelectedResult.Text}\"");
                }
            }
            catch (Exception ex)
            {
                ShowSmartStatusBadge($"❌ Lỗi nhận diện chữ viết: {ex.Message}");
            }
        }

        private void OnCandidateSelected(object? sender, string selectedText)
        {
            try
            {
                var selectedObjects = _selectionManager?.GetSelectedObjects();
                if (selectedObjects == null || selectedObjects.Count == 0) return;

                Rect bounds;
                if (_selectionManager?.SelectedObject != null)
                {
                    bounds = _selectionManager.SelectedObject.Bounds;
                }
                else
                {
                    bounds = _selectionManager?.GetMultiSelectionBounds() ?? Rect.Empty;
                }

                if (bounds.IsEmpty || bounds.Width <= 0 || bounds.Height <= 0) return;

                Color originalColor = _smartHandwritingRecognitionService.ExtractElementColor(selectedObjects[0].Element);
                double autoFontSize = _smartHandwritingRecognitionService.CalculateAutoFontSize(bounds.Height);

                // Remove original stroke elements
                foreach (var obj in selectedObjects)
                {
                    if (obj.Element != null && MainInteractiveBoard.Children.Contains(obj.Element))
                    {
                        MainInteractiveBoard.Children.Remove(obj.Element);
                        RecordRemoveAction(obj.Element, "Stroke");
                    }
                }

                // Create new TextBlock with matching original ink color & auto font size
                var textBlock = new TextBlock
                {
                    Text = selectedText,
                    FontSize = autoFontSize,
                    FontFamily = new FontFamily("Segoe UI"),
                    FontWeight = FontWeights.Medium,
                    Foreground = new SolidColorBrush(originalColor),
                    VerticalAlignment = VerticalAlignment.Center,
                    HorizontalAlignment = HorizontalAlignment.Center
                };

                Canvas.SetLeft(textBlock, bounds.Left);
                Canvas.SetTop(textBlock, bounds.Top);

                MainInteractiveBoard.Children.Add(textBlock);
                RecordAddAction(textBlock, "Text");

                _selectionManager?.DeselectAll();
                _selectionBox?.Detach();
                _contextToolbar?.Hide();
                RefreshSelectableObjects();

                System.Diagnostics.Debug.WriteLine($"✅ OCR candidate selected: '{selectedText}' with color {originalColor}");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ OnCandidateSelected error: {ex.Message}");
            }
        }

        private void OnFloatingKeyboardTextConfirmed(object? sender, string newText)
        {
            try
            {
                if (_editingTextBlock != null)
                {
                    _editingTextBlock.Text = newText;
                    RecordAddAction(_editingTextBlock, "Edit Text");
                    RefreshSelectableObjects();
                    _selectionBox?.UpdatePosition();
                    _editingTextBlock = null; // ✅ QC_4.2: Xóa tham chiếu vết tránh trôi biến
                    System.Diagnostics.Debug.WriteLine($"✅ In-place text updated: '{newText}'");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ OnFloatingKeyboardTextConfirmed error: {ex.Message}");
            }
        }

        private void OnTextEditRequested(object? sender, SelectableObject obj)
        {
            if (obj?.Element is TextBlock textBlock)
            {
                System.Diagnostics.Debug.WriteLine($"✏️ Double-click detected on TextBlock — starting in-place text editing");
                StartInPlaceTextEditing(textBlock);
            }
        }

        public void StartInPlaceTextEditing(TextBlock textBlock)
        {
            if (textBlock == null || _floatingTouchKeyboard == null) return;
            _editingTextBlock = textBlock;

            // [LOI_VID_53] Enforce min FontSize 24pt trên SMART TOUCH (phản biện TS. Bùi Văn Sơn)
            if (textBlock.FontSize < 24)
            {
                textBlock.FontSize = 24;
            }

            double left = Canvas.GetLeft(textBlock);
            double top = Canvas.GetTop(textBlock);
            if (double.IsNaN(left)) left = 100;
            if (double.IsNaN(top)) top = 100;

            Point pos = new Point(Math.Max(20, left), top + textBlock.ActualHeight + 10);

            // [LOI_VID_53] Truyền textBlock để tính SafeFocusScroll + vị trí thông minh
            _floatingTouchKeyboard.ShowWithText(textBlock.Text, pos, textBlock);
        }

        /// <summary>
        /// Insert recognized text as TextBox on canvas
        /// </summary>
        private void InsertRecognizedText(string text, Rect bounds, bool replaceStrokes)
        {
            try
            {
                // Create TextBox
                var textBox = new TextBox
                {
                    Text = text,
                    FontFamily = new System.Windows.Media.FontFamily("Segoe UI, Arial"),
                    FontSize = Math.Max(16, bounds.Height * 0.6), // Auto-size based on bounds
                    Foreground = Brushes.Black,
                    Background = Brushes.Transparent,
                    BorderThickness = new Thickness(0),
                    TextWrapping = TextWrapping.Wrap,
                    AcceptsReturn = false,
                    Width = Math.Max(100, bounds.Width),
                    MinHeight = Math.Max(30, bounds.Height)
                };

                // Position at selection bounds
                Canvas.SetLeft(textBox, bounds.Left);
                Canvas.SetTop(textBox, bounds.Top);
                Canvas.SetZIndex(textBox, 1000); // Above other elements

                // Add to canvas
                MainInteractiveBoard.Children.Add(textBox);

                // Register with SelectionManager
                RegisterNewObjectWithSelectionManager(textBox);

                // Record undo action
                RecordAddAction(textBox, "Recognized Text");

                // Replace strokes if requested
                if (replaceStrokes && _selectionManager != null)
                {
                    var selectedObjects = _selectionManager.GetSelectedObjects();
                    if (selectedObjects != null && selectedObjects.Count > 0)
                    {
                        foreach (var obj in selectedObjects.ToList())
                        {
                            // Only remove strokes (Polyline), keep other objects
                            if (obj.Type == ObjectType.Stroke && obj.Element is Polyline)
                            {
                                MainInteractiveBoard.Children.Remove(obj.Element);
                                _selectionManager.RemoveObject(obj);
                                System.Diagnostics.Debug.WriteLine($"🗑️ Removed stroke: {obj.Element}");
                            }
                        }
                    }
                }

                // Deselect all
                _selectionManager?.DeselectAll();

                System.Diagnostics.Debug.WriteLine($"✅ Inserted TextBox: \"{text}\" at ({bounds.Left:F0}, {bounds.Top:F0})");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Failed to insert text: {ex.Message}");
                throw;
            }
        }

        private void OnToolbarLockClicked(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null)
            {
                var obj = _selectionManager.SelectedObject;
                var oldLockState = obj.IsLocked;
                
                _selectionManager.ToggleLockSelectedObject();
                
                var newLockState = obj.IsLocked;
                _contextToolbar?.UpdateLockIcon(newLockState);
                System.Diagnostics.Debug.WriteLine($"🔒 Lock toggled: {newLockState}");
                
                // Add to undo stack
                RecordModifyAction(obj.Element, "IsLocked", oldLockState, newLockState, 
                    newLockState ? "Lock object" : "Unlock object");
                
                // Visual feedback
                AnimateLockToggle(obj.Element, newLockState);
            }
        }

        private void OnToolbarBringToFrontClicked(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null)
            {
                var obj = _selectionManager.SelectedObject;
                var oldZIndex = obj.ZIndex;
                
                _selectionManager.BringToFront(obj);
                
                var newZIndex = obj.ZIndex;
                System.Diagnostics.Debug.WriteLine("â¬†ï¸ Brought to front");
                
                // Add to undo stack
                RecordModifyAction(obj.Element, "ZIndex", oldZIndex, newZIndex, "Bring to front");
                
                // Visual feedback
                AnimatePop(obj.Element);
            }
        }

        private void OnToolbarSendToBackClicked(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null)
            {
                var obj = _selectionManager.SelectedObject;
                var oldZIndex = obj.ZIndex;
                
                _selectionManager.SendToBack(obj);
                
                var newZIndex = obj.ZIndex;
                System.Diagnostics.Debug.WriteLine("â¬‡ï¸ Sent to back");
                
                // Add to undo stack
                RecordModifyAction(obj.Element, "ZIndex", oldZIndex, newZIndex, "Send to back");
                
                // Visual feedback
                AnimateFadeOut(obj.Element, 0.3, 0.5);
            }
        }

        private void OnToolbarRotate90Clicked(object? sender, EventArgs e)
        {
            // ✅ FIX: Luôn dùng _selectionBox.AttachedObject - nguồn tin cậy duy nhất
            // cho cả single-selection và multi-selection (groupContainer)
            var targetObj = _selectionBox?.AttachedObject;
            if (targetObj == null || _transformService == null) return;

            System.Diagnostics.Debug.WriteLine($"🔄 Rotate90: IsGroup={targetObj.IsGroup}, Members={targetObj.GroupMembers?.Count ?? 0}");

            var initialStates = CaptureTargetTransformStates(targetObj);
            _transformService.RotateInPlace(targetObj, 90);

            // Cập nhật SelectionBox và Toolbar vị trí mới
            if (_selectionBox != null) _selectionBox.AttachTo(targetObj);
            RefreshSelectableObjects();

            if (_contextToolbar != null)
            {
                var pos = CalculateOptimalToolbarPosition(targetObj.Bounds);
                _contextToolbar.ShowAt(pos, targetObj);
            }

            var finalStates = CaptureTargetTransformStates(targetObj);
            RecordTransformAction(initialStates, finalStates, "Rotate 90°");
            System.Diagnostics.Debug.WriteLine($"🔄 Rotated 90° in-place applied & recorded Undo");
        }

        private void OnToolbarFlipHorizontalClicked(object? sender, EventArgs e)
        {
            // ✅ FIX: Luôn dùng _selectionBox.AttachedObject - nguồn tin cậy duy nhất
            var targetObj = _selectionBox?.AttachedObject;
            if (targetObj == null || _transformService == null) return;

            System.Diagnostics.Debug.WriteLine($"↔️ FlipH: IsGroup={targetObj.IsGroup}, Members={targetObj.GroupMembers?.Count ?? 0}");

            var initialStates = CaptureTargetTransformStates(targetObj);
            _transformService.FlipHorizontal(targetObj);

            if (_selectionBox != null) _selectionBox.AttachTo(targetObj);
            RefreshSelectableObjects();

            if (_contextToolbar != null)
            {
                var pos = CalculateOptimalToolbarPosition(targetObj.Bounds);
                _contextToolbar.ShowAt(pos, targetObj);
            }

            var finalStates = CaptureTargetTransformStates(targetObj);
            RecordTransformAction(initialStates, finalStates, "Flip Horizontal");
            System.Diagnostics.Debug.WriteLine("↔️ Flip Horizontal in-place applied & recorded Undo");
        }

        private void OnToolbarFlipVerticalClicked(object? sender, EventArgs e)
        {
            // ✅ FIX: Luôn dùng _selectionBox.AttachedObject - nguồn tin cậy duy nhất
            var targetObj = _selectionBox?.AttachedObject;
            if (targetObj == null || _transformService == null) return;

            System.Diagnostics.Debug.WriteLine($"↕️ FlipV: IsGroup={targetObj.IsGroup}, Members={targetObj.GroupMembers?.Count ?? 0}");

            var initialStates = CaptureTargetTransformStates(targetObj);
            _transformService.FlipVertical(targetObj);

            if (_selectionBox != null) _selectionBox.AttachTo(targetObj);
            RefreshSelectableObjects();

            if (_contextToolbar != null)
            {
                var pos = CalculateOptimalToolbarPosition(targetObj.Bounds);
                _contextToolbar.ShowAt(pos, targetObj);
            }

            var finalStates = CaptureTargetTransformStates(targetObj);
            RecordTransformAction(initialStates, finalStates, "Flip Vertical");
            System.Diagnostics.Debug.WriteLine("↕️ Flip Vertical in-place applied & recorded Undo");
        }


        private void OnToolbarThicknessClicked(object? sender, EventArgs e)
        {
            if (_contextToolbar != null && _selectionManager?.SelectedObject != null)
            {
                var pickerPosition = new Point(
                    Canvas.GetLeft(_contextToolbar) + 280, // Position next to thickness button
                    Canvas.GetTop(_contextToolbar) - 150    // Above toolbar
                );
                
                // Set current thickness before showing
                if (_thicknessPicker != null)
                {
                    _thicknessPicker.SelectedThickness = _selectionManager.SelectedObject.StrokeThickness;
                    _thicknessPicker.ShowAt(pickerPosition);
                }
                
                // Hide other pickers
                _colorPicker?.Hide();
                _moreMenu?.Hide();
                
                System.Diagnostics.Debug.WriteLine($"📏 Thickness picker opened with value: {_selectionManager.SelectedObject.StrokeThickness}px");
            }
        }

        private void OnToolbarColorClicked(object? sender, EventArgs e)
        {
            if (_contextToolbar != null && _selectionManager?.SelectedObject != null)
            {
                var pickerPosition = new Point(
                    Canvas.GetLeft(_contextToolbar) + 330, // Position next to color button
                    Canvas.GetTop(_contextToolbar) - 180    // Above toolbar
                );
                
                // Show color picker (current color already shown via toolbar preview)
                _colorPicker?.ShowAt(pickerPosition);
                
                // Hide other pickers
                _thicknessPicker?.Hide();
                _moreMenu?.Hide();
                
                System.Diagnostics.Debug.WriteLine($"🎨 Color picker opened with color: {_selectionManager.SelectedObject.StrokeColor}");
            }
        }

        private void OnToolbarDeleteClicked(object? sender, EventArgs e)
        {
            var selectedList = _selectionManager?.SelectedObjects.ToList();
            if (selectedList != null && selectedList.Count > 0)
            {
                foreach (var obj in selectedList)
                {
                    if (obj.Element != null)
                    {
                        RecordRemoveAction(obj.Element, $"Delete {obj.Type}");
                    }
                }

                // Immediately detach selection box & hide toolbar UI
                _selectionBox?.Detach();
                _contextToolbar?.Hide();
                _moreMenu?.Hide();
                _thicknessPicker?.Hide();
                _colorPicker?.Hide();

                _selectionManager?.DeleteSelectedObjects();
                System.Diagnostics.Debug.WriteLine($"🗑️ Deleted {selectedList.Count} selected object(s)");
            }
        }

        private void OnToolbarSpotlightClicked(object? sender, EventArgs e)
        {
            try
            {
                System.Diagnostics.Debug.WriteLine("OnToolbarSpotlightClicked called");
                
                // Toggle Spotlight Mode
                if (_currentSpotlightOverlay != null)
                {
                    // Turn off if already on
                    MainInteractiveBoard.Children.Remove(_currentSpotlightOverlay);
                    _currentSpotlightOverlay = null;
                    System.Diagnostics.Debug.WriteLine("Spotlight Mode deactivated");
                    return;
                }

                // Turn on Spotlight Mode for selected object
                var selectedObj = _selectionManager?.SelectedObject;
                if (selectedObj == null)
                {
                    var list = _selectionManager?.GetSelectedObjects();
                    if (list != null && list.Count > 0)
                    {
                        selectedObj = list[0];
                    }
                }

                if (selectedObj == null)
                {
                    MessageBox.Show("Vui lòng chọn một đối tượng để bật chế độ tiêu điểm (Spotlight).", "Thông báo", MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Get selected object's bounds
                Rect bounds = selectedObj.Bounds;
                
                // Create the geometry for the overlay: whole canvas minus the selected bounds
                var outerGeometry = new System.Windows.Media.RectangleGeometry(new Rect(0, 0, MainInteractiveBoard.ActualWidth, MainInteractiveBoard.ActualHeight));
                var innerGeometry = new System.Windows.Media.RectangleGeometry(bounds, 8, 8);
                var combined = new System.Windows.Media.CombinedGeometry(System.Windows.Media.GeometryCombineMode.Exclude, outerGeometry, innerGeometry);
                
                var path = new System.Windows.Shapes.Path
                {
                    Fill = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromArgb(180, 0, 0, 0)), // 70% opacity black
                    Data = combined,
                    IsHitTestVisible = true
                };
                
                path.MouseLeftButtonDown += (s, args) =>
                {
                    MainInteractiveBoard.Children.Remove(path);
                    if (_currentSpotlightOverlay == path)
                    {
                        _currentSpotlightOverlay = null;
                    }
                    args.Handled = true;
                };

                MainInteractiveBoard.Children.Add(path);
                _currentSpotlightOverlay = path;
                
                System.Diagnostics.Debug.WriteLine("Spotlight Mode activated");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[Spotlight Error] {ex.Message}");
            }
        }

        /// <summary>
        /// ✅ BUG #12 FIX: Dùng kích thước cố định thay vì Measure() trên control Collapsed.
        /// MoreMenu.xaml: d:DesignWidth="280", ScrollViewer MaxHeight=500 + Border Padding 8×2 = 520.
        /// </summary>
        private void OnToolbarMoreClicked(object? sender, EventArgs e)
        {
            if (_contextToolbar != null && _moreMenu != null)
            {
                // ✅ BUG #12 FIX: Kích thước cố định — Measure() trên Collapsed control trả về (0,0)
                const double menuWidth = 280;
                const double menuHeight = 520;

                double boardWidth = MainInteractiveBoard.ActualWidth > 0 ? MainInteractiveBoard.ActualWidth : 1920;
                double boardHeight = MainInteractiveBoard.ActualHeight > 0 ? MainInteractiveBoard.ActualHeight : 1080;

                double toolbarLeft = Canvas.GetLeft(_contextToolbar);
                double toolbarTop = Canvas.GetTop(_contextToolbar);
                if (double.IsNaN(toolbarLeft)) toolbarLeft = 100;
                if (double.IsNaN(toolbarTop)) toolbarTop = 100;

                double toolbarHeight = _contextToolbar.ActualHeight > 0 ? _contextToolbar.ActualHeight : 45;

                // Calculate smart X position aligned with ContextToolbar
                double posX = Math.Max(10, Math.Min(toolbarLeft + 50, boardWidth - menuWidth - 10));

                // Calculate smart Y position (Above or Below toolbar based on screen space)
                double posY;
                if (toolbarTop + toolbarHeight + menuHeight > boardHeight - 20)
                {
                    // Position ABOVE context toolbar if toolbar is in lower screen area
                    posY = Math.Max(10, toolbarTop - menuHeight - 10);
                }
                else
                {
                    // Position BELOW context toolbar
                    posY = toolbarTop + toolbarHeight + 5;
                }

                _moreMenu.ShowAt(new Point(posX, posY));

                // Hide pickers
                _thicknessPicker?.Hide();
                _colorPicker?.Hide();

                System.Diagnostics.Debug.WriteLine($"📋 MoreMenu shown at ({posX:F0}, {posY:F0}), board: {boardWidth:F0}×{boardHeight:F0}");
            }
        }

        // ThicknessPicker handler
        private void OnThicknessChanged(object? sender, double thickness)
        {
            if (_selectionManager == null)
                return;

            // Get all selected objects (support multi-selection)
            var selectedObjects = _selectionManager.GetSelectedObjects();
            
            if (selectedObjects.Count == 0)
                return;

            System.Diagnostics.Debug.WriteLine($"📏 Applying thickness to {selectedObjects.Count} object(s)");

            foreach (var obj in selectedObjects)
            {
                var oldThickness = obj.StrokeThickness;
                
                // Update model
                obj.StrokeThickness = thickness;
                
                // Update actual UIElement
                if (obj.Element is Polyline polyline)
                {
                    polyline.StrokeThickness = thickness;
                    System.Diagnostics.Debug.WriteLine($"   ✓ Polyline thickness changed: {oldThickness:F0}px → {thickness:F0}px");
                }
                else if (obj.Element is System.Windows.Shapes.Shape shape)
                {
                    shape.StrokeThickness = thickness;
                    System.Diagnostics.Debug.WriteLine($"   ✓ Shape thickness changed: {oldThickness:F0}px → {thickness:F0}px");
                }
                else if (obj.Element is Border border)
                {
                    border.BorderThickness = new Thickness(thickness);
                    System.Diagnostics.Debug.WriteLine($"   ✓ Border thickness changed: {oldThickness:F0}px → {thickness:F0}px");
                }
                
                // Record for undo/redo
                RecordModifyAction(obj.Element, oldThickness, thickness, $"Change Thickness {oldThickness:F0}→{thickness:F0}px");
            }
            
            System.Diagnostics.Debug.WriteLine($"✅ Thickness changed for {selectedObjects.Count} object(s): → {thickness:F0}px");
        }

        // ColorPicker handler
        private void OnColorSelected(object? sender, Color color)
        {
            if (_selectionManager == null)
                return;

            // Get all selected objects (support multi-selection)
            var selectedObjects = _selectionManager.GetSelectedObjects();
            
            if (selectedObjects.Count == 0)
                return;

            System.Diagnostics.Debug.WriteLine($"🎨 Applying color to {selectedObjects.Count} object(s)");

            foreach (var obj in selectedObjects)
            {
                var oldColor = obj.StrokeColor;
                
                // Update model
                obj.StrokeColor = color;
                
                // Update actual UIElement color
                if (obj.Element is Polyline polyline)
                {
                    polyline.Stroke = new SolidColorBrush(color);
                    System.Diagnostics.Debug.WriteLine($"   ✓ Polyline color changed: {oldColor} → {color}");
                }
                else if (obj.Element is System.Windows.Shapes.Shape shape)
                {
                    shape.Stroke = new SolidColorBrush(color);
                    System.Diagnostics.Debug.WriteLine($"   ✓ Shape color changed: {oldColor} → {color}");
                }
                else if (obj.Element is Border border)
                {
                    border.BorderBrush = new SolidColorBrush(color);
                    System.Diagnostics.Debug.WriteLine($"   ✓ Border color changed: {oldColor} → {color}");
                }
                
                // Record for undo/redo
                RecordModifyAction(obj.Element, oldColor, color, $"Change Color {oldColor} → {color}");
            }

            // Update toolbar preview
            _contextToolbar?.UpdateColorPreview(color);
            
            System.Diagnostics.Debug.WriteLine($"✅ Color changed for {selectedObjects.Count} object(s): → {color}");
        }

        // MoreMenu handlers (stub implementations - will be completed in Sprint 2-5)
        private void OnMoreMenuFlipHorizontal(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null && _transformService != null)
            {
                var obj = _selectionManager.SelectedObject;
                var initialStates = CaptureTargetTransformStates(obj);
                
                // Apply flip
                _transformService.FlipHorizontal(obj);
                _selectionBox?.UpdatePosition();
                
                var finalStates = CaptureTargetTransformStates(obj);
                RecordTransformAction(initialStates, finalStates, "Flip Horizontal");
                
                // Visual feedback
                AnimateFlip(obj.Element, true);
                
                System.Diagnostics.Debug.WriteLine("↔️ Flipped horizontally & recorded Undo");
            }
        }

        private void OnMoreMenuFlipVertical(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null && _transformService != null)
            {
                var obj = _selectionManager.SelectedObject;
                var initialStates = CaptureTargetTransformStates(obj);
                
                // Apply flip
                _transformService.FlipVertical(obj);
                _selectionBox?.UpdatePosition();
                
                var finalStates = CaptureTargetTransformStates(obj);
                RecordTransformAction(initialStates, finalStates, "Flip Vertical");
                
                // Visual feedback
                AnimateFlip(obj.Element, false);
                
                System.Diagnostics.Debug.WriteLine("↕️ Flipped vertically & recorded Undo");
            }
        }

        private void OnMoreMenuRotate180(object? sender, EventArgs e)
        {
            var selectedObjects = _selectionManager?.GetSelectedObjects();
            if (selectedObjects == null || selectedObjects.Count == 0) return;

            var targetObj = selectedObjects.Count == 1 ? selectedObjects[0] : _selectionBox?.AttachedObject;
            if (targetObj != null && _transformService != null)
            {
                var initialStates = CaptureTargetTransformStates(targetObj);
                _transformService.RotateInPlace(targetObj, 180);
                
                if (_selectionBox != null) _selectionBox.AttachTo(targetObj);
                RefreshSelectableObjects();

                if (_contextToolbar != null)
                {
                    var pos = CalculateOptimalToolbarPosition(targetObj.Bounds);
                    _contextToolbar.ShowAt(pos, targetObj);
                }

                var finalStates = CaptureTargetTransformStates(targetObj);
                RecordTransformAction(initialStates, finalStates, "Rotate 180°");
                System.Diagnostics.Debug.WriteLine($"🔄 Rotated 180° in-place & recorded Undo");
            }
        }

        private void OnMoreMenuRotateLeft90(object? sender, EventArgs e)
        {
            var selectedObjects = _selectionManager?.GetSelectedObjects();
            if (selectedObjects == null || selectedObjects.Count == 0) return;

            var targetObj = selectedObjects.Count == 1 ? selectedObjects[0] : _selectionBox?.AttachedObject;
            if (targetObj != null && _transformService != null)
            {
                var initialStates = CaptureTargetTransformStates(targetObj);
                _transformService.RotateInPlace(targetObj, -90);
                
                if (_selectionBox != null) _selectionBox.AttachTo(targetObj);
                RefreshSelectableObjects();

                if (_contextToolbar != null)
                {
                    var pos = CalculateOptimalToolbarPosition(targetObj.Bounds);
                    _contextToolbar.ShowAt(pos, targetObj);
                }

                var finalStates = CaptureTargetTransformStates(targetObj);
                RecordTransformAction(initialStates, finalStates, "Rotate Left 90°");
                System.Diagnostics.Debug.WriteLine($"↩️ Rotated Left 90° in-place & recorded Undo");
            }
        }

        private void OnMoreMenuRotateCustom(object? sender, EventArgs e)
        {
            if (_selectionManager?.SelectedObject != null && _transformService != null)
            {
                var obj = _selectionManager.SelectedObject;
                var oldAngle = obj.RotationAngle;
                
                // Simple input dialog using TextBox in Window
                var inputWindow = new Window
                {
                    Title = "Custom Rotation",
                    Width = 350,
                    Height = 180,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize,
                    Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };
                
                var labelCurrent = new TextBlock
                {
                    Text = $"Current angle: {oldAngle:F0}°",
                    Foreground = Brushes.White,
                    FontSize = 14,
                    Margin = new Thickness(0, 0, 0, 10)
                };
                
                var labelPrompt = new TextBlock
                {
                    Text = "Enter new rotation angle (0-360):",
                    Foreground = Brushes.White,
                    FontSize = 14,
                    Margin = new Thickness(0, 0, 0, 5)
                };
                
                var textBox = new TextBox
                {
                    Text = oldAngle.ToString("F0"),
                    FontSize = 16,
                    Padding = new Thickness(5),
                    Margin = new Thickness(0, 0, 0, 15)
                };
                textBox.SelectAll();
                textBox.Focus();
                
                var buttonPanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    HorizontalAlignment = HorizontalAlignment.Right
                };
                
                var btnOK = new Button
                {
                    Content = "OK",
                    Width = 80,
                    Height = 30,
                    Margin = new Thickness(0, 0, 10, 0),
                    IsDefault = true
                };
                
                var btnCancel = new Button
                {
                    Content = "Cancel",
                    Width = 80,
                    Height = 30,
                    IsCancel = true
                };
                
                bool dialogResult = false;
                btnOK.Click += (s, args) => { dialogResult = true; inputWindow.Close(); };
                btnCancel.Click += (s, args) => { dialogResult = false; inputWindow.Close(); };
                
                buttonPanel.Children.Add(btnOK);
                buttonPanel.Children.Add(btnCancel);
                
                stackPanel.Children.Add(labelCurrent);
                stackPanel.Children.Add(labelPrompt);
                stackPanel.Children.Add(textBox);
                stackPanel.Children.Add(buttonPanel);
                
                inputWindow.Content = stackPanel;
                inputWindow.ShowDialog();
                
                if (dialogResult && double.TryParse(textBox.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double newAngle))
                {
                    // Clamp to 0-360
                    newAngle = ((newAngle % 360) + 360) % 360;
                    
                    var initialStates = CaptureTargetTransformStates(obj);

                    // Apply rotation
                    double delta = newAngle - oldAngle;
                    _transformService.RotateInPlace(obj, delta);
                    if (_selectionBox != null) _selectionBox.AttachTo(obj);
                    RefreshSelectableObjects();

                    if (_contextToolbar != null)
                    {
                        var pos = CalculateOptimalToolbarPosition(obj.Bounds);
                        _contextToolbar.ShowAt(pos, obj);
                    }
                    
                    var finalStates = CaptureTargetTransformStates(obj);
                    RecordTransformAction(initialStates, finalStates, $"Rotate Custom {newAngle:F0}°");
                    
                    System.Diagnostics.Debug.WriteLine($"🔄 Rotated custom: {oldAngle:F0}° → {newAngle:F0}° & recorded Undo");
                }
                
                _moreMenu?.Hide();
            }
        }

        // Visual feedback animations
        /// <summary>
        /// Fade in animation for new objects (Copy)
        /// </summary>
        private void AnimateFadeIn(UIElement? element)
        {
            if (element == null)
            {
                System.Diagnostics.Debug.WriteLine("âš ï¸ AnimateFadeIn: element is null");
                return;
            }
            
            element.Opacity = 0;
            var animation = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = 0,
                To = 1,
                Duration = TimeSpan.FromMilliseconds(300),
                EasingFunction = new System.Windows.Media.Animation.QuadraticEase { EasingMode = System.Windows.Media.Animation.EasingMode.EaseOut }
            };
            element.BeginAnimation(UIElement.OpacityProperty, animation);
        }

        /// <summary>
        /// Fade out animation with optional callback (Delete, SendToBack)
        /// </summary>
        private void AnimateFadeOut(UIElement? element, double fromOpacity, double toOpacity, Action? onComplete = null)
        {
            if (element == null)
            {
                System.Diagnostics.Debug.WriteLine("⚠️ AnimateFadeOut: element is null");
                onComplete?.Invoke();
                return;
            }
            
            var animation = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = fromOpacity,
                To = toOpacity,
                Duration = TimeSpan.FromMilliseconds(250),
                EasingFunction = new System.Windows.Media.Animation.QuadraticEase { EasingMode = System.Windows.Media.Animation.EasingMode.EaseIn }
            };
            
            if (onComplete != null)
            {
                animation.Completed += (s, e) => onComplete();
            }
            
            element.BeginAnimation(UIElement.OpacityProperty, animation);
        }

        /// <summary>
        /// Pop animation for layer changes (BringToFront)
        /// </summary>
        private void AnimatePop(UIElement element)
        {
            var scaleTransform = element.RenderTransform as System.Windows.Media.ScaleTransform;
            if (scaleTransform == null)
            {
                scaleTransform = new System.Windows.Media.ScaleTransform(1, 1);
                element.RenderTransform = scaleTransform;
                element.RenderTransformOrigin = new Point(0.5, 0.5);
            }

            var scaleUpX = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = 1,
                To = 1.1,
                Duration = TimeSpan.FromMilliseconds(150),
                AutoReverse = true,
                EasingFunction = new System.Windows.Media.Animation.BackEase { Amplitude = 0.3, EasingMode = System.Windows.Media.Animation.EasingMode.EaseOut }
            };
            
            var scaleUpY = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = 1,
                To = 1.1,
                Duration = TimeSpan.FromMilliseconds(150),
                AutoReverse = true,
                EasingFunction = new System.Windows.Media.Animation.BackEase { Amplitude = 0.3, EasingMode = System.Windows.Media.Animation.EasingMode.EaseOut }
            };

            scaleTransform.BeginAnimation(System.Windows.Media.ScaleTransform.ScaleXProperty, scaleUpX);
            scaleTransform.BeginAnimation(System.Windows.Media.ScaleTransform.ScaleYProperty, scaleUpY);
        }

        /// <summary>
        /// Rotation animation (Rotate90)
        /// </summary>
        private void AnimateRotation(UIElement element, double fromAngle, double toAngle)
        {
            var rotateTransform = element.RenderTransform as System.Windows.Media.RotateTransform;
            if (rotateTransform == null)
            {
                rotateTransform = new System.Windows.Media.RotateTransform(fromAngle);
                element.RenderTransform = rotateTransform;
                element.RenderTransformOrigin = new Point(0.5, 0.5);
            }

            var animation = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = fromAngle,
                To = toAngle,
                Duration = TimeSpan.FromMilliseconds(300),
                EasingFunction = new System.Windows.Media.Animation.CubicEase { EasingMode = System.Windows.Media.Animation.EasingMode.EaseInOut }
            };

            rotateTransform.BeginAnimation(System.Windows.Media.RotateTransform.AngleProperty, animation);
        }

        /// <summary>
        /// Lock toggle animation (pulse effect)
        /// </summary>
        private void AnimateLockToggle(UIElement element, bool isLocked)
        {
            var animation = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = 1,
                To = 0.7,
                Duration = TimeSpan.FromMilliseconds(200),
                AutoReverse = true,
                RepeatBehavior = new System.Windows.Media.Animation.RepeatBehavior(2)
            };

            element.BeginAnimation(UIElement.OpacityProperty, animation);
        }

        /// <summary>
        /// Flip animation (FlipHorizontal/FlipVertical)
        /// </summary>
        private void AnimateFlip(UIElement? element, bool isHorizontal)
        {
            if (element == null)
                return;

            var scaleTransform = element.RenderTransform as System.Windows.Media.ScaleTransform;
            if (scaleTransform == null)
            {
                scaleTransform = new System.Windows.Media.ScaleTransform(1, 1);
                element.RenderTransform = scaleTransform;
                element.RenderTransformOrigin = new Point(0.5, 0.5);
            }

            var property = isHorizontal
                ? System.Windows.Media.ScaleTransform.ScaleXProperty
                : System.Windows.Media.ScaleTransform.ScaleYProperty;

            var currentScale = isHorizontal ? scaleTransform.ScaleX : scaleTransform.ScaleY;

            var animation = new System.Windows.Media.Animation.DoubleAnimation
            {
                From = currentScale,
                To = 0.1,
                Duration = TimeSpan.FromMilliseconds(150),
                AutoReverse = true,
                EasingFunction = new System.Windows.Media.Animation.QuadraticEase
                {
                    EasingMode = System.Windows.Media.Animation.EasingMode.EaseInOut
                }
            };

            scaleTransform.BeginAnimation(property, animation);
        }

        /// <summary>
        /// Dọn dẹp hình chữ nhật xem trước vùng chọn (blue dashed rectangle) triệt để khỏi Canvas
        /// </summary>
        private void ClearRectangleSelectionPreview()
        {
            if (_rectangleSelectionPreview != null)
            {
                if (MainInteractiveBoard?.Children.Contains(_rectangleSelectionPreview) == true)
                {
                    MainInteractiveBoard.Children.Remove(_rectangleSelectionPreview);
                }
                _rectangleSelectionPreview = null;
            }
            _isRectangleSelecting = false;
        }

        /// <summary>
        /// Gom nhóm các nét vẽ tự do nằm gần hoặc đè lên nhau thành từng cụm ký tự (ví dụ: 2 nét của số 4, chữ T, A, E, +)
        /// Sắp xếp nghiêm ngặt các cụm từ trái sang phải theo trục X
        /// </summary>
        private List<List<SelectableObject>> ClusterDrawingObjects(List<SelectableObject> drawingObjs)
        {
            var clusters = new List<List<SelectableObject>>();
            if (drawingObjs == null || drawingObjs.Count == 0) return clusters;

            var sorted = drawingObjs.OrderBy(o => o.Bounds.X).ToList();

            foreach (var obj in sorted)
            {
                bool addedToCluster = false;

                foreach (var cluster in clusters)
                {
                    double clusterLeft = cluster.Min(o => o.Bounds.Left);
                    double clusterRight = cluster.Max(o => o.Bounds.Right);
                    double clusterTop = cluster.Min(o => o.Bounds.Top);
                    double clusterBottom = cluster.Max(o => o.Bounds.Bottom);
                    Rect clusterRect = new Rect(clusterLeft, clusterTop, Math.Max(1, clusterRight - clusterLeft), Math.Max(1, clusterBottom - clusterTop));

                    // Ngưỡng 12px theo chiều ngang để gom các nét cùng 1 ký tự mà không làm dính chữ bên cạnh
                    Rect expandedCluster = new Rect(clusterRect.X - 12, clusterRect.Y - 20, clusterRect.Width + 24, clusterRect.Height + 40);

                    if (expandedCluster.IntersectsWith(obj.Bounds))
                    {
                        cluster.Add(obj);
                        addedToCluster = true;
                        break;
                    }
                }

                if (!addedToCluster)
                {
                    clusters.Add(new List<SelectableObject> { obj });
                }
            }

            // Sắp xếp các cụm từ trái qua phải theo chiều ngang
            return clusters.OrderBy(c => c.Min(o => o.Bounds.X)).ToList();
        }

        #endregion
    }
}