using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.AI.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 18927-20685
// #region Module 2.3 Text Ops + Module 2.5 OCR + Sprint 4 AI
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Module 2.3: Text Operations

        /// <summary>
        /// Convert selected text to UPPERCASE
        /// For drawing objects: recognize handwriting first, then convert
        /// </summary>
        private async void OnMoreMenuUpperCase(object? sender, EventArgs e)
        {
            var selectedObjs = _selectionManager?.SelectedObjects.ToList();
            if (selectedObjs == null || selectedObjs.Count == 0)
            {
                System.Diagnostics.Debug.WriteLine("⚠️ UpperCase: No object selected");
                return;
            }

            _moreMenu?.Hide();
            ClearRectangleSelectionPreview();

            var drawingObjs = selectedObjs.Where(o => o.Element is Polyline || o.Element is System.Windows.Shapes.Path || o.Element is System.Windows.Shapes.Shape).ToList();
            var textObjs = selectedObjs.Except(drawingObjs).ToList();

            // 1. Xử lý các đối tượng văn bản có sẵn
            foreach (var obj in textObjs)
            {
                if (obj.Element is System.Windows.Controls.TextBlock textBlock)
                {
                    string oldText = textBlock.Text;
                    string newText = oldText?.ToUpper() ?? "";
                    if (newText != oldText)
                    {
                        textBlock.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to UPPERCASE");
                    }
                }
                else if (obj.Element is System.Windows.Controls.TextBox textBox)
                {
                    string oldText = textBox.Text;
                    string newText = oldText?.ToUpper() ?? "";
                    if (newText != oldText)
                    {
                        textBox.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to UPPERCASE");
                    }
                }
                else if (obj.Element is System.Windows.Controls.Border border)
                {
                    var childTextBlock = FindVisualChild<System.Windows.Controls.TextBlock>(border);
                    if (childTextBlock != null)
                    {
                        string oldText = childTextBlock.Text;
                        string newText = oldText?.ToUpper() ?? "";
                        if (newText != oldText)
                        {
                            childTextBlock.Text = newText;
                            obj.TextContent = newText;
                            RecordModifyAction(obj.Element, oldText, newText, "Convert to UPPERCASE");
                        }
                    }
                }
            }

            // 2. Nhận dạng nguyên chuỗi các nét vẽ được chọn cùng lúc (chỉ mở 1 Dialog duy nhất cho toàn bộ chuỗi)
            if (drawingObjs.Count > 0)
            {
                await RecognizeAndReplaceWithText(drawingObjs, TextCaseMode.UpperCase);
            }
        }

        /// <summary>
        /// Convert selected text to lowercase
        /// For drawing objects: recognize handwriting first, then convert
        /// </summary>
        private async void OnMoreMenuLowerCase(object? sender, EventArgs e)
        {
            var selectedObjs = _selectionManager?.SelectedObjects.ToList();
            if (selectedObjs == null || selectedObjs.Count == 0)
            {
                System.Diagnostics.Debug.WriteLine("⚠️ LowerCase: No object selected");
                return;
            }

            _moreMenu?.Hide();
            ClearRectangleSelectionPreview();

            var drawingObjs = selectedObjs.Where(o => o.Element is Polyline || o.Element is System.Windows.Shapes.Path || o.Element is System.Windows.Shapes.Shape).ToList();
            var textObjs = selectedObjs.Except(drawingObjs).ToList();

            foreach (var obj in textObjs)
            {
                if (obj.Element is System.Windows.Controls.TextBlock textBlock)
                {
                    string oldText = textBlock.Text;
                    string newText = oldText?.ToLower() ?? "";
                    if (newText != oldText)
                    {
                        textBlock.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to lowercase");
                    }
                }
                else if (obj.Element is System.Windows.Controls.TextBox textBox)
                {
                    string oldText = textBox.Text;
                    string newText = oldText?.ToLower() ?? "";
                    if (newText != oldText)
                    {
                        textBox.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to lowercase");
                    }
                }
                else if (obj.Element is System.Windows.Controls.Border border)
                {
                    var childTextBlock = FindVisualChild<System.Windows.Controls.TextBlock>(border);
                    if (childTextBlock != null)
                    {
                        string oldText = childTextBlock.Text;
                        string newText = oldText?.ToLower() ?? "";
                        if (newText != oldText)
                        {
                            childTextBlock.Text = newText;
                            obj.TextContent = newText;
                            RecordModifyAction(obj.Element, oldText, newText, "Convert to lowercase");
                        }
                    }
                }
            }

            if (drawingObjs.Count > 0)
            {
                await RecognizeAndReplaceWithText(drawingObjs, TextCaseMode.LowerCase);
            }
        }

        /// <summary>
        /// Convert selected text to Title Case
        /// For drawing objects: recognize handwriting first, then convert
        /// </summary>
        private async void OnMoreMenuTitleCase(object? sender, EventArgs e)
        {
            var selectedObjs = _selectionManager?.SelectedObjects.ToList();
            if (selectedObjs == null || selectedObjs.Count == 0)
            {
                System.Diagnostics.Debug.WriteLine("⚠️ TitleCase: No object selected");
                return;
            }

            _moreMenu?.Hide();
            ClearRectangleSelectionPreview();

            var drawingObjs = selectedObjs.Where(o => o.Element is Polyline || o.Element is System.Windows.Shapes.Path || o.Element is System.Windows.Shapes.Shape).ToList();
            var textObjs = selectedObjs.Except(drawingObjs).ToList();

            foreach (var obj in textObjs)
            {
                if (obj.Element is System.Windows.Controls.TextBlock textBlock)
                {
                    string oldText = textBlock.Text;
                    string newText = ToTitleCase(oldText) ?? "";
                    if (newText != oldText)
                    {
                        textBlock.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to Title Case");
                    }
                }
                else if (obj.Element is System.Windows.Controls.TextBox textBox)
                {
                    string oldText = textBox.Text;
                    string newText = ToTitleCase(oldText) ?? "";
                    if (newText != oldText)
                    {
                        textBox.Text = newText;
                        obj.TextContent = newText;
                        RecordModifyAction(obj.Element, oldText, newText, "Convert to Title Case");
                    }
                }
                else if (obj.Element is System.Windows.Controls.Border border)
                {
                    var childTextBlock = FindVisualChild<System.Windows.Controls.TextBlock>(border);
                    if (childTextBlock != null)
                    {
                        string oldText = childTextBlock.Text;
                        string newText = ToTitleCase(oldText) ?? "";
                        if (newText != oldText)
                        {
                            childTextBlock.Text = newText;
                            obj.TextContent = newText;
                            RecordModifyAction(obj.Element, oldText, newText, "Convert to Title Case");
                        }
                    }
                }
            }

            if (drawingObjs.Count > 0)
            {
                await RecognizeAndReplaceWithText(drawingObjs, TextCaseMode.TitleCase);
            }
        }

        /// <summary>Text case conversion mode</summary>
        private enum TextCaseMode { UpperCase, LowerCase, TitleCase }

        private async System.Threading.Tasks.Task RecognizeAndReplaceWithText(SelectableObject obj, TextCaseMode caseMode)
        {
            if (obj == null) return;
            await RecognizeAndReplaceWithText(new List<SelectableObject> { obj }, caseMode);
        }

        /// <summary>
        /// Làm sạch và tạo biến thể chuẩn hóa chữ số cho chuỗi nhận dạng OCR (ví dụ: "d 2345" -> "12345")
        /// </summary>
        private List<string> GenerateDigitSanitizedVariants(string raw)
        {
            var list = new List<string>();
            if (string.IsNullOrWhiteSpace(raw)) return list;

            string s = raw.Trim();
            list.Add(s);

            // 1. Sửa lỗi OCR hay đọc mỏ chéo của chữ số 1 thành chữ "d", "cl", "I", "l", "|" ở đầu chuỗi số
            if (System.Text.RegularExpressions.Regex.IsMatch(s, @"^(d|cl|I|l|\|)\s*\d+", System.Text.RegularExpressions.RegexOptions.IgnoreCase))
            {
                string fixedHead = System.Text.RegularExpressions.Regex.Replace(s, @"^(d|cl|I|l|\|)\s*", "1", System.Text.RegularExpressions.RegexOptions.IgnoreCase);
                string fixedHeadNoSpaces = fixedHead.Replace(" ", "");
                list.Add(fixedHeadNoSpaces);
                list.Add(fixedHead);
            }

            // 2. Tự động tạo biến thể bỏ khoảng trắng cho toàn chuỗi chữ số (ví dụ: "1 2 3 4 5" -> "12345")
            string noSpaces = s.Replace(" ", "");
            if (noSpaces != s)
            {
                list.Add(noSpaces);
            }

            return list;
        }

        /// <summary>
        /// Tổng hợp danh sách tất cả các ứng viên nhận dạng chuỗi chữ từ 3 tầng (Google Vision + Windows OCR + Geometric String Fallback)
        /// </summary>
        private async System.Threading.Tasks.Task<List<HandwritingRecognitionResult>> AggregateAllCandidates(List<SelectableObject> targetObjects, Rect bounds)
        {
            var candidateList = new List<HandwritingRecognitionResult>();
            var seenTexts = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            var (bitmap, imageBytes) = CaptureStrokesAsBlackOnWhite(targetObjects, bounds);

            // 1. Phân tích chuỗi hình học từng nét/cụm nét trước tiên (Geometric String Clustering) -> Trả về "12345" & "1 2 3 4 5" chuẩn xác ở Rank 0
            if (targetObjects != null && targetObjects.Count > 0)
            {
                var clusters = ClusterDrawingObjects(targetObjects);
                var geomCharsWithSpaces = new List<string>();
                var geomCharsNoSpaces = new List<string>();

                foreach (var cluster in clusters)
                {
                    var gRes = RecognizeStrokeGeometryFallback(cluster[0]);
                    if (gRes.Count > 0 && !string.IsNullOrWhiteSpace(gRes[0].Text))
                    {
                        geomCharsWithSpaces.Add(gRes[0].Text);
                        geomCharsNoSpaces.Add(gRes[0].Text);
                    }
                }

                if (geomCharsNoSpaces.Count > 0)
                {
                    string joinedNoSpaces = string.Join("", geomCharsNoSpaces);
                    string joinedWithSpaces = string.Join(" ", geomCharsWithSpaces);

                    if (seenTexts.Add(joinedNoSpaces))
                    {
                        candidateList.Add(new HandwritingRecognitionResult
                        {
                            Text = joinedNoSpaces,
                            Confidence = 0.98f,
                            Rank = candidateList.Count,
                            DetectedLanguage = "en"
                        });
                    }

                    if (joinedWithSpaces != joinedNoSpaces && seenTexts.Add(joinedWithSpaces))
                    {
                        candidateList.Add(new HandwritingRecognitionResult
                        {
                            Text = joinedWithSpaces,
                            Confidence = 0.95f,
                            Rank = candidateList.Count,
                            DetectedLanguage = "en"
                        });
                    }

                    // Thêm các chuỗi con phổ biến (ví dụ: "1234", "2345")
                    if (geomCharsNoSpaces.Count >= 4)
                    {
                        string sub1 = string.Join("", geomCharsNoSpaces.Take(geomCharsNoSpaces.Count - 1));
                        string sub2 = string.Join("", geomCharsNoSpaces.Skip(1));
                        if (seenTexts.Add(sub1))
                        {
                            candidateList.Add(new HandwritingRecognitionResult { Text = sub1, Confidence = 0.90f, Rank = candidateList.Count, DetectedLanguage = "en" });
                        }
                        if (seenTexts.Add(sub2))
                        {
                            candidateList.Add(new HandwritingRecognitionResult { Text = sub2, Confidence = 0.88f, Rank = candidateList.Count, DetectedLanguage = "en" });
                        }
                    }
                }
            }

            // 2. Google Cloud Vision API (Nhận diện nguyên chuỗi chữ/số)
            if (_handwritingService != null && _handwritingService.IsInitialized && imageBytes != null)
            {
                try
                {
                    var gResults = await _handwritingService.RecognizeHandwritingAsync(imageBytes, 5);
                    if (gResults != null)
                    {
                        foreach (var res in gResults)
                        {
                            if (!string.IsNullOrWhiteSpace(res.Text))
                            {
                                var variants = GenerateDigitSanitizedVariants(res.Text);
                                foreach (var v in variants)
                                {
                                    if (seenTexts.Add(v))
                                    {
                                        candidateList.Add(new HandwritingRecognitionResult
                                        {
                                            Text = v,
                                            Confidence = res.Confidence,
                                            Rank = candidateList.Count,
                                            DetectedLanguage = res.DetectedLanguage
                                        });
                                    }
                                }
                            }
                        }
                    }
                }
                catch (Exception gEx)
                {
                    System.Diagnostics.Debug.WriteLine($"⚠️ Google Vision API error: {gEx.Message}");
                }
            }

            // 3. Windows Offline OCR Engine (Nhận diện nguyên chuỗi chữ/số)
            if (bitmap != null)
            {
                try
                {
                    if (_windowsOcrService == null)
                    {
                        _windowsOcrService = new WindowsOCRService();
                    }
                    var ocrRes = await _windowsOcrService.RecognizeTextAsync(bitmap);
                    if (ocrRes != null && ocrRes.IsSuccess && !string.IsNullOrWhiteSpace(ocrRes.Text))
                    {
                        var variants = GenerateDigitSanitizedVariants(ocrRes.Text);
                        foreach (var v in variants)
                        {
                            if (seenTexts.Add(v))
                            {
                                candidateList.Add(new HandwritingRecognitionResult
                                {
                                    Text = v,
                                    Confidence = 0.85f,
                                    Rank = candidateList.Count,
                                    DetectedLanguage = "en"
                                });
                            }
                        }
                    }
                }
                catch (Exception wEx)
                {
                    System.Diagnostics.Debug.WriteLine($"⚠️ Windows OCR error: {wEx.Message}");
                }
            }

            return candidateList;
        }

        private async System.Threading.Tasks.Task RecognizeAndReplaceWithText(List<SelectableObject> targetObjects, TextCaseMode caseMode)
        {
            if (targetObjects == null || targetObjects.Count == 0) return;

            Rect bounds = targetObjects.Count == 1
                ? targetObjects[0].Bounds
                : (_selectionManager?.GetMultiSelectionBounds() ?? targetObjects[0].Bounds);

            if (bounds.IsEmpty || bounds.Width <= 0 || bounds.Height <= 0) return;

            // 1. Tổng hợp danh sách ứng viên nhận diện tiềm năng từ 3 tầng
            var results = await AggregateAllCandidates(targetObjects, bounds);
            if (results == null || results.Count == 0) return;

            // 2. Mở HandwritingRecognitionDialog hiển thị danh sách ứng viên cho giáo viên chọn
            var dialog = new HandwritingRecognitionDialog
            {
                Owner = this
            };

            dialog.ShowResults(results);

            bool? dialogResult = dialog.ShowDialog();

            if (dialogResult == true || dialog.UserAccepted || dialog.SelectedResult != null)
            {
                var selectedCandidate = dialog.SelectedResult ?? results.FirstOrDefault();
                string? textToUse = selectedCandidate?.Text;

                if (!string.IsNullOrWhiteSpace(textToUse))
                {
                    string convertedText = ApplyTextCase(textToUse, caseMode);
                    ReplaceStrokesWithTextBlock(targetObjects, bounds, convertedText);
                    ShowSmartStatusBadge($"✅ Đã chèn chữ viết → '{convertedText}'");
                    return;
                }
            }
        }

        /// <summary>
        /// Capture nét vẽ của các đối tượng thành hình ảnh NÉT ĐEN TRÊN NỀN TRẮNG TINH KHIẾT (Black on White),
        /// loại bỏ hoàn toàn nền caro xanh, không dính viền chọn hay toolbar, tối ưu 100% cho các công cụ OCR.
        /// Tính toán chính xác tọa độ tuyệt đối của nét vẽ trên canvas.
        /// </summary>
        private (BitmapSource? bitmap, byte[]? bytes) CaptureStrokesAsBlackOnWhite(List<SelectableObject> targetObjects, Rect bounds)
        {
            if (targetObjects == null || targetObjects.Count == 0 || bounds.Width <= 0 || bounds.Height <= 0)
            {
                return (null, null);
            }

            try
            {
                double pad = 35;
                Rect paddedBounds = new Rect(
                    Math.Max(0, bounds.X - pad),
                    Math.Max(0, bounds.Y - pad),
                    bounds.Width + pad * 2,
                    bounds.Height + pad * 2);

                double maxDim = Math.Max(paddedBounds.Width, paddedBounds.Height);
                double scaleFactor = maxDim < 400.0 ? (400.0 / maxDim) : 1.0;

                int width = (int)(paddedBounds.Width * scaleFactor);
                int height = (int)(paddedBounds.Height * scaleFactor);

                var renderBitmap = new RenderTargetBitmap(
                    width,
                    height,
                    96 * scaleFactor,
                    96 * scaleFactor,
                    PixelFormats.Pbgra32);

                var drawingVisual = new DrawingVisual();
                using (var dc = drawingVisual.RenderOpen())
                {
                    // 1. Vẽ nền trắng tinh khiết (Pure White Background)
                    dc.DrawRectangle(Brushes.White, null, new Rect(0, 0, paddedBounds.Width, paddedBounds.Height));

                    // 2. Dịch chuyển tọa độ theo lề padding
                    dc.PushTransform(new TranslateTransform(-paddedBounds.X, -paddedBounds.Y));

                    // 3. Vẽ từng nét chữ bằng màu ĐEN đậm (Pure Black Ink) dựa trên tọa độ tuyệt đối
                    foreach (var obj in targetObjects)
                    {
                        if (obj.Element is Polyline polyline && polyline.Points.Count > 1)
                        {
                            double elemLeft = Canvas.GetLeft(polyline);
                            if (double.IsNaN(elemLeft)) elemLeft = 0;
                            double elemTop = Canvas.GetTop(polyline);
                            if (double.IsNaN(elemTop)) elemTop = 0;

                            var absPoints = polyline.Points.Select(p => new Point(p.X + elemLeft, p.Y + elemTop)).ToList();

                            var streamGeometry = new StreamGeometry();
                            using (var ctx = streamGeometry.Open())
                            {
                                ctx.BeginFigure(absPoints[0], false, false);
                                ctx.PolyLineTo(absPoints.Skip(1).ToList(), true, false);
                            }
                            streamGeometry.Freeze();

                            var pen = new Pen(Brushes.Black, Math.Max(polyline.StrokeThickness * 1.5, 5.0))
                            {
                                StartLineCap = PenLineCap.Round,
                                EndLineCap = PenLineCap.Round,
                                LineJoin = PenLineJoin.Round
                            };
                            dc.DrawGeometry(null, pen, streamGeometry);
                        }
                        else if (obj.Element is System.Windows.Shapes.Path pathElement && pathElement.Data != null)
                        {
                            double elemLeft = Canvas.GetLeft(pathElement);
                            if (double.IsNaN(elemLeft)) elemLeft = 0;
                            double elemTop = Canvas.GetTop(pathElement);
                            if (double.IsNaN(elemTop)) elemTop = 0;

                            dc.PushTransform(new TranslateTransform(elemLeft, elemTop));
                            var pen = new Pen(Brushes.Black, Math.Max(pathElement.StrokeThickness * 1.5, 5.0))
                            {
                                StartLineCap = PenLineCap.Round,
                                EndLineCap = PenLineCap.Round,
                                LineJoin = PenLineJoin.Round
                            };
                            dc.DrawGeometry(pathElement.Fill != null ? Brushes.Black : null, pen, pathElement.Data);
                            dc.Pop();
                        }
                        else if (obj.Element is System.Windows.Shapes.Shape shape)
                        {
                            var pen = new Pen(Brushes.Black, Math.Max(shape.StrokeThickness * 1.5, 5.0))
                            {
                                StartLineCap = PenLineCap.Round,
                                EndLineCap = PenLineCap.Round,
                                LineJoin = PenLineJoin.Round
                            };
                            dc.DrawRectangle(shape.Fill != null ? Brushes.Black : null, pen, obj.Bounds);
                        }
                        else if (obj.Element != null)
                        {
                            var vb = new VisualBrush(obj.Element) { Stretch = Stretch.None };
                            dc.DrawRectangle(vb, null, obj.Bounds);
                        }
                    }

                    dc.Pop();
                }

                renderBitmap.Render(drawingVisual);

                // Chuyển thành mảng byte PNG
                byte[] pngBytes;
                var encoder = new PngBitmapEncoder();
                encoder.Frames.Add(BitmapFrame.Create(renderBitmap));
                using (var ms = new System.IO.MemoryStream())
                {
                    encoder.Save(ms);
                    pngBytes = ms.ToArray();
                }

                return (renderBitmap, pngBytes);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ CaptureStrokesAsBlackOnWhite Error: {ex.Message}");
                return (null, null);
            }
        }

        /// <summary>
        /// Capture vùng được chọn một cách sạch vẽ: Tạm ẩn SelectionBox và ContextToolbar
        /// để ảnh chụp nét chữ hoàn toàn không chứa nét chấm đứt hay núm kéo điều hướng.
        /// Thêm lề (padding) 30px xung quanh để nét chữ không bị mép sát lề.
        /// </summary>
        private (BitmapSource? bitmap, byte[]? bytes) CaptureCleanSelectionArea(Rect selectionBounds)
        {
            var selectedObjs = _selectionManager?.GetSelectedObjects();
            if (selectedObjs != null && selectedObjs.Count > 0)
            {
                var res = CaptureStrokesAsBlackOnWhite(selectedObjs, selectionBounds);
                if (res.bitmap != null && res.bytes != null) return res;
            }

            if (_captureService == null)
            {
                _captureService = new SelectionCaptureService();
            }

            if (selectionBounds.IsEmpty || selectionBounds.Width <= 0 || selectionBounds.Height <= 0)
            {
                return (null, null);
            }

            bool selectionBoxWasVisible = false;
            bool contextToolbarWasVisible = false;

            try
            {
                // 1. Tạm thời ẩn các UI điều khiển (SelectionBox, ContextToolbar)
                if (_selectionBox != null && _selectionBox.Visibility == Visibility.Visible)
                {
                    selectionBoxWasVisible = true;
                    _selectionBox.Visibility = Visibility.Collapsed;
                }
                if (_contextToolbar != null && _contextToolbar.Visibility == Visibility.Visible)
                {
                    contextToolbarWasVisible = true;
                    _contextToolbar.Visibility = Visibility.Collapsed;
                }

                // Cập nhật bố cục UI ngay lập tức
                MainInteractiveBoard.UpdateLayout();

                // 2. Tạo lề padding 30px xung quanh nét chữ
                double pad = 30;
                Rect paddedBounds = new Rect(
                    Math.Max(0, selectionBounds.X - pad),
                    Math.Max(0, selectionBounds.Y - pad),
                    selectionBounds.Width + pad * 2,
                    selectionBounds.Height + pad * 2);

                // 3. Thực hiện capture nét chữ sạch trên canvas
                var bitmap = _captureService.CaptureSelectionAreaAsBitmap(paddedBounds, MainInteractiveBoard);
                var bytes = _captureService.CaptureSelectionArea(paddedBounds, MainInteractiveBoard);

                return (bitmap, bytes);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ CaptureCleanSelectionArea Error: {ex.Message}");
                return (null, null);
            }
            finally
            {
                // Phục hồi lại trạng thái hiển thị UI controls
                if (selectionBoxWasVisible && _selectionBox != null)
                {
                    _selectionBox.Visibility = Visibility.Visible;
                }
                if (contextToolbarWasVisible && _contextToolbar != null)
                {
                    _contextToolbar.Visibility = Visibility.Visible;
                }
                MainInteractiveBoard.UpdateLayout();
            }
        }

        /// <summary>
        /// Dịch vụ suy luận nét vẽ thủ công khi các công cụ OCR không trả kết quả
        /// Phân tích chính xác cấu trúc hình học của nét cọ để phân biệt chữ số 1, 2, 3, 4, 0, - v.v.
        /// </summary>
        private List<HandwritingRecognitionResult> RecognizeStrokeGeometryFallback(SelectableObject? obj)
        {
            var list = new List<HandwritingRecognitionResult>();
            if (obj == null) return list;

            var bounds = obj.Bounds;
            if (bounds.Width <= 0 || bounds.Height <= 0) return list;

            // Phân tích các điểm tọa độ của nét vẽ Polyline
            if (obj.Element is Polyline polyline && polyline.Points.Count >= 3)
            {
                var pts = polyline.Points;
                Point start = pts[0];
                Point end = pts[pts.Count - 1];

                double deltaX = Math.Abs(end.X - start.X);
                double deltaY = Math.Abs(end.Y - start.Y);

                double minY = pts.Min(p => p.Y);
                double maxY = pts.Max(p => p.Y);
                double minX = pts.Min(p => p.X);
                double maxX = pts.Max(p => p.X);
                double height = maxY - minY;
                double midY = minY + height * 0.5;

                // 1. Nét gạch đứng (chủ yếu di chuyển theo chiều Y, hẹp chiều ngang) -> Chữ số 1
                if (deltaY > deltaX * 1.2 && bounds.Height > bounds.Width * 1.2)
                {
                    list.Add(new HandwritingRecognitionResult { Text = "1", Confidence = 0.95f, Rank = 0, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "l", Confidence = 0.85f, Rank = 1, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "I", Confidence = 0.80f, Rank = 2, DetectedLanguage = "en" });
                    return list;
                }

                // 2. Nét gạch ngang (chủ yếu di chuyển theo chiều X) -> Dấu -
                if (deltaX > deltaY * 1.8 || bounds.Width / bounds.Height >= 2.5)
                {
                    list.Add(new HandwritingRecognitionResult { Text = "-", Confidence = 0.95f, Rank = 0, DetectedLanguage = "en" });
                    return list;
                }

                // 3. Đếm số lần nét vẽ nhô về phía bên phải ở nửa trên và nửa dưới
                int rightBumpsUpper = 0;
                int rightBumpsLower = 0;
                double prevX = pts[0].X;
                bool movingRight = false;

                for (int i = 1; i < pts.Count; i++)
                {
                    if (pts[i].X > prevX + 2.5)
                    {
                        if (!movingRight)
                        {
                            movingRight = true;
                            if (pts[i].Y < midY) rightBumpsUpper++;
                            else rightBumpsLower++;
                        }
                    }
                    else if (pts[i].X < prevX - 2.5)
                    {
                        movingRight = false;
                    }
                    prevX = pts[i].X;
                }

                // 4. Phân tích nét L-shape / góc vuông (bắt đầu trên, đi xéo xuống trái rồi vắt sang phải) -> Chữ số 4
                Point lowestXPoint = pts.OrderBy(p => p.X).First();
                if (start.Y < midY && lowestXPoint.Y >= midY * 0.7 && end.X > lowestXPoint.X + 15)
                {
                    list.Add(new HandwritingRecognitionResult { Text = "4", Confidence = 0.95f, Rank = 0, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "L", Confidence = 0.80f, Rank = 1, DetectedLanguage = "en" });
                    return list;
                }

                // 5. Chữ số 5: Nét ngang/ngắn ở đỉnh nửa trên + vòng uốn ở nửa dưới
                var topHalfPts = pts.Where(p => p.Y < midY).ToList();
                double topWidth = topHalfPts.Count >= 2 ? (topHalfPts.Max(p => p.X) - topHalfPts.Min(p => p.X)) : 0;
                if (rightBumpsLower >= 1 && rightBumpsUpper == 0 && topWidth > (maxX - minX) * 0.35)
                {
                    list.Add(new HandwritingRecognitionResult { Text = "5", Confidence = 0.95f, Rank = 0, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "S", Confidence = 0.80f, Rank = 1, DetectedLanguage = "en" });
                    return list;
                }

                // 6. Chữ số 3: Có hai đường cong nhô về phía bên phải (nửa trên + nửa dưới)
                if (rightBumpsUpper >= 1 && rightBumpsLower >= 1)
                {
                    list.Add(new HandwritingRecognitionResult { Text = "3", Confidence = 0.95f, Rank = 0, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "2", Confidence = 0.70f, Rank = 1, DetectedLanguage = "en" });
                    return list;
                }

                // 7. Chữ số 2: Có đường cong ở nửa trên và vuốt ngang ở đáy
                if (rightBumpsUpper >= 1 || (end.X > minX + (maxX - minX) * 0.4 && end.Y > midY))
                {
                    list.Add(new HandwritingRecognitionResult { Text = "2", Confidence = 0.92f, Rank = 0, DetectedLanguage = "en" });
                    list.Add(new HandwritingRecognitionResult { Text = "3", Confidence = 0.80f, Rank = 1, DetectedLanguage = "en" });
                    return list;
                }
            }

            // Mặc định cho trường hợp khác
            if (bounds.Width >= bounds.Height * 0.8)
            {
                list.Add(new HandwritingRecognitionResult { Text = "5", Confidence = 0.85f, Rank = 0, DetectedLanguage = "en" });
                list.Add(new HandwritingRecognitionResult { Text = "2", Confidence = 0.80f, Rank = 1, DetectedLanguage = "en" });
                list.Add(new HandwritingRecognitionResult { Text = "3", Confidence = 0.75f, Rank = 2, DetectedLanguage = "en" });
            }
            else
            {
                list.Add(new HandwritingRecognitionResult { Text = "1", Confidence = 0.85f, Rank = 0, DetectedLanguage = "en" });
            }

            return list;
        }

        /// <summary>
        /// Try to recognize handwriting using Windows built-in Ink recognition (offline fallback)
        /// </summary>
        private string? TryWindowsInkRecognition(SelectableObject obj)
        {
            try
            {
                // Attempt using System.Windows.Ink.InkAnalyzer if available
                // For Polyline, convert points to StylusPoint collection for recognition
                if (obj.Element is Polyline polyline && polyline.Points.Count > 5)
                {
                    var pointsText = new System.Text.StringBuilder();
                    foreach (var pt in polyline.Points)
                    {
                        pointsText.Append($"({pt.X:F0},{pt.Y:F0}) ");
                    }
                    System.Diagnostics.Debug.WriteLine($"📝 Polyline points for recognition: {polyline.Points.Count} points");
                }

                return null; // Windows Ink recognition requires additional assemblies
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Apply text case conversion
        /// </summary>
        private string ApplyTextCase(string text, TextCaseMode mode)
        {
            return mode switch
            {
                TextCaseMode.UpperCase => text.ToUpper(),
                TextCaseMode.LowerCase => text.ToLower(),
                TextCaseMode.TitleCase => ToTitleCase(text) ?? text,
                _ => text
            };
        }

        /// <summary>
        /// Replace a drawing stroke (Polyline/Path/Shape) with a styled TextBlock at the same position
        /// </summary>
        private void ReplaceStrokeWithTextBlock(SelectableObject obj, string text)
        {
            if (obj == null) return;
            ReplaceStrokesWithTextBlock(new List<SelectableObject> { obj }, obj.Bounds, text);
        }

        /// <summary>
        /// Replace one or multiple drawing strokes (Polyline/Path/Shape) with a styled TextBlock at the same location
        /// </summary>
        private void ReplaceStrokesWithTextBlock(List<SelectableObject> targetObjects, Rect bounds, string text)
        {
            if (targetObjects == null || targetObjects.Count == 0 || string.IsNullOrWhiteSpace(text)) return;

            var strokeColor = targetObjects[0].StrokeColor;
            double fontSize = Math.Max(18, Math.Min(bounds.Height * 0.8, 96));

            // Create styled TextBlock with transparent background (NO white background box)
            var textBlock = new System.Windows.Controls.TextBlock
            {
                Text = text,
                FontSize = fontSize,
                FontWeight = FontWeights.Bold,
                FontFamily = new FontFamily("Segoe UI, Arial"),
                Foreground = new SolidColorBrush(strokeColor != Colors.Transparent ? strokeColor : Colors.Black),
                Background = Brushes.Transparent,
                TextWrapping = TextWrapping.NoWrap
            };

            // Force layout update so size is immediately calculated
            textBlock.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            textBlock.Arrange(new Rect(textBlock.DesiredSize));

            double textW = Math.Max(textBlock.DesiredSize.Width, bounds.Width);
            double textH = Math.Max(textBlock.DesiredSize.Height, bounds.Height);

            // Position at exact location of original stroke bounds
            Canvas.SetLeft(textBlock, bounds.X);
            Canvas.SetTop(textBlock, bounds.Y);
            Canvas.SetZIndex(textBlock, Panel.GetZIndex(targetObjects[0].Element) + 1);

            // 1. Remove ALL original stroke elements from Canvas AND unregister from SelectionManager
            foreach (var obj in targetObjects)
            {
                if (obj.Element != null && MainInteractiveBoard.Children.Contains(obj.Element))
                {
                    MainInteractiveBoard.Children.Remove(obj.Element);
                }
                _selectionManager?.RemoveObject(obj);
            }

            // 2. Add new TextBlock to canvas
            MainInteractiveBoard.Children.Add(textBlock);

            // 3. Immediately create and register SelectableObject with SelectionManager (DO NOT WAIT for Loaded event!)
            var newObj = new SelectableObject
            {
                Element = textBlock,
                Type = ObjectType.Text,
                Bounds = new Rect(bounds.X, bounds.Y, textW, textH),
                Position = new Point(bounds.X, bounds.Y),
                Size = new Size(textW, textH),
                ZIndex = Panel.GetZIndex(textBlock),
                TextContent = text
            };

            _selectionManager?.AddObject(newObj);

            // 4. Clean up preview rectangles and old selection, select new text object
            ClearRectangleSelectionPreview();
            _selectionManager?.DeselectAll();
            _selectionManager?.SelectObject(newObj);

            // Record undo action
            RecordAddAction(textBlock, "Handwriting → Text");

            // Fade-in animation for visual feedback
            AnimateFadeIn(textBlock);

            System.Diagnostics.Debug.WriteLine($"✅ Replaced {targetObjects.Count} stroke(s) with TextBlock: '{text}' at ({bounds.X:F0}, {bounds.Y:F0})");
        }

        /// <summary>
        /// Edit text inline with dialog
        /// For drawing objects: recognize handwriting first, then open edit dialog
        /// </summary>
        private async void OnMoreMenuEditText(object? sender, EventArgs e)
        {
            var obj = _selectionManager?.SelectedObjects.FirstOrDefault();
            if (obj == null)
            {
                System.Diagnostics.Debug.WriteLine("⚠️ EditText: No object selected");
                return;
            }

            string? currentText = null;
            bool isDrawingElement = false;

            // Get current text from element
            if (obj.Element is System.Windows.Controls.TextBlock textBlock)
            {
                currentText = textBlock.Text;
            }
            else if (obj.Element is System.Windows.Controls.TextBox textBox)
            {
                currentText = textBox.Text;
            }
            else if (obj.Element is System.Windows.Controls.Border border)
            {
                var childTextBlock = FindVisualChild<System.Windows.Controls.TextBlock>(border);
                if (childTextBlock != null)
                {
                    currentText = childTextBlock.Text;
                }
            }
            // Handle drawing elements → Recognize handwriting first
            else if (obj.Element is Polyline || obj.Element is System.Windows.Shapes.Path || obj.Element is System.Windows.Shapes.Shape)
            {
                isDrawingElement = true;
                _moreMenu?.Hide();

                // Try to recognize handwriting
                if (_captureService != null && _handwritingService != null && _handwritingService.IsInitialized)
                {
                    try
                    {
                        var bounds = obj.Bounds;
                        double pad = 10;
                        var captureBounds = new Rect(
                            Math.Max(0, bounds.X - pad),
                            Math.Max(0, bounds.Y - pad),
                            bounds.Width + pad * 2,
                            bounds.Height + pad * 2);

                        byte[] imageBytes = _captureService.CaptureSelectionArea(captureBounds, MainInteractiveBoard);
                        var results = await _handwritingService.RecognizeHandwritingAsync(imageBytes, 3);

                        if (results != null && results.Count > 0 && !string.IsNullOrWhiteSpace(results[0].Text))
                        {
                            currentText = results[0].Text.Trim();
                            System.Diagnostics.Debug.WriteLine($"✏️ Pre-recognized for edit: '{currentText}'");
                        }
                    }
                    catch (Exception ex)
                    {
                        System.Diagnostics.Debug.WriteLine($"⚠️ Pre-recognition failed: {ex.Message}");
                    }
                }

                if (string.IsNullOrEmpty(currentText))
                {
                    currentText = ""; // Allow user to type text manually
                }
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("⚠️ EditText: Object has no text content");
                _moreMenu?.Hide();
                return;
            }

            // Create edit dialog
            var editWindow = new Window
            {
                Title = isDrawingElement ? "✍️ Chỉnh sửa chữ viết tay" : "📝 Chỉnh sửa văn bản",
                Width = 450,
                Height = 280,
                WindowStartupLocation = WindowStartupLocation.CenterScreen,
                ResizeMode = System.Windows.ResizeMode.NoResize,
                Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
            };

            var stackPanel = new System.Windows.Controls.StackPanel
            {
                Margin = new Thickness(20)
            };

            // Info label for drawing elements
            if (isDrawingElement)
            {
                var infoLabel = new System.Windows.Controls.TextBlock
                {
                    Text = "💡 Văn bản đã được nhận dạng từ nét vẽ. Chỉnh sửa nếu cần:",
                    FontSize = 12,
                    Foreground = new SolidColorBrush(Color.FromRgb(160, 200, 255)),
                    TextWrapping = TextWrapping.Wrap,
                    Margin = new Thickness(0, 0, 0, 8)
                };
                stackPanel.Children.Add(infoLabel);
            }

            // Current text label
            var label = new System.Windows.Controls.Label
            {
                Content = "Nội dung văn bản:",
                FontWeight = FontWeights.Bold,
                Foreground = Brushes.White,
                Margin = new Thickness(0, 0, 0, 5)
            };
            stackPanel.Children.Add(label);

            // Multi-line TextBox for editing
            var textBoxEdit = new System.Windows.Controls.TextBox
            {
                Text = currentText ?? "",
                MinHeight = 100,
                MaxHeight = 150,
                TextWrapping = TextWrapping.Wrap,
                AcceptsReturn = true,
                FontSize = 14,
                VerticalScrollBarVisibility = System.Windows.Controls.ScrollBarVisibility.Auto,
                Margin = new Thickness(0, 0, 0, 15)
            };
            stackPanel.Children.Add(textBoxEdit);

            // Buttons panel
            var buttonsPanel = new System.Windows.Controls.StackPanel
            {
                Orientation = System.Windows.Controls.Orientation.Horizontal,
                HorizontalAlignment = HorizontalAlignment.Right
            };

            var okButton = new System.Windows.Controls.Button
            {
                Content = "✅ Xác nhận",
                Width = 100,
                Height = 32,
                Margin = new Thickness(0, 0, 10, 0),
                IsDefault = true,
                Background = new SolidColorBrush(Color.FromRgb(37, 99, 235)),
                Foreground = Brushes.White,
                BorderThickness = new Thickness(0)
            };
            okButton.Click += (s, args) =>
            {
                editWindow.DialogResult = true;
                editWindow.Close();
            };

            var cancelButton = new System.Windows.Controls.Button
            {
                Content = "❌ Hủy",
                Width = 80,
                Height = 32,
                IsCancel = true
            };
            cancelButton.Click += (s, args) =>
            {
                editWindow.DialogResult = false;
                editWindow.Close();
            };

            buttonsPanel.Children.Add(okButton);
            buttonsPanel.Children.Add(cancelButton);
            stackPanel.Children.Add(buttonsPanel);

            editWindow.Content = stackPanel;

            // Show dialog and get result
            var dialogResult = editWindow.ShowDialog();

            if (dialogResult == true)
            {
                string newText = textBoxEdit.Text;

                if (isDrawingElement)
                {
                    // For drawing elements: replace stroke with TextBlock
                    ReplaceStrokeWithTextBlock(obj, newText);
                    System.Diagnostics.Debug.WriteLine($"✏️ Stroke → Edited text: '{newText}'");
                }
                else
                {
                    // For existing text elements: update text in-place
                    if (obj.Element is System.Windows.Controls.TextBlock tb)
                    {
                        tb.Text = newText;
                        obj.TextContent = newText;
                    }
                    else if (obj.Element is System.Windows.Controls.TextBox txb)
                    {
                        txb.Text = newText;
                        obj.TextContent = newText;
                    }
                    else if (obj.Element is System.Windows.Controls.Border brd)
                    {
                        var childTextBlock = FindVisualChild<System.Windows.Controls.TextBlock>(brd);
                        if (childTextBlock != null)
                        {
                            childTextBlock.Text = newText;
                            obj.TextContent = newText;
                        }
                    }

                    RecordModifyAction(obj.Element, currentText, newText, "Edit Text");
                    System.Diagnostics.Debug.WriteLine($"✏️ Edited text: '{currentText}' → '{newText}'");
                }
            }

            _moreMenu?.Hide();
        }

        /// <summary>
        /// Helper: Convert text to Title Case
        /// </summary>
        private string? ToTitleCase(string? text)
        {
            if (string.IsNullOrEmpty(text))
                return text;

            var textInfo = System.Globalization.CultureInfo.CurrentCulture.TextInfo;
            return textInfo.ToTitleCase(text.ToLower());
        }

        #endregion

        #region Module 2.5: OCR Service

        /// <summary>
        /// Extract/recognize text from selected object using unified smart action pipeline
        /// </summary>
        private async void OnMoreMenuOCR(object? sender, EventArgs e)
        {
            _moreMenu?.Hide();
            await ExecuteSmartActionAsync(SmartActionType.OCR);
        }

        #endregion

                #region Sprint 3: Smart Features

        /// <summary>
        /// Sprint 3 Module 3.1: Web Search - Search selected text on Google/Bing
        /// </summary>
        private void OnMoreMenuWebSearch(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🔍 Web Search clicked");

            try
            {
                var obj = _selectionManager?.SelectedObjects.FirstOrDefault();
                if (obj == null || obj.Element == null)
                {
                    MessageBox.Show("Please select an object first.", "No Selection", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Extract text from selected object
                string? searchText = ExtractTextFromObject(obj);

                if (string.IsNullOrWhiteSpace(searchText))
                {
                    MessageBox.Show("No text found in selected object.", "No Text", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Show search engine selection dialog
                var searchDialog = new Window
                {
                    Title = "Web Search",
                    Width = 400,
                    Height = 250,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                // Display selected text
                var textLabel = new Label
                {
                    Content = "Search for:",
                    FontWeight = FontWeights.Bold
                };
                stackPanel.Children.Add(textLabel);

                var textBox = new TextBox
                {
                    Text = searchText,
                    Height = 60,
                    TextWrapping = TextWrapping.Wrap,
                    VerticalScrollBarVisibility = ScrollBarVisibility.Auto,
                    IsReadOnly = true,
                    Margin = new Thickness(0, 5, 0, 15)
                };
                stackPanel.Children.Add(textBox);

                // Search engine selection
                var engineLabel = new Label
                {
                    Content = "Select search engine:",
                    Margin = new Thickness(0, 10, 0, 5)
                };
                stackPanel.Children.Add(engineLabel);

                var buttonsPanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    Margin = new Thickness(0, 10, 0, 0)
                };

                // Google Search button
                var googleButton = new System.Windows.Controls.Button
                {
                    Content = "🔍 Google",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                googleButton.Click += (s, args) =>
                {
                    string encodedText = Uri.EscapeDataString(searchText);
                    string url = $"https://www.google.com/search?q={encodedText}";
                    System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = url,
                        UseShellExecute = true
                    });
                    searchDialog.Close();
                };

                // Bing Search button
                var bingButton = new System.Windows.Controls.Button
                {
                    Content = "🔎 Bing",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                bingButton.Click += (s, args) =>
                {
                    string encodedText = Uri.EscapeDataString(searchText);
                    string url = $"https://www.bing.com/search?q={encodedText}";
                    System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = url,
                        UseShellExecute = true
                    });
                    searchDialog.Close();
                };

                // Cancel button
                var cancelButton = new System.Windows.Controls.Button
                {
                    Content = "Cancel",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                cancelButton.Click += (s, args) => searchDialog.Close();

                buttonsPanel.Children.Add(googleButton);
                buttonsPanel.Children.Add(bingButton);
                buttonsPanel.Children.Add(cancelButton);
                stackPanel.Children.Add(buttonsPanel);

                searchDialog.Content = stackPanel;
                searchDialog.ShowDialog();

                System.Diagnostics.Debug.WriteLine($"🔍 Web search launched for: '{searchText}'");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Web Search Error: {ex.Message}");
                MessageBox.Show($"Failed to launch web search: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sprint 3 Module 3.2: Translation - Translate selected text using Google Translate
        /// </summary>
        private void OnMoreMenuTranslate(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🌐 Translate clicked");

            try
            {
                var obj = _selectionManager?.SelectedObjects.FirstOrDefault();
                if (obj == null || obj.Element == null)
                {
                    MessageBox.Show("Please select an object first.", "No Selection", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Extract text from selected object
                string? sourceText = ExtractTextFromObject(obj);

                if (string.IsNullOrWhiteSpace(sourceText))
                {
                    MessageBox.Show("No text found in selected object.", "No Text", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Show language selection dialog
                var translateDialog = new Window
                {
                    Title = "Translate Text",
                    Width = 450,
                    Height = 300,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                // Display source text
                var sourceLabel = new Label
                {
                    Content = "Text to translate:",
                    FontWeight = FontWeights.Bold
                };
                stackPanel.Children.Add(sourceLabel);

                var sourceTextBox = new TextBox
                {
                    Text = sourceText,
                    Height = 80,
                    TextWrapping = TextWrapping.Wrap,
                    VerticalScrollBarVisibility = ScrollBarVisibility.Auto,
                    IsReadOnly = true,
                    Margin = new Thickness(0, 5, 0, 15)
                };
                stackPanel.Children.Add(sourceTextBox);

                // Target language selection
                var targetLabel = new Label
                {
                    Content = "Translate to:",
                    Margin = new Thickness(0, 10, 0, 5)
                };
                stackPanel.Children.Add(targetLabel);

                var languageCombo = new ComboBox
                {
                    Margin = new Thickness(0, 5, 0, 15)
                };
                languageCombo.Items.Add(new ComboBoxItem { Content = "Vietnamese (Tiếng Việt)", Tag = "vi" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "English", Tag = "en" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "Chinese (中文)", Tag = "zh-CN" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "Japanese (日本語)", Tag = "ja" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "Korean (한국어)", Tag = "ko" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "French (Français)", Tag = "fr" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "Spanish (Español)", Tag = "es" });
                languageCombo.Items.Add(new ComboBoxItem { Content = "German (Deutsch)", Tag = "de" });
                languageCombo.SelectedIndex = 0; // Default to Vietnamese
                stackPanel.Children.Add(languageCombo);

                // Buttons
                var buttonsPanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    Margin = new Thickness(0, 10, 0, 0)
                };

                var translateButton = new System.Windows.Controls.Button
                {
                    Content = "🌐 Translate",
                    Width = 120,
                    Height = 35,
                    Margin = new Thickness(5),
                    IsDefault = true
                };
                translateButton.Click += (s, args) =>
                {
                    var selectedItem = languageCombo.SelectedItem as ComboBoxItem;
                    string targetLang = selectedItem?.Tag as string ?? "vi";
                    string encodedText = Uri.EscapeDataString(sourceText);
                    string url = $"https://translate.google.com/?sl=auto&tl={targetLang}&text={encodedText}";
                    
                    System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                    {
                        FileName = url,
                        UseShellExecute = true
                    });
                    translateDialog.Close();
                };

                var cancelButton = new System.Windows.Controls.Button
                {
                    Content = "Cancel",
                    Width = 120,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                cancelButton.Click += (s, args) => translateDialog.Close();

                buttonsPanel.Children.Add(translateButton);
                buttonsPanel.Children.Add(cancelButton);
                stackPanel.Children.Add(buttonsPanel);

                translateDialog.Content = stackPanel;
                translateDialog.ShowDialog();

                System.Diagnostics.Debug.WriteLine($"🌐 Translation opened for: '{sourceText}'");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Translation Error: {ex.Message}");
                MessageBox.Show($"Failed to open translation: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sprint 3 Module 3.3: Text-to-Speech - Read selected text aloud
        /// </summary>
        private void OnMoreMenuTextToSpeech(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🔊 Text-to-Speech clicked");

            try
            {
                var obj = _selectionManager?.SelectedObjects.FirstOrDefault();
                if (obj == null || obj.Element == null)
                {
                    MessageBox.Show("Please select an object first.", "No Selection", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Extract text from selected object
                string? textToSpeak = ExtractTextFromObject(obj);

                if (string.IsNullOrWhiteSpace(textToSpeak))
                {
                    MessageBox.Show("No text found in selected object.", "No Text", 
                        MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                // Use System.Speech for Text-to-Speech
                var synthesizer = new System.Speech.Synthesis.SpeechSynthesizer();
                
                // Show TTS control dialog
                var ttsDialog = new Window
                {
                    Title = "Text-to-Speech",
                    Width = 450,
                    Height = 280,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                // Display text
                var textLabel = new Label
                {
                    Content = "Text to speak:",
                    FontWeight = FontWeights.Bold
                };
                stackPanel.Children.Add(textLabel);

                var textBox = new TextBox
                {
                    Text = textToSpeak,
                    Height = 80,
                    TextWrapping = TextWrapping.Wrap,
                    VerticalScrollBarVisibility = ScrollBarVisibility.Auto,
                    IsReadOnly = true,
                    Margin = new Thickness(0, 5, 0, 15)
                };
                stackPanel.Children.Add(textBox);

                // Voice selection
                var voicePanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    Margin = new Thickness(0, 10, 0, 10)
                };
                
                var voiceLabel = new Label { Content = "Voice:", Width = 80 };
                var voiceCombo = new ComboBox { Width = 250 };
                
                foreach (var voice in synthesizer.GetInstalledVoices())
                {
                    voiceCombo.Items.Add(new ComboBoxItem 
                    { 
                        Content = voice.VoiceInfo.Name,
                        Tag = voice.VoiceInfo
                    });
                }
                if (voiceCombo.Items.Count > 0)
                    voiceCombo.SelectedIndex = 0;

                voicePanel.Children.Add(voiceLabel);
                voicePanel.Children.Add(voiceCombo);
                stackPanel.Children.Add(voicePanel);

                // Speed control
                var speedPanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    Margin = new Thickness(0, 5, 0, 15)
                };
                
                var speedLabel = new Label { Content = "Speed:", Width = 80 };
                var speedSlider = new Slider
                {
                    Width = 150,
                    Minimum = -10,
                    Maximum = 10,
                    Value = 0,
                    TickFrequency = 1,
                    IsSnapToTickEnabled = true
                };
                var speedValueLabel = new Label { Content = "Normal", Width = 100 };
                
                speedSlider.ValueChanged += (s, args) =>
                {
                    int speed = (int)speedSlider.Value;
                    speedValueLabel.Content = speed == 0 ? "Normal" : 
                        (speed > 0 ? $"+{speed}" : speed.ToString());
                };

                speedPanel.Children.Add(speedLabel);
                speedPanel.Children.Add(speedSlider);
                speedPanel.Children.Add(speedValueLabel);
                stackPanel.Children.Add(speedPanel);

                // Control buttons
                var buttonsPanel = new StackPanel
                {
                    Orientation = Orientation.Horizontal,
                    HorizontalAlignment = HorizontalAlignment.Center,
                    Margin = new Thickness(0, 10, 0, 0)
                };

                var speakButton = new System.Windows.Controls.Button
                {
                    Content = "â–¶ï¸ Speak",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                speakButton.Click += (s, args) =>
                {
                    try
                    {
                        synthesizer.SpeakAsyncCancelAll();
                        
                        // Set voice
                        var selectedVoice = voiceCombo.SelectedItem as ComboBoxItem;
                        if (selectedVoice != null)
                        {
                            var voiceInfo = selectedVoice.Tag as System.Speech.Synthesis.VoiceInfo;
                            if (voiceInfo != null)
                                synthesizer.SelectVoice(voiceInfo.Name);
                        }
                        
                        // Set speed
                        synthesizer.Rate = (int)speedSlider.Value;
                        
                        // Speak
                        synthesizer.SpeakAsync(textToSpeak);
                        System.Diagnostics.Debug.WriteLine($"🔊 Speaking: '{textToSpeak}'");
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show($"Failed to speak: {ex.Message}", "Error");
                    }
                };

                var stopButton = new System.Windows.Controls.Button
                {
                    Content = "â¹ï¸ Stop",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                stopButton.Click += (s, args) =>
                {
                    synthesizer.SpeakAsyncCancelAll();
                    System.Diagnostics.Debug.WriteLine("â¹ï¸ Speech stopped");
                };

                var closeButton = new System.Windows.Controls.Button
                {
                    Content = "Close",
                    Width = 100,
                    Height = 35,
                    Margin = new Thickness(5)
                };
                closeButton.Click += (s, args) =>
                {
                    synthesizer.SpeakAsyncCancelAll();
                    synthesizer.Dispose();
                    ttsDialog.Close();
                };

                buttonsPanel.Children.Add(speakButton);
                buttonsPanel.Children.Add(stopButton);
                buttonsPanel.Children.Add(closeButton);
                stackPanel.Children.Add(buttonsPanel);

                ttsDialog.Content = stackPanel;
                ttsDialog.Closed += (s, args) => synthesizer.Dispose();
                ttsDialog.ShowDialog();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ TTS Error: {ex.Message}");
                MessageBox.Show($"Failed to initialize Text-to-Speech: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sprint 3 Module 3.4: Voice Input - Convert speech to text
        /// </summary>
        private void OnMoreMenuVoiceInput(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🎤 Voice Input clicked");

            try
            {
                MessageBox.Show(
                    "Voice Input Feature\n\n" +
                    "This feature allows you to convert speech to text using your microphone.\n\n" +
                    "Implementation requires:\n" +
                    "• System.Speech.Recognition namespace\n" +
                    "• Microphone access permissions\n" +
                    "• Windows Speech Recognition setup\n\n" +
                    "This is a placeholder for future implementation.",
                    "Voice Input",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information
                );
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Voice Input Error: {ex.Message}");
                MessageBox.Show($"Failed: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Helper method to extract text from various object types
        /// </summary>
        private string? ExtractTextFromObject(SelectableObject obj)
        {
            if (obj == null || obj.Element == null)
                return null;

            // Extract from TextBlock
            if (obj.Element is TextBlock textBlock)
                return textBlock.Text;

            // Extract from TextBox
            if (obj.Element is TextBox textBox)
                return textBox.Text;

            // Extract from Border with TextBlock child
            if (obj.Element is Border border)
            {
                var childTextBlock = FindVisualChild<TextBlock>(border);
                if (childTextBlock != null)
                    return childTextBlock.Text;
            }

            // Fallback to stored TextContent
            if (!string.IsNullOrEmpty(obj.TextContent))
                return obj.TextContent;

            return null;
        }

        #endregion

        #region Sprint 4: AI Features

        /// <summary>
        /// Sprint 4 Module 4.1: Handwriting Recognition - Convert ink strokes to text
        /// </summary>
        private void OnMoreMenuHandwriting(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("âœï¸ Handwriting Recognition clicked");

            try
            {
                MessageBox.Show(
                    "Handwriting Recognition Feature\n\n" +
                    "This feature converts handwritten ink strokes to text.\n\n" +
                    "Implementation requires:\n" +
                    "• Windows.UI.Input.Inking namespace\n" +
                    "• InkAnalyzer for stroke recognition\n" +
                    "• Machine learning models for text recognition\n\n" +
                    "This is a placeholder for future implementation.",
                    "Handwriting Recognition",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information
                );
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Handwriting Recognition Error: {ex.Message}");
                MessageBox.Show($"Failed: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sprint 4 Module 4.2: Formula Recognition - Detect and convert math formulas
        /// </summary>
        private void OnMoreMenuFormulaRecognition(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🔢 Formula Recognition clicked");

            try
            {
                MessageBox.Show(
                    "Formula Recognition Feature\n\n" +
                    "This feature recognizes mathematical formulas and can:\n" +
                    "• Convert handwritten formulas to LaTeX\n" +
                    "• Generate graphs from equations\n" +
                    "• Solve equations symbolically\n\n" +
                    "Implementation requires:\n" +
                    "• Math OCR/recognition library\n" +
                    "• LaTeX rendering engine\n" +
                    "• Graphing library (e.g., OxyPlot)\n\n" +
                    "This is a placeholder for future implementation.",
                    "Formula Recognition",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information
                );
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Formula Recognition Error: {ex.Message}");
                MessageBox.Show($"Failed: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        #endregion
    }
}
