using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.ShapeDrawing.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 14699-17119
// #region Canvas Size Optimization + Object Action Buttons + Shape Drawing + Path Helpers
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Canvas Size Optimization

        /// <summary>
        /// Trims canvas to fit content with minimal padding (removes white space completely)
        /// Includes StrokeThickness in bounds calculation
        /// </summary>
        private void TrimCanvasToContent(Canvas canvas, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box of all children INCLUDING stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                double left = Canvas.GetLeft(child);
                double top = Canvas.GetTop(child);
                
                // Handle NaN values (use 0)
                if (double.IsNaN(left)) left = 0;
                if (double.IsNaN(top)) top = 0;

                double right = left;
                double bottom = top;

                // Get actual dimensions (Check Shape first to override general FrameworkElement bounds)
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    // For shapes, check their geometry bounds + stroke thickness
                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                        continue;
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                        continue;
                    }
                    else if (shape is Polyline polyline)
                    {
                        foreach (Point pt in polyline.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                        continue;
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        // Ellipse vertices (used for dots on shapes)
                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + ellipse.Width + halfStroke);
                        maxY = Math.Max(maxY, top + ellipse.Height + halfStroke);
                        continue;
                    }
                    
                    right = left + (shape.ActualWidth > 0 ? shape.ActualWidth : shape.Width) + strokeThickness;
                    bottom = top + (shape.ActualHeight > 0 ? shape.ActualHeight : shape.Height) + strokeThickness;
                }
                else if (child is FrameworkElement frameworkElement)
                {
                    right = left + (frameworkElement.ActualWidth > 0 ? frameworkElement.ActualWidth : frameworkElement.Width);
                    bottom = top + (frameworkElement.ActualHeight > 0 ? frameworkElement.ActualHeight : frameworkElement.Height);
                }

                minX = Math.Min(minX, left);
                minY = Math.Min(minY, top);
                maxX = Math.Max(maxX, right);
                maxY = Math.Max(maxY, bottom);
            }

            // If no valid bounds found, keep original size
            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Adjust all children positions to account for removed white space
            double offsetX = minX - padding;
            double offsetY = minY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    // For Lines, adjust X1, Y1, X2, Y2
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    // For Polygons/Polylines, adjust all points
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else if (shape is Polyline polyline)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polyline.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polyline.Points = newPoints;
                    }
                    else
                    {
                        // For other shapes (Rectangle, Ellipse), adjust Canvas position
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    // For other elements, adjust Canvas position
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set new canvas size (content size + padding on all sides)
            double newWidth = (maxX - minX) + (padding * 2);
            double newHeight = (maxY - minY) + (padding * 2);
            
            if (double.IsNaN(newWidth) || double.IsInfinity(newWidth) || newWidth < 10) newWidth = 200;
            if (double.IsNaN(newHeight) || double.IsInfinity(newHeight) || newHeight < 10) newHeight = 200;

            canvas.Width = newWidth;
            canvas.Height = newHeight;
        }

        /// <summary>
        /// Trims canvas to a perfect square centered on sphere
        /// Square side = diameter of sphere on canvas
        /// Sphere center = center of square
        /// </summary>
        private void TrimCanvasToSquare(Canvas canvas, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box including stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Polyline polyline)
                    {
                        foreach (Point pt in polyline.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        double left = Canvas.GetLeft(ellipse);
                        double top = Canvas.GetTop(ellipse);
                        if (double.IsNaN(left)) left = 0;
                        if (double.IsNaN(top)) top = 0;

                        double width = ellipse.ActualWidth > 0 ? ellipse.ActualWidth : ellipse.Width;
                        double height = ellipse.ActualHeight > 0 ? ellipse.ActualHeight : ellipse.Height;

                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + width + halfStroke);
                        maxY = Math.Max(maxY, top + height + halfStroke);
                    }
                }
            }

            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Calculate content dimensions
            double contentWidth = maxX - minX;
            double contentHeight = maxY - minY;

            // Find the diameter (max of width/height)
            double diameter = Math.Max(contentWidth, contentHeight);

            // Calculate center of current content
            double centerX = (minX + maxX) / 2.0;
            double centerY = (minY + maxY) / 2.0;

            // Create square bounds: center remains same, side = diameter
            double squareMinX = centerX - (diameter / 2.0);
            double squareMinY = centerY - (diameter / 2.0);
            double squareMaxX = centerX + (diameter / 2.0);
            double squareMaxY = centerY + (diameter / 2.0);

            // Adjust all children to new origin (squareMinX, squareMinY)
            double offsetX = squareMinX - padding;
            double offsetY = squareMinY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else if (shape is Polyline polyline)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polyline.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polyline.Points = newPoints;
                    }
                    else
                    {
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set canvas to perfect square: side = diameter + padding * 2
            double squareSize = diameter + (padding * 2);
            canvas.Width = Math.Max(squareSize, 10);
            canvas.Height = Math.Max(squareSize, 10);
        }

        /// <summary>
        /// Trims canvas to a perfect square for cube based on space diagonal
        /// Square side = space diagonal of cube (a × √3)
        /// Cube center = center of square
        /// </summary>
        private void TrimCanvasToCubeDiagonal(Canvas canvas, double cubeSize, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box including stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        double left = Canvas.GetLeft(ellipse);
                        double top = Canvas.GetTop(ellipse);
                        if (double.IsNaN(left)) left = 0;
                        if (double.IsNaN(top)) top = 0;

                        double width = ellipse.ActualWidth > 0 ? ellipse.ActualWidth : ellipse.Width;
                        double height = ellipse.ActualHeight > 0 ? ellipse.ActualHeight : ellipse.Height;

                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + width + halfStroke);
                        maxY = Math.Max(maxY, top + height + halfStroke);
                    }
                }
            }

            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Calculate center of current content
            double centerX = (minX + maxX) / 2.0;
            double centerY = (minY + maxY) / 2.0;

            // Calculate space diagonal of cube: diagonal = cubeSize × √3
            // This is the diagonal from one vertex to the opposite vertex in 3D space
            double spaceDiagonal = cubeSize * Math.Sqrt(3);

            // For 2D projection, we need to account for the perspective
            // The projected size should fit within this diagonal
            // Use the actual content size but ensure minimum is the space diagonal
            double contentWidth = maxX - minX;
            double contentHeight = maxY - minY;
            double currentDiagonal = Math.Sqrt(contentWidth * contentWidth + contentHeight * contentHeight);
            
            // Use the larger of actual diagonal or theoretical space diagonal
            double targetDiagonal = Math.Max(currentDiagonal, spaceDiagonal);
            
            // Convert diagonal to square side (for a square, diagonal = side × √2)
            // So side = diagonal / √2
            double squareSide = targetDiagonal / Math.Sqrt(2);

            // Create square bounds centered on cube
            double squareMinX = centerX - (squareSide / 2.0);
            double squareMinY = centerY - (squareSide / 2.0);

            // Adjust all children to new origin
            double offsetX = squareMinX - padding;
            double offsetY = squareMinY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else
                    {
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set canvas to perfect square
            double finalSize = squareSide + (padding * 2);
            canvas.Width = Math.Max(finalSize, 10);
            canvas.Height = Math.Max(finalSize, 10);
        }

        /// <summary>
        /// Trims canvas to a rectangle for pyramid
        /// Rectangle: width = base width, height = pyramid height
        /// </summary>
        private void TrimCanvasToPyramidRectangle(Canvas canvas, double baseSize, double pyramidHeight, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box including stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        double left = Canvas.GetLeft(ellipse);
                        double top = Canvas.GetTop(ellipse);
                        if (double.IsNaN(left)) left = 0;
                        if (double.IsNaN(top)) top = 0;

                        double width = ellipse.ActualWidth > 0 ? ellipse.ActualWidth : ellipse.Width;
                        double height = ellipse.ActualHeight > 0 ? ellipse.ActualHeight : ellipse.Height;

                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + width + halfStroke);
                        maxY = Math.Max(maxY, top + height + halfStroke);
                    }
                }
            }

            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Calculate center of current content
            double centerX = (minX + maxX) / 2.0;
            double centerY = (minY + maxY) / 2.0;

            // Calculate actual content dimensions
            double contentWidth = maxX - minX;
            double contentHeight = maxY - minY;

            // For pyramid: width should fit the base, height should fit the pyramid height
            // The base is typically the circumradius × 2 (for regular polygons)
            // Use the actual projected size but ensure it's at least the theoretical size
            double theoreticalBaseWidth = baseSize * 1.5; // Account for projection and rotation
            double theoreticalHeight = pyramidHeight * 1.2; // Account for projection

            double targetWidth = Math.Max(contentWidth, theoreticalBaseWidth);
            double targetHeight = Math.Max(contentHeight, theoreticalHeight);

            // Create rectangle bounds centered on pyramid
            double rectMinX = centerX - (targetWidth / 2.0);
            double rectMinY = centerY - (targetHeight / 2.0);

            // Adjust all children to new origin
            double offsetX = rectMinX - padding;
            double offsetY = rectMinY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else
                    {
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set canvas to rectangle
            canvas.Width = Math.Max(targetWidth + (padding * 2), 10);
            canvas.Height = Math.Max(targetHeight + (padding * 2), 10);
        }

        /// <summary>
        /// Trims canvas to a rectangle for cylinder
        /// Rectangle: width = diameter (2 × radius), height = cylinder height
        /// </summary>
        private void TrimCanvasToCylinderRectangle(Canvas canvas, double radius, double cylinderHeight, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box including stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        double left = Canvas.GetLeft(ellipse);
                        double top = Canvas.GetTop(ellipse);
                        if (double.IsNaN(left)) left = 0;
                        if (double.IsNaN(top)) top = 0;

                        double width = ellipse.ActualWidth > 0 ? ellipse.ActualWidth : ellipse.Width;
                        double height = ellipse.ActualHeight > 0 ? ellipse.ActualHeight : ellipse.Height;

                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + width + halfStroke);
                        maxY = Math.Max(maxY, top + height + halfStroke);
                    }
                }
            }

            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Calculate center of current content
            double centerX = (minX + maxX) / 2.0;
            double centerY = (minY + maxY) / 2.0;

            // Calculate actual content dimensions
            double contentWidth = maxX - minX;
            double contentHeight = maxY - minY;

            // For cylinder: width = diameter (2 × radius), height = cylinder height
            double theoreticalDiameter = radius * 2.0 * 1.2; // Account for projection
            double theoreticalHeight = cylinderHeight * 1.2; // Account for projection

            double targetWidth = Math.Max(contentWidth, theoreticalDiameter);
            double targetHeight = Math.Max(contentHeight, theoreticalHeight);

            // Create rectangle bounds centered on cylinder
            double rectMinX = centerX - (targetWidth / 2.0);
            double rectMinY = centerY - (targetHeight / 2.0);

            // Adjust all children to new origin
            double offsetX = rectMinX - padding;
            double offsetY = rectMinY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else
                    {
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set canvas to rectangle
            canvas.Width = Math.Max(targetWidth + (padding * 2), 10);
            canvas.Height = Math.Max(targetHeight + (padding * 2), 10);
        }

        /// <summary>
        /// Trims canvas to a rectangle for prism
        /// Rectangle: width = base diagonal, height = hypotenuse of triangle(diagonal, prism height)
        /// hypotenuse = √(diagonal² + height²)
        /// </summary>
        private void TrimCanvasToPrismRectangle(Canvas canvas, double baseSize, double prismHeight, string baseType, double padding = 10)
        {
            if (canvas.Children.Count == 0) return;

            // Get number of sides from base type
            int sides = baseType switch
            {
                "Triangle" => 3,
                "Square" => 4,
                "Pentagon" => 5,
                "Hexagon" => 6,
                _ => 4
            };

            double minX = double.MaxValue;
            double minY = double.MaxValue;
            double maxX = double.MinValue;
            double maxY = double.MinValue;

            // Calculate bounding box including stroke thickness
            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    double strokeThickness = shape.StrokeThickness;
                    double halfStroke = strokeThickness / 2.0;

                    if (shape is Line line)
                    {
                        minX = Math.Min(minX, Math.Min(line.X1, line.X2) - halfStroke);
                        minY = Math.Min(minY, Math.Min(line.Y1, line.Y2) - halfStroke);
                        maxX = Math.Max(maxX, Math.Max(line.X1, line.X2) + halfStroke);
                        maxY = Math.Max(maxY, Math.Max(line.Y1, line.Y2) + halfStroke);
                    }
                    else if (shape is Polygon polygon)
                    {
                        foreach (Point pt in polygon.Points)
                        {
                            minX = Math.Min(minX, pt.X - halfStroke);
                            minY = Math.Min(minY, pt.Y - halfStroke);
                            maxX = Math.Max(maxX, pt.X + halfStroke);
                            maxY = Math.Max(maxY, pt.Y + halfStroke);
                        }
                    }
                    else if (shape is Ellipse ellipse)
                    {
                        double left = Canvas.GetLeft(ellipse);
                        double top = Canvas.GetTop(ellipse);
                        if (double.IsNaN(left)) left = 0;
                        if (double.IsNaN(top)) top = 0;

                        double width = ellipse.ActualWidth > 0 ? ellipse.ActualWidth : ellipse.Width;
                        double height = ellipse.ActualHeight > 0 ? ellipse.ActualHeight : ellipse.Height;

                        minX = Math.Min(minX, left - halfStroke);
                        minY = Math.Min(minY, top - halfStroke);
                        maxX = Math.Max(maxX, left + width + halfStroke);
                        maxY = Math.Max(maxY, top + height + halfStroke);
                    }
                }
            }

            if (minX == double.MaxValue || minY == double.MaxValue || 
                maxX == double.MinValue || maxY == double.MinValue)
                return;

            // Calculate center of current content
            double centerX = (minX + maxX) / 2.0;
            double centerY = (minY + maxY) / 2.0;

            // Calculate actual content dimensions
            double contentWidth = maxX - minX;
            double contentHeight = maxY - minY;

            // For prism base diagonal calculation
            // For regular polygon: diagonal depends on number of sides
            // For n-sided polygon inscribed in circle of radius r:
            // Maximum diagonal â‰ˆ 2 × r (for opposite vertices)
            double circumradius = baseSize / (2.0 * Math.Sin(Math.PI / sides));
            double baseDiagonal = 2.0 * circumradius;

            // Calculate hypotenuse: √(diagonal² + height²)
            double hypotenuse = Math.Sqrt(baseDiagonal * baseDiagonal + prismHeight * prismHeight);

            // Account for projection
            double theoreticalWidth = baseDiagonal * 1.2;
            double theoreticalHeight = hypotenuse * 1.2;

            double targetWidth = Math.Max(contentWidth, theoreticalWidth);
            double targetHeight = Math.Max(contentHeight, theoreticalHeight);

            // Create rectangle bounds centered on prism
            double rectMinX = centerX - (targetWidth / 2.0);
            double rectMinY = centerY - (targetHeight / 2.0);

            // Adjust all children to new origin
            double offsetX = rectMinX - padding;
            double offsetY = rectMinY - padding;

            foreach (UIElement child in canvas.Children)
            {
                if (child is Shape shape)
                {
                    if (shape is Line line)
                    {
                        line.X1 -= offsetX;
                        line.Y1 -= offsetY;
                        line.X2 -= offsetX;
                        line.Y2 -= offsetY;
                    }
                    else if (shape is Polygon polygon)
                    {
                        var newPoints = new PointCollection();
                        foreach (Point pt in polygon.Points)
                        {
                            newPoints.Add(new Point(pt.X - offsetX, pt.Y - offsetY));
                        }
                        polygon.Points = newPoints;
                    }
                    else
                    {
                        double left = Canvas.GetLeft(shape);
                        double top = Canvas.GetTop(shape);
                        if (!double.IsNaN(left)) Canvas.SetLeft(shape, left - offsetX);
                        if (!double.IsNaN(top)) Canvas.SetTop(shape, top - offsetY);
                    }
                }
                else
                {
                    double left = Canvas.GetLeft(child);
                    double top = Canvas.GetTop(child);
                    if (!double.IsNaN(left)) Canvas.SetLeft(child, left - offsetX);
                    if (!double.IsNaN(top)) Canvas.SetTop(child, top - offsetY);
                }
            }

            // Set canvas to rectangle
            canvas.Width = Math.Max(targetWidth + (padding * 2), 10);
            canvas.Height = Math.Max(targetHeight + (padding * 2), 10);
        }

        #endregion

        #region Object Action Buttons (Legacy Cleanup)

        /// <summary>
        /// Hides action buttons (Legacy cleanup method)
        /// </summary>
        private void HideActionButtons()
        {
        }

        #endregion
        
        #region Phase 2 Shape Drawing Helper Methods
        
        /// <summary>
        /// Draws an arrow pointing in specified direction
        /// </summary>
        private void DrawArrow(Polygon polygon, double left, double top, double width, double height, string direction)
        {
            polygon.Points.Clear();
            double midX = left + width / 2;
            double midY = top + height / 2;
            double shaftWidth = height * 0.3;
            double arrowWidth = height * 0.7;
            
            if (direction == "RightArrow")
            {
                // Right-pointing arrow: shaft (left) + triangle (right)
                polygon.Points.Add(new Point(left, midY - shaftWidth / 2));
                polygon.Points.Add(new Point(left + width * 0.6, midY - shaftWidth / 2));
                polygon.Points.Add(new Point(left + width * 0.6, top));
                polygon.Points.Add(new Point(left + width, midY));
                polygon.Points.Add(new Point(left + width * 0.6, top + height));
                polygon.Points.Add(new Point(left + width * 0.6, midY + shaftWidth / 2));
                polygon.Points.Add(new Point(left, midY + shaftWidth / 2));
            }
            else if (direction == "LeftArrow")
            {
                polygon.Points.Add(new Point(left + width, midY - shaftWidth / 2));
                polygon.Points.Add(new Point(left + width * 0.4, midY - shaftWidth / 2));
                polygon.Points.Add(new Point(left + width * 0.4, top));
                polygon.Points.Add(new Point(left, midY));
                polygon.Points.Add(new Point(left + width * 0.4, top + height));
                polygon.Points.Add(new Point(left + width * 0.4, midY + shaftWidth / 2));
                polygon.Points.Add(new Point(left + width, midY + shaftWidth / 2));
            }
            else if (direction == "UpArrow")
            {
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height));
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height * 0.4));
                polygon.Points.Add(new Point(left, top + height * 0.4));
                polygon.Points.Add(new Point(midX, top));
                polygon.Points.Add(new Point(left + width, top + height * 0.4));
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height * 0.4));
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height));
            }
            else if (direction == "DownArrow")
            {
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top));
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height * 0.6));
                polygon.Points.Add(new Point(left, top + height * 0.6));
                polygon.Points.Add(new Point(midX, top + height));
                polygon.Points.Add(new Point(left + width, top + height * 0.6));
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height * 0.6));
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top));
            }
        }
        
        private void DrawDoubleArrow(Polygon polygon, double left, double top, double width, double height, string direction)
        {
            polygon.Points.Clear();
            double midX = left + width / 2;
            double midY = top + height / 2;
            double shaftWidth = height * 0.3;
            
            if (direction == "LeftRightArrow")
            {
                // Left arrow head
                polygon.Points.Add(new Point(left, midY));
                polygon.Points.Add(new Point(left + width * 0.2, top));
                polygon.Points.Add(new Point(left + width * 0.2, midY - shaftWidth / 2));
                // Shaft
                polygon.Points.Add(new Point(left + width * 0.8, midY - shaftWidth / 2));
                // Right arrow head
                polygon.Points.Add(new Point(left + width * 0.8, top));
                polygon.Points.Add(new Point(left + width, midY));
                polygon.Points.Add(new Point(left + width * 0.8, top + height));
                polygon.Points.Add(new Point(left + width * 0.8, midY + shaftWidth / 2));
                // Shaft back
                polygon.Points.Add(new Point(left + width * 0.2, midY + shaftWidth / 2));
                polygon.Points.Add(new Point(left + width * 0.2, top + height));
            }
            else if (direction == "UpDownArrow")
            {
                // Up arrow head
                polygon.Points.Add(new Point(midX, top));
                polygon.Points.Add(new Point(left + width, top + height * 0.2));
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height * 0.2));
                // Shaft
                polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height * 0.8));
                // Down arrow head
                polygon.Points.Add(new Point(left + width, top + height * 0.8));
                polygon.Points.Add(new Point(midX, top + height));
                polygon.Points.Add(new Point(left, top + height * 0.8));
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height * 0.8));
                // Shaft back
                polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height * 0.2));
                polygon.Points.Add(new Point(left, top + height * 0.2));
            }
        }
        
        private void DrawQuadArrow(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double midX = left + width / 2;
            double midY = top + height / 2;
            double inset = Math.Min(width, height) * 0.35;
            double shaftWidth = Math.Min(width, height) * 0.15;
            
            // 4-way cross arrow - 12 points creating + shape with arrow heads
            
            // Top arrow head
            polygon.Points.Add(new Point(midX, top));
            polygon.Points.Add(new Point(midX + inset, top + inset));
            polygon.Points.Add(new Point(midX + shaftWidth / 2, top + inset));
            
            // Right arrow head
            polygon.Points.Add(new Point(midX + shaftWidth / 2, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width - inset, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width, midY));
            polygon.Points.Add(new Point(left + width - inset, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(midX + shaftWidth / 2, midY + shaftWidth / 2));
            
            // Bottom arrow head
            polygon.Points.Add(new Point(midX + shaftWidth / 2, top + height - inset));
            polygon.Points.Add(new Point(midX + inset, top + height - inset));
            polygon.Points.Add(new Point(midX, top + height));
            polygon.Points.Add(new Point(midX - inset, top + height - inset));
            polygon.Points.Add(new Point(midX - shaftWidth / 2, top + height - inset));
            
            // Left arrow head
            polygon.Points.Add(new Point(midX - shaftWidth / 2, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left + inset, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left, midY));
            polygon.Points.Add(new Point(left + inset, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(midX - shaftWidth / 2, midY - shaftWidth / 2));
            
            // Back to top
            polygon.Points.Add(new Point(midX - shaftWidth / 2, top + inset));
            polygon.Points.Add(new Point(midX - inset, top + inset));
        }
        
        private void DrawNotchedRightArrow(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double midY = top + height / 2;
            double shaftWidth = height * 0.3;
            double notchDepth = width * 0.1;
            
            // Right arrow with notch (7 points)
            polygon.Points.Add(new Point(left, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.6, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.6, top));
            polygon.Points.Add(new Point(left + width, midY));
            polygon.Points.Add(new Point(left + width * 0.6, top + height));
            polygon.Points.Add(new Point(left + width * 0.6, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left + notchDepth, midY)); // Notch point
        }
        
        private void DrawPentagonArrow(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double midY = top + height / 2;
            
            // Pentagon arrow (5 points)
            polygon.Points.Add(new Point(left, top));
            polygon.Points.Add(new Point(left + width * 0.7, top));
            polygon.Points.Add(new Point(left + width, midY));
            polygon.Points.Add(new Point(left + width * 0.7, top + height));
            polygon.Points.Add(new Point(left, top + height));
        }
        
        private void DrawChevronArrow(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double midY = top + height / 2;
            double inset = width * 0.2;
            
            // Chevron (V-shaped arrow, 6 points)
            polygon.Points.Add(new Point(left, top));
            polygon.Points.Add(new Point(left + width * 0.7, top));
            polygon.Points.Add(new Point(left + width, midY));
            polygon.Points.Add(new Point(left + width * 0.7, top + height));
            polygon.Points.Add(new Point(left, top + height));
            polygon.Points.Add(new Point(left + inset, midY)); // Inner V point
        }
        
        private void DrawStripedRightArrow(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double midY = top + height / 2;
            double shaftWidth = height * 0.3;
            double stripeWidth = width * 0.05;
            
            // Right arrow with stripe gap (10 points)
            polygon.Points.Add(new Point(left, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.25, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.25, midY - shaftWidth / 2 - height * 0.05)); // Gap up
            polygon.Points.Add(new Point(left + width * 0.3, midY - shaftWidth / 2 - height * 0.05));
            polygon.Points.Add(new Point(left + width * 0.3, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.6, midY - shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.6, top));
            polygon.Points.Add(new Point(left + width, midY));
            polygon.Points.Add(new Point(left + width * 0.6, top + height));
            polygon.Points.Add(new Point(left + width * 0.6, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.3, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left + width * 0.3, midY + shaftWidth / 2 + height * 0.05)); // Gap down
            polygon.Points.Add(new Point(left + width * 0.25, midY + shaftWidth / 2 + height * 0.05));
            polygon.Points.Add(new Point(left + width * 0.25, midY + shaftWidth / 2));
            polygon.Points.Add(new Point(left, midY + shaftWidth / 2));
        }
        
        private void DrawCurvedArrow(Polygon polygon, double left, double top, double width, double height, string direction)
        {
            polygon.Points.Clear();
            int curvePoints = 30;
            
            if (direction == "CurvedRightArrow")
            {
                // Curved right arrow using Bezier-like curve
                for (int i = 0; i <= curvePoints; i++)
                {
                    double t = i / (double)curvePoints;
                    double x = left + width * 0.7 * t;
                    double y = top + height * 0.2 + height * 0.3 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
                // Arrow head
                polygon.Points.Add(new Point(left + width * 0.7, top + height * 0.2));
                polygon.Points.Add(new Point(left + width, top + height * 0.5));
                polygon.Points.Add(new Point(left + width * 0.7, top + height * 0.8));
                
                // Return curve (bottom)
                for (int i = curvePoints; i >= 0; i--)
                {
                    double t = i / (double)curvePoints;
                    double x = left + width * 0.7 * t;
                    double y = top + height * 0.8 + height * 0.1 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
            }
            else if (direction == "CurvedLeftArrow")
            {
                // Mirror of right
                for (int i = 0; i <= curvePoints; i++)
                {
                    double t = i / (double)curvePoints;
                    double x = left + width - width * 0.7 * t;
                    double y = top + height * 0.2 + height * 0.3 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
                polygon.Points.Add(new Point(left + width * 0.3, top + height * 0.2));
                polygon.Points.Add(new Point(left, top + height * 0.5));
                polygon.Points.Add(new Point(left + width * 0.3, top + height * 0.8));
                
                for (int i = curvePoints; i >= 0; i--)
                {
                    double t = i / (double)curvePoints;
                    double x = left + width - width * 0.7 * t;
                    double y = top + height * 0.8 + height * 0.1 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
            }
            else if (direction == "CurvedUpArrow")
            {
                // Vertical curved arrow (up)
                for (int i = 0; i <= curvePoints; i++)
                {
                    double t = i / (double)curvePoints;
                    double y = top + height - height * 0.7 * t;
                    double x = left + width * 0.2 + width * 0.3 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
                polygon.Points.Add(new Point(left + width * 0.2, top + height * 0.3));
                polygon.Points.Add(new Point(left + width * 0.5, top));
                polygon.Points.Add(new Point(left + width * 0.8, top + height * 0.3));
                
                for (int i = curvePoints; i >= 0; i--)
                {
                    double t = i / (double)curvePoints;
                    double y = top + height - height * 0.7 * t;
                    double x = left + width * 0.8 + width * 0.1 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
            }
            else // CurvedDownArrow
            {
                for (int i = 0; i <= curvePoints; i++)
                {
                    double t = i / (double)curvePoints;
                    double y = top + height * 0.7 * t;
                    double x = left + width * 0.2 + width * 0.3 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
                polygon.Points.Add(new Point(left + width * 0.2, top + height * 0.7));
                polygon.Points.Add(new Point(left + width * 0.5, top + height));
                polygon.Points.Add(new Point(left + width * 0.8, top + height * 0.7));
                
                for (int i = curvePoints; i >= 0; i--)
                {
                    double t = i / (double)curvePoints;
                    double y = top + height * 0.7 * t;
                    double x = left + width * 0.8 + width * 0.1 * Math.Sin(t * Math.PI);
                    polygon.Points.Add(new Point(x, y));
                }
            }
        }
        
        private void DrawStar(Polygon polygon, double left, double top, double width, double height, int points)
        {
            polygon.Points.Clear();
            double centerX = left + width / 2;
            double centerY = top + height / 2;
            double outerRadius = Math.Min(width, height) / 2;
            double innerRadius = outerRadius * 0.4;
            
            for (int i = 0; i < points * 2; i++)
            {
                double angle = (i * 180.0 / points - 90) * Math.PI / 180;
                double radius = (i % 2 == 0) ? outerRadius : innerRadius;
                polygon.Points.Add(new Point(
                    centerX + radius * Math.Cos(angle),
                    centerY + radius * Math.Sin(angle)
                ));
            }
        }
        
        private void DrawWave(Polygon polygon, double left, double top, double width, double height, int waves)
        {
            polygon.Points.Clear();
            int points = 50;
            double amplitude = height / (waves * 2);
            
            for (int i = 0; i <= points; i++)
            {
                double x = left + (width * i / points);
                double t = (i * waves * 2 * Math.PI) / points;
                double y = top + height / 2 + amplitude * Math.Sin(t);
                polygon.Points.Add(new Point(x, y));
            }
        }
        
        private void DrawRibbon(Polygon polygon, double left, double top, double width, double height)
        {
            polygon.Points.Clear();
            double curve = width * 0.1;
            // Simple rectangle with slight curves
            polygon.Points.Add(new Point(left + curve, top));
            polygon.Points.Add(new Point(left + width - curve, top));
            polygon.Points.Add(new Point(left + width, top + height / 2));
            polygon.Points.Add(new Point(left + width - curve, top + height));
            polygon.Points.Add(new Point(left + curve, top + height));
            polygon.Points.Add(new Point(left, top + height / 2));
        }
        
        private void DrawFlowchartShape(Polygon polygon, double left, double top, double width, double height, string shapeName)
        {
            polygon.Points.Clear();
            double midX = left + width / 2;
            double midY = top + height / 2;
            
            switch (shapeName)
            {
                case "FlowProcess":
                    // Rectangle
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width, top));
                    polygon.Points.Add(new Point(left + width, top + height));
                    polygon.Points.Add(new Point(left, top + height));
                    break;
                    
                case "FlowDecision":
                    // Diamond
                    polygon.Points.Add(new Point(midX, top));
                    polygon.Points.Add(new Point(left + width, midY));
                    polygon.Points.Add(new Point(midX, top + height));
                    polygon.Points.Add(new Point(left, midY));
                    break;
                    
                case "FlowDocument":
                    // Rectangle with wavy bottom
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width, top));
                    polygon.Points.Add(new Point(left + width, top + height * 0.8));
                    polygon.Points.Add(new Point(midX, top + height));
                    polygon.Points.Add(new Point(left, top + height * 0.8));
                    break;
                    
                default:
                    // Default to rectangle for all other flowchart shapes
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width, top));
                    polygon.Points.Add(new Point(left + width, top + height));
                    polygon.Points.Add(new Point(left, top + height));
                    break;
            }
        }
        
        private void DrawCallout(Polygon polygon, double left, double top, double width, double height, string shapeName)
        {
            polygon.Points.Clear();
            
            switch (shapeName)
            {
                case "RectangularCallout":
                    // Simple rectangle with bottom pointer
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width, top));
                    polygon.Points.Add(new Point(left + width, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.6, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.5, top + height));  // Pointer tip
                    polygon.Points.Add(new Point(left + width * 0.4, top + height * 0.7));
                    polygon.Points.Add(new Point(left, top + height * 0.7));
                    break;
                
                case "RoundedRectangularCallout":
                    // Rounded corners approximation + pointer
                    polygon.Points.Add(new Point(left + width * 0.1, top));
                    polygon.Points.Add(new Point(left + width * 0.9, top));
                    polygon.Points.Add(new Point(left + width, top + height * 0.1));
                    polygon.Points.Add(new Point(left + width, top + height * 0.6));
                    polygon.Points.Add(new Point(left + width * 0.9, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.55, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.5, top + height));  // Pointer
                    polygon.Points.Add(new Point(left + width * 0.45, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.1, top + height * 0.7));
                    polygon.Points.Add(new Point(left, top + height * 0.6));
                    polygon.Points.Add(new Point(left, top + height * 0.1));
                    break;
                
                case "OvalCallout":
                    // Simplified oval (octagon) with pointer
                    polygon.Points.Add(new Point(left + width * 0.3, top));
                    polygon.Points.Add(new Point(left + width * 0.7, top));
                    polygon.Points.Add(new Point(left + width, top + height * 0.2));
                    polygon.Points.Add(new Point(left + width, top + height * 0.5));
                    polygon.Points.Add(new Point(left + width * 0.7, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.55, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.5, top + height));  // Pointer
                    polygon.Points.Add(new Point(left + width * 0.45, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.3, top + height * 0.7));
                    polygon.Points.Add(new Point(left, top + height * 0.5));
                    polygon.Points.Add(new Point(left, top + height * 0.2));
                    break;
                
                case "CloudCallout":
                    // Simplified cloud (wavy edges) with pointer
                    polygon.Points.Add(new Point(left + width * 0.2, top));
                    polygon.Points.Add(new Point(left + width * 0.4, top + height * 0.05));
                    polygon.Points.Add(new Point(left + width * 0.6, top));
                    polygon.Points.Add(new Point(left + width * 0.8, top + height * 0.05));
                    polygon.Points.Add(new Point(left + width, top + height * 0.2));
                    polygon.Points.Add(new Point(left + width * 0.95, top + height * 0.4));
                    polygon.Points.Add(new Point(left + width, top + height * 0.6));
                    polygon.Points.Add(new Point(left + width * 0.8, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.55, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.5, top + height));  // Pointer
                    polygon.Points.Add(new Point(left + width * 0.45, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.2, top + height * 0.7));
                    polygon.Points.Add(new Point(left, top + height * 0.6));
                    polygon.Points.Add(new Point(left + width * 0.05, top + height * 0.4));
                    polygon.Points.Add(new Point(left, top + height * 0.2));
                    break;
                
                case "LineCallout1":
                case "BorderCallout1":
                case "AccentCallout1":
                    // Rectangle with straight line pointer extending down-right
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width * 0.7, top));
                    polygon.Points.Add(new Point(left + width * 0.7, top + height * 0.6));
                    polygon.Points.Add(new Point(left, top + height * 0.6));
                    break;
                
                case "LineCallout2":
                case "BorderCallout2":
                case "AccentCallout2":
                    // Rectangle with angled pointer to right
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width * 0.65, top));
                    polygon.Points.Add(new Point(left + width * 0.65, top + height * 0.6));
                    polygon.Points.Add(new Point(left, top + height * 0.6));
                    break;
                
                case "LineCallout3":
                case "BorderCallout3":
                case "AccentCallout3":
                    // Rectangle with longer pointer
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width * 0.6, top));
                    polygon.Points.Add(new Point(left + width * 0.6, top + height * 0.5));
                    polygon.Points.Add(new Point(left, top + height * 0.5));
                    break;
                
                case "LineCallout4":
                    // Rectangle with bordered edge
                    polygon.Points.Add(new Point(left + width * 0.05, top + height * 0.05));
                    polygon.Points.Add(new Point(left + width * 0.65, top + height * 0.05));
                    polygon.Points.Add(new Point(left + width * 0.65, top + height * 0.55));
                    polygon.Points.Add(new Point(left + width * 0.05, top + height * 0.55));
                    break;
                
                default:
                    // Fallback: simple rectangle callout
                    polygon.Points.Add(new Point(left, top));
                    polygon.Points.Add(new Point(left + width, top));
                    polygon.Points.Add(new Point(left + width, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.6, top + height * 0.7));
                    polygon.Points.Add(new Point(left + width * 0.5, top + height));
                    polygon.Points.Add(new Point(left + width * 0.4, top + height * 0.7));
                    polygon.Points.Add(new Point(left, top + height * 0.7));
                    break;
            }
        }
        
        
        #endregion

        #region Path-based Equation Shape Helpers (Multi-Component)
        
        private void UpdatePathEquationShape(System.Windows.Shapes.Path path, Point startPoint, Point currentPoint)
        {
            double left = Math.Min(startPoint.X, currentPoint.X);
            double top = Math.Min(startPoint.Y, currentPoint.Y);
            double width = Math.Abs(currentPoint.X - startPoint.X);
            double height = Math.Abs(currentPoint.Y - startPoint.Y);
            
            GeometryGroup geometryGroup = new GeometryGroup();
            
            if (_currentShape == "Approximately")
            {
                // â‰ˆ symbol - TWO wavy lines
                geometryGroup.Children.Add(CreateWavyLine(left, top + height * 0.35, width, height * 0.08));
                geometryGroup.Children.Add(CreateWavyLine(left, top + height * 0.65, width, height * 0.08));
            }
            else if (_currentShape == "Equal")
            {
                // = symbol - TWO horizontal lines
                double lineThickness = height * 0.08;
                geometryGroup.Children.Add(CreateRectangle(left, top + height * 0.35, width, lineThickness));
                geometryGroup.Children.Add(CreateRectangle(left, top + height * 0.65, width, lineThickness));
            }
            else if (_currentShape == "Minus")
            {
                // − symbol - ONE horizontal line
                double lineThickness = height * 0.08;
                geometryGroup.Children.Add(CreateRectangle(left, top + height * 0.46, width, lineThickness));
            }
            else if (_currentShape == "Multiply")
            {
                // × symbol - TWO diagonal lines with white intersection gap
                double lineThickness = height * 0.12; // Thicker for visibility
                
                // Create path with two crossing lines
                PathGeometry pathGeo = new PathGeometry();
                
                // First diagonal (top-left to bottom-right)
                PathFigure line1 = new PathFigure();
                line1.StartPoint = new Point(left + width * 0.15, top + height * 0.15);
                line1.Segments.Add(new LineSegment(new Point(left + width * 0.85, top + height * 0.85), true));
                pathGeo.Figures.Add(line1);
                
                // Second diagonal (top-right to bottom-left)
                PathFigure line2 = new PathFigure();
                line2.StartPoint = new Point(left + width * 0.85, top + height * 0.15);
                line2.Segments.Add(new LineSegment(new Point(left + width * 0.15, top + height * 0.85), true));
                pathGeo.Figures.Add(line2);
                
                geometryGroup.Children.Add(pathGeo);
            }
            else if (_currentShape == "Divide")
            {
                // Ã· symbol - Line + TWO dots
                double lineThickness = height * 0.05;
                double dotRadius = height * 0.08;
                double midX = left + width * 0.5;
                double midY = top + height * 0.5;
                
                geometryGroup.Children.Add(CreateRectangle(left, midY - lineThickness / 2, width, lineThickness));
                geometryGroup.Children.Add(CreateCircle(midX, midY - height * 0.25, dotRadius));
                geometryGroup.Children.Add(CreateCircle(midX, midY + height * 0.25, dotRadius));
            }
            else if (_currentShape == "NotEqual")
            {
                // â‰  symbol - TWO lines + diagonal slash with white intersections
                double lineThickness = height * 0.12;
                
                // Create path with three lines
                PathGeometry pathGeo = new PathGeometry();
                
                // Top horizontal line
                PathFigure line1 = new PathFigure();
                line1.StartPoint = new Point(left, top + height * 0.35);
                line1.Segments.Add(new LineSegment(new Point(left + width, top + height * 0.35), true));
                pathGeo.Figures.Add(line1);
                
                // Bottom horizontal line
                PathFigure line2 = new PathFigure();
                line2.StartPoint = new Point(left, top + height * 0.65);
                line2.Segments.Add(new LineSegment(new Point(left + width, top + height * 0.65), true));
                pathGeo.Figures.Add(line2);
                
                // Diagonal slash
                PathFigure line3 = new PathFigure();
                line3.StartPoint = new Point(left + width * 0.3, top);
                line3.Segments.Add(new LineSegment(new Point(left + width * 0.7, top + height), true));
                pathGeo.Figures.Add(line3);
                
                geometryGroup.Children.Add(pathGeo);
            }
            else if (_currentShape == "LessOrEqual")
            {
                // â‰¤ symbol - < V-shape + horizontal line below
                double lineThickness = height * 0.08;
                geometryGroup.Children.Add(CreateVShape(left, top + height * 0.25, width, height * 0.4, true)); // pointing left
                geometryGroup.Children.Add(CreateRectangle(left + width * 0.1, top + height * 0.75, width * 0.8, lineThickness));
            }
            else if (_currentShape == "GreaterOrEqual")
            {
                // â‰¥ symbol - > V-shape + horizontal line below
                double lineThickness = height * 0.08;
                geometryGroup.Children.Add(CreateVShape(left, top + height * 0.25, width, height * 0.4, false)); // pointing right
                geometryGroup.Children.Add(CreateRectangle(left + width * 0.1, top + height * 0.75, width * 0.8, lineThickness));
            }
            else if (_currentShape == "LessThan")
            {
                // < symbol - V-shape pointing left
                geometryGroup.Children.Add(CreateVShape(left, top, width, height, true));
            }
            else if (_currentShape == "GreaterThan")
            {
                // > symbol - V-shape pointing right
                geometryGroup.Children.Add(CreateVShape(left, top, width, height, false));
            }
            else if (_currentShape == "Plus")
            {
                // + symbol - Vertical + Horizontal lines with white intersection gap
                double lineThickness = height * 0.12;
                
                // Create path with two crossing lines
                PathGeometry pathGeo = new PathGeometry();
                
                // Vertical line
                PathFigure vLine = new PathFigure();
                vLine.StartPoint = new Point(left + width * 0.5, top);
                vLine.Segments.Add(new LineSegment(new Point(left + width * 0.5, top + height), true));
                pathGeo.Figures.Add(vLine);
                
                // Horizontal line
                PathFigure hLine = new PathFigure();
                hLine.StartPoint = new Point(left, top + height * 0.5);
                hLine.Segments.Add(new LineSegment(new Point(left + width, top + height * 0.5), true));
                pathGeo.Figures.Add(hLine);
                
                geometryGroup.Children.Add(pathGeo);
            }
            else if (_currentShape == "Infinity")
            {
                geometryGroup.Children.Add(CreateInfinitySymbol(left, top, width, height));
            }
            else if (_currentShape == "Radical")
            {
                geometryGroup.Children.Add(CreateRadicalSymbol(left, top, width, height));
            }
            else if (_currentShape == "Summation")
            {
                geometryGroup.Children.Add(CreateSummationSymbol(left, top, width, height));
            }
            else if (_currentShape == "Integral")
            {
                geometryGroup.Children.Add(CreateIntegralSymbol(left, top, width, height));
            }
            
            path.Data = geometryGroup;
            
            // BUGFIX: Store intersection data for white overlay (to be drawn after finalization)
            if (_currentShape == "Plus" || _currentShape == "Multiply" || _currentShape == "NotEqual")
            {
                // Store shape type and bounds for later white intersection drawing
                path.Tag = new
                {
                    ShapeType = _currentShape,
                    Left = left,
                    Top = top,
                    Width = width,
                    Height = height,
                    LineThickness = height * 0.08,
                    NeedsWhiteIntersection = true
                };
            }
        }
        
        // Helper: Create wavy line geometry
        private Geometry CreateWavyLine(double x, double y, double width, double thickness)
        {
            PathGeometry pathGeo = new PathGeometry();
            PathFigure figure = new PathFigure();
            figure.StartPoint = new Point(x, y);
            
            int waves = 4;
            double waveHeight = thickness * 2;
            
            for (int i = 0; i <= 30; i++)
            {
                double t = (double)i / 30;
                double px = x + width * t;
                double py = y + waveHeight * Math.Sin(t * Math.PI * waves);
                figure.Segments.Add(new LineSegment(new Point(px, py), true));
            }
            
            // Return path for thickness
            for (int i = 30; i >= 0; i--)
            {
                double t = (double)i / 30;
                double px = x + width * t;
                double py = y + waveHeight * Math.Sin(t * Math.PI * waves) + thickness;
                figure.Segments.Add(new LineSegment(new Point(px, py), true));
            }
            
            figure.IsClosed = true;
            pathGeo.Figures.Add(figure);
            return pathGeo;
        }
        
        // Helper: Create rectangle geometry
        private Geometry CreateRectangle(double x, double y, double width, double height)
        {
            return new RectangleGeometry(new Rect(x, y, width, height));
        }
        
        // Helper: Create circle geometry
        private Geometry CreateCircle(double centerX, double centerY, double radius)
        {
            return new EllipseGeometry(new Point(centerX, centerY), radius, radius);
        }
        
        // Helper: Create V-shape (< or >)
        private Geometry CreateVShape(double x, double y, double width, double height, bool pointingLeft)
        {
            PathGeometry pathGeo = new PathGeometry();
            PathFigure figure = new PathFigure();
            
            double thickness = Math.Min(width, height) * 0.08;
            double midY = y + height * 0.5;
            
            if (pointingLeft)
            {
                // < shape
                figure.StartPoint = new Point(x + width * 0.8, y + height * 0.1);
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.2, midY), true));
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.8, y + height * 0.9), true));
                figure.Segments.Add(new LineSegment(new Point(x + width, y + height * 0.9), true));
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.4, midY), true));
                figure.Segments.Add(new LineSegment(new Point(x + width, y + height * 0.1), true));
            }
            else
            {
                // > shape
                figure.StartPoint = new Point(x + width * 0.2, y + height * 0.1);
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.8, midY), true));
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.2, y + height * 0.9), true));
                figure.Segments.Add(new LineSegment(new Point(x, y + height * 0.9), true));
                figure.Segments.Add(new LineSegment(new Point(x + width * 0.6, midY), true));
                figure.Segments.Add(new LineSegment(new Point(x, y + height * 0.1), true));
            }
            
            figure.IsClosed = true;
            pathGeo.Figures.Add(figure);
            return pathGeo;
        }
        
        // Helper: Create infinity symbol (âˆž)
        private Geometry CreateInfinitySymbol(double x, double y, double width, double height)
        {
            // Create infinity using two ellipse loops
            GeometryGroup group = new GeometryGroup();
            
            double loopWidth = width * 0.45;
            double loopHeight = height * 0.8;
            
            // Left loop
            EllipseGeometry leftLoop = new EllipseGeometry(
                new Point(x + width * 0.25, y + height * 0.5),
                loopWidth / 2,
                loopHeight / 2
            );
            
            // Right loop
            EllipseGeometry rightLoop = new EllipseGeometry(
                new Point(x + width * 0.75, y + height * 0.5),
                loopWidth / 2,
                loopHeight / 2
            );
            
            group.Children.Add(leftLoop);
            group.Children.Add(rightLoop);
            
            return group;
        }
        
        // Helper: Create radical symbol (√)
        private Geometry CreateRadicalSymbol(double x, double y, double width, double height)
        {
            PathGeometry pathGeo = new PathGeometry();
            PathFigure figure = new PathFigure();
            
            double thickness = height * 0.05;
            
            // √ shape: Short vertical, diagonal down, diagonal up, horizontal bar
            figure.StartPoint = new Point(x + width * 0.1, y + height * 0.5);
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.25, y + height * 0.9), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.4, y + height * 0.1), true));
            figure.Segments.Add(new LineSegment(new Point(x + width, y + height * 0.1), true));
            figure.Segments.Add(new LineSegment(new Point(x + width, y + height * 0.1 + thickness), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.42, y + height * 0.1 + thickness), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.27, y + height * 0.85), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.15, y + height * 0.5), true));
            
            figure.IsClosed = true;
            pathGeo.Figures.Add(figure);
            return pathGeo;
        }
        
        // Helper: Create summation symbol (Î£)
        private Geometry CreateSummationSymbol(double x, double y, double width, double height)
        {
            PathGeometry pathGeo = new PathGeometry();
            PathFigure figure = new PathFigure();
            
            double thickness = height * 0.08;
            
            // Î£ shape
            figure.StartPoint = new Point(x, y);
            figure.Segments.Add(new LineSegment(new Point(x + width, y), true));
            figure.Segments.Add(new LineSegment(new Point(x + width, y + thickness), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.3, y + height * 0.5), true));
            figure.Segments.Add(new LineSegment(new Point(x + width, y + height - thickness), true));
            figure.Segments.Add(new LineSegment(new Point(x + width, y + height), true));
            figure.Segments.Add(new LineSegment(new Point(x, y + height), true));
            figure.Segments.Add(new LineSegment(new Point(x + width * 0.5, y + height * 0.5), true));
            
            figure.IsClosed = true;
            pathGeo.Figures.Add(figure);
            return pathGeo;
        }
        
        // Helper: Create integral symbol (âˆ«)
        private Geometry CreateIntegralSymbol(double x, double y, double width, double height)
        {
            PathGeometry pathGeo = new PathGeometry();
            PathFigure figure = new PathFigure();
            
            double midX = x + width * 0.5;
            
            // âˆ« shape using Bezier curve
            figure.StartPoint = new Point(midX + width * 0.2, y);
            figure.Segments.Add(new BezierSegment(
                new Point(midX - width * 0.1, y + height * 0.2),
                new Point(midX - width * 0.1, y + height * 0.4),
                new Point(midX, y + height * 0.5),
                true));
            figure.Segments.Add(new BezierSegment(
                new Point(midX + width * 0.1, y + height * 0.6),
                new Point(midX + width * 0.1, y + height * 0.8),
                new Point(midX - width * 0.2, y + height),
                true));
            
            // Add thickness by creating return path
            figure.Segments.Add(new LineSegment(new Point(midX - width * 0.15, y + height), true));
            figure.Segments.Add(new BezierSegment(
                new Point(midX + width * 0.15, y + height * 0.8),
                new Point(midX + width * 0.15, y + height * 0.6),
                new Point(midX + width * 0.05, y + height * 0.5),
                true));
            figure.Segments.Add(new BezierSegment(
                new Point(midX - width * 0.05, y + height * 0.4),
                new Point(midX - width * 0.05, y + height * 0.2),
                new Point(midX + width * 0.15, y),
                true));
            
            figure.IsClosed = true;
            pathGeo.Figures.Add(figure);
            return pathGeo;
        }
        
        #endregion
    }
}