using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.AdvancedFeatures.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 20687-21745
// #region Sprint 5: Advanced Features
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Sprint 5: Advanced Features

        /// <summary>
        /// Sprint 5 Module 5.1/5.2: Group selected objects
        /// </summary>
        private void OnMoreMenuGroup(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("📦 Group clicked");

            try
            {
                var selectedObjects = _selectionManager?.SelectedObjects;
                
                if (selectedObjects == null || selectedObjects.Count < 2)
                {
                    MessageBox.Show(
                        "Please select at least 2 objects to group.\n\n" +
                        "Tip: Hold Ctrl and click multiple objects to select them.",
                        "Group Objects",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                    return;
                }

                // Create new group ID
                string groupId = Guid.NewGuid().ToString();
                
                // Assign group ID to all selected objects
                foreach (var obj in selectedObjects)
                {
                    obj.GroupId = groupId;
                }

                // Calculate group bounds
                double minX = selectedObjects.Min(o => o.Position.X);
                double minY = selectedObjects.Min(o => o.Position.Y);
                double maxX = selectedObjects.Max(o => o.Position.X + o.Size.Width);
                double maxY = selectedObjects.Max(o => o.Position.Y + o.Size.Height);

                System.Diagnostics.Debug.WriteLine(
                    $"📦 Grouped {selectedObjects.Count} objects with GroupId: {groupId}\n" +
                    $"   Bounds: ({minX}, {minY}) - ({maxX}, {maxY})"
                );

                MessageBox.Show(
                    $"Successfully grouped {selectedObjects.Count} objects!\n\n" +
                    $"Group ID: {groupId.ToString().Substring(0, 8)}...\n" +
                    $"Size: {maxX - minX:F0} x {maxY - minY:F0}",
                    "Group Created",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information
                );
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Group Error: {ex.Message}");
                MessageBox.Show($"Failed to group objects: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sprint 5 Module 5.2: Ungroup selected objects
        /// </summary>
        private void OnMoreMenuUngroup(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("📂 Ungroup clicked");

            try
            {
                var selectedObjects = _selectionManager?.SelectedObjects;
                
                if (selectedObjects == null || selectedObjects.Count == 0)
                {
                    MessageBox.Show(
                        "Please select grouped objects to ungroup.",
                        "Ungroup Objects",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                    return;
                }

                // Find objects with GroupId
                var groupedObjects = selectedObjects.Where(o => o.GroupId != null).ToList();
                
                if (groupedObjects.Count == 0)
                {
                    MessageBox.Show(
                        "Selected objects are not grouped.",
                        "Ungroup Objects",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                    return;
                }

                // Get unique group IDs
                var groupIds = groupedObjects.Select(o => o.GroupId).Distinct().ToList();
                
                // Remove group IDs from all objects
                foreach (var obj in groupedObjects)
                {
                    obj.GroupId = null;
                }

                System.Diagnostics.Debug.WriteLine($"📂 Ungrouped {groupedObjects.Count} objects from {groupIds.Count} group(s)");

                MessageBox.Show(
                    $"Successfully ungrouped {groupedObjects.Count} objects!\n\n" +
                    $"Groups removed: {groupIds.Count}",
                    "Ungroup Complete",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information
                );
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Ungroup Error: {ex.Message}");
                MessageBox.Show($"Failed to ungroup objects: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Sao chép nhiều lần — clone N copies with offset
        /// </summary>
        private void OnMoreMenuDuplicate(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("📋 Duplicate Multiple clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj?.Element == null)
            {
                MessageBox.Show("Vui lòng chọn một đối tượng để sao chép.", "Sao chép nhiều lần",
                    MessageBoxButton.OK, MessageBoxImage.Information);
                _moreMenu?.Hide();
                return;
            }

            try
            {
                // Dialog nhập số lần và offset
                var inputWindow = new Window
                {
                    Title = "Sao chép nhiều lần",
                    Width = 380, Height = 280,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize,
                    Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                // Number of copies
                stackPanel.Children.Add(new TextBlock { Text = "Số lần sao chép:", Foreground = Brushes.White, FontSize = 14 });
                var txtCopies = new TextBox { Text = "3", FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 12) };
                stackPanel.Children.Add(txtCopies);

                // Offset X
                stackPanel.Children.Add(new TextBlock { Text = "Khoảng cách X (px):", Foreground = Brushes.White, FontSize = 14 });
                var txtOffsetX = new TextBox { Text = "30", FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 12) };
                stackPanel.Children.Add(txtOffsetX);

                // Offset Y
                stackPanel.Children.Add(new TextBlock { Text = "Khoảng cách Y (px):", Foreground = Brushes.White, FontSize = 14 });
                var txtOffsetY = new TextBox { Text = "30", FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 12) };
                stackPanel.Children.Add(txtOffsetY);

                // Buttons
                var btnPanel = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right };
                var btnOK = new Button
                {
                    Content = "Sao chép", Width = 90, Height = 32, Margin = new Thickness(0, 0, 8, 0),
                    Background = new SolidColorBrush(Color.FromRgb(0, 122, 204)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };
                var btnCancel = new Button
                {
                    Content = "Hủy", Width = 70, Height = 32,
                    Background = new SolidColorBrush(Color.FromRgb(100, 100, 100)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };
                btnOK.Click += (s, args) => { inputWindow.DialogResult = true; };
                btnCancel.Click += (s, args) => { inputWindow.DialogResult = false; };
                btnPanel.Children.Add(btnOK);
                btnPanel.Children.Add(btnCancel);
                stackPanel.Children.Add(btnPanel);

                inputWindow.Content = stackPanel;

                if (inputWindow.ShowDialog() == true)
                {
                    if (int.TryParse(txtCopies.Text, out int copies) && copies > 0 && copies <= 50 &&
                        double.TryParse(txtOffsetX.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double offsetX) &&
                        double.TryParse(txtOffsetY.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double offsetY))
                    {
                        var sourceElement = obj.Element as FrameworkElement;
                        if (sourceElement == null) return;

                        for (int i = 1; i <= copies; i++)
                        {
                            UIElement? clone = CloneUIElement(sourceElement);
                            if (clone != null)
                            {
                                double newX = obj.Position.X + (offsetX * i);
                                double newY = obj.Position.Y + (offsetY * i);
                                Canvas.SetLeft(clone, newX);
                                Canvas.SetTop(clone, newY);
                                Panel.SetZIndex(clone, obj.ZIndex);

                                MainInteractiveBoard.Children.Add(clone);
                                RecordAddAction(clone, $"Duplicate copy #{i}");
                                RegisterNewObjectWithSelectionManager(clone);
                            }
                        }

                        System.Diagnostics.Debug.WriteLine($"📋 Duplicated {copies} copies with offset ({offsetX}, {offsetY})");
                    }
                    else
                    {
                        MessageBox.Show("Giá trị không hợp lệ. Số lần: 1-50, offset: số thực.", "Lỗi",
                            MessageBoxButton.OK, MessageBoxImage.Warning);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Duplicate Error: {ex.Message}");
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Clone a UIElement (supports Polyline, Path, Line, Shape, Image, TextBlock, Border)
        /// </summary>
        private UIElement? CloneUIElement(FrameworkElement source)
        {
            try
            {
                if (source is Polyline polyline)
                {
                    var clone = new Polyline
                    {
                        Stroke = polyline.Stroke?.Clone(),
                        StrokeThickness = polyline.StrokeThickness,
                        StrokeLineJoin = polyline.StrokeLineJoin,
                        StrokeStartLineCap = polyline.StrokeStartLineCap,
                        StrokeEndLineCap = polyline.StrokeEndLineCap,
                        Opacity = polyline.Opacity
                    };
                    foreach (var pt in polyline.Points) clone.Points.Add(pt);
                    return clone;
                }
                else if (source is System.Windows.Shapes.Path path && path.Data != null)
                {
                    var clone = new System.Windows.Shapes.Path
                    {
                        Data = path.Data.Clone(),
                        Stroke = path.Stroke?.Clone(),
                        StrokeThickness = path.StrokeThickness,
                        StrokeLineJoin = path.StrokeLineJoin,
                        StrokeStartLineCap = path.StrokeStartLineCap,
                        StrokeEndLineCap = path.StrokeEndLineCap,
                        Fill = path.Fill?.Clone(),
                        Opacity = path.Opacity
                    };
                    return clone;
                }
                else if (source is System.Windows.Shapes.Line line)
                {
                    return new System.Windows.Shapes.Line
                    {
                        X1 = line.X1, Y1 = line.Y1, X2 = line.X2, Y2 = line.Y2,
                        Stroke = line.Stroke?.Clone(),
                        StrokeThickness = line.StrokeThickness,
                        Opacity = line.Opacity
                    };
                }
                else if (source is System.Windows.Shapes.Rectangle rect)
                {
                    return new System.Windows.Shapes.Rectangle
                    {
                        Width = rect.Width, Height = rect.Height,
                        Stroke = rect.Stroke?.Clone(), Fill = rect.Fill?.Clone(),
                        StrokeThickness = rect.StrokeThickness,
                        RadiusX = rect.RadiusX, RadiusY = rect.RadiusY,
                        Opacity = rect.Opacity
                    };
                }
                else if (source is System.Windows.Shapes.Ellipse ellipse)
                {
                    return new System.Windows.Shapes.Ellipse
                    {
                        Width = ellipse.Width, Height = ellipse.Height,
                        Stroke = ellipse.Stroke?.Clone(), Fill = ellipse.Fill?.Clone(),
                        StrokeThickness = ellipse.StrokeThickness,
                        Opacity = ellipse.Opacity
                    };
                }
                else if (source is System.Windows.Controls.Image img && img.Source != null)
                {
                    return new System.Windows.Controls.Image
                    {
                        Source = img.Source.Clone(),
                        Width = img.Width, Height = img.Height,
                        Stretch = img.Stretch,
                        Opacity = img.Opacity
                    };
                }
                else if (source is System.Windows.Controls.TextBlock tb)
                {
                    return new System.Windows.Controls.TextBlock
                    {
                        Text = tb.Text,
                        FontSize = tb.FontSize, FontFamily = tb.FontFamily,
                        FontWeight = tb.FontWeight, FontStyle = tb.FontStyle,
                        Foreground = tb.Foreground?.Clone(),
                        Background = tb.Background?.Clone(),
                        Opacity = tb.Opacity
                    };
                }

                // Fallback: use XamlWriter/XamlReader
                string xaml = System.Windows.Markup.XamlWriter.Save(source);
                var cloned = System.Windows.Markup.XamlReader.Parse(xaml) as UIElement;
                return cloned;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"âš ï¸ CloneUIElement failed: {ex.Message}");
                return null;
            }
        }

        /// <summary>
        /// Tạo liên kết — attach URL to selected object
        /// </summary>
        private void OnMoreMenuCreateLink(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🔗 Create Link clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj == null)
            {
                _moreMenu?.Hide();
                return;
            }

            try
            {
                var inputWindow = new Window
                {
                    Title = "Tạo liên kết",
                    Width = 420, Height = 200,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize,
                    Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                stackPanel.Children.Add(new TextBlock
                {
                    Text = "Nhập URL liên kết:",
                    Foreground = Brushes.White, FontSize = 14,
                    Margin = new Thickness(0, 0, 0, 5)
                });

                var txtUrl = new TextBox
                {
                    Text = obj.LinkUrl ?? "https://",
                    FontSize = 14, Padding = new Thickness(8),
                    Margin = new Thickness(0, 0, 0, 10)
                };
                txtUrl.SelectAll();
                stackPanel.Children.Add(txtUrl);

                stackPanel.Children.Add(new TextBlock
                {
                    Text = "💡 Double-click đối tượng để mở liên kết",
                    Foreground = new SolidColorBrush(Color.FromRgb(150, 150, 150)),
                    FontSize = 12, FontStyle = FontStyles.Italic,
                    Margin = new Thickness(0, 0, 0, 12)
                });

                var btnPanel = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right };

                var btnRemove = new Button
                {
                    Content = "Xóa liên kết", Width = 90, Height = 32, Margin = new Thickness(0, 0, 8, 0),
                    Background = new SolidColorBrush(Color.FromRgb(180, 60, 60)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand,
                    Visibility = string.IsNullOrEmpty(obj.LinkUrl) ? Visibility.Collapsed : Visibility.Visible
                };
                var btnOK = new Button
                {
                    Content = "Lưu", Width = 70, Height = 32, Margin = new Thickness(0, 0, 8, 0),
                    Background = new SolidColorBrush(Color.FromRgb(0, 122, 204)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };
                var btnCancel = new Button
                {
                    Content = "Hủy", Width = 70, Height = 32,
                    Background = new SolidColorBrush(Color.FromRgb(100, 100, 100)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };

                btnRemove.Click += (s, args) =>
                {
                    obj.LinkUrl = null;
                    // Remove link badge if exists
                    RemoveLinkBadge(obj);
                    inputWindow.DialogResult = false;
                    System.Diagnostics.Debug.WriteLine("🔗 Link removed");
                };
                btnOK.Click += (s, args) => { inputWindow.DialogResult = true; };
                btnCancel.Click += (s, args) => { inputWindow.DialogResult = false; };

                btnPanel.Children.Add(btnRemove);
                btnPanel.Children.Add(btnOK);
                btnPanel.Children.Add(btnCancel);
                stackPanel.Children.Add(btnPanel);

                inputWindow.Content = stackPanel;

                if (inputWindow.ShowDialog() == true)
                {
                    string url = txtUrl.Text.Trim();
                    if (!string.IsNullOrEmpty(url))
                    {
                        obj.LinkUrl = url;
                        AddLinkBadge(obj);
                        System.Diagnostics.Debug.WriteLine($"🔗 Link set: {url}");
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ CreateLink Error: {ex.Message}");
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Add visual link badge (🔗 icon) to linked object
        /// </summary>
        private void AddLinkBadge(SelectableObject obj)
        {
            if (obj.Element == null) return;
            RemoveLinkBadge(obj); // Remove existing badge first

            var badge = new System.Windows.Controls.TextBlock
            {
                Text = "🔗",
                FontSize = 14,
                Tag = $"LinkBadge_{obj.Id}",
                IsHitTestVisible = false,
                Opacity = 0.8
            };

            double left = obj.Position.X + obj.Size.Width - 18;
            double top = obj.Position.Y - 6;
            Canvas.SetLeft(badge, left);
            Canvas.SetTop(badge, top);
            Panel.SetZIndex(badge, obj.ZIndex + 1);
            MainInteractiveBoard.Children.Add(badge);
        }

        /// <summary>
        /// Remove link badge from object
        /// </summary>
        private void RemoveLinkBadge(SelectableObject obj)
        {
            string badgeTag = $"LinkBadge_{obj.Id}";
            var toRemove = MainInteractiveBoard.Children.OfType<System.Windows.Controls.TextBlock>()
                .FirstOrDefault(tb => tb.Tag?.ToString() == badgeTag);
            if (toRemove != null)
                MainInteractiveBoard.Children.Remove(toRemove);
        }

        /// <summary>
        /// Xuất thành ảnh — render selected object(s) to PNG
        /// </summary>
        private void OnMoreMenuExportImage(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("💾 Export Image clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj?.Element == null)
            {
                _moreMenu?.Hide();
                return;
            }

            try
            {
                var element = obj.Element as FrameworkElement;
                if (element == null) return;

                // Render element to bitmap
                var bounds = obj.Bounds;
                double dpi = 192; // 2x for high quality
                int width = (int)(bounds.Width * dpi / 96);
                int height = (int)(bounds.Height * dpi / 96);
                if (width <= 0 || height <= 0) return;

                var renderBitmap = new System.Windows.Media.Imaging.RenderTargetBitmap(
                    width, height, dpi, dpi, PixelFormats.Pbgra32);

                // Create a visual brush of the element
                var drawingVisual = new DrawingVisual();
                using (var dc = drawingVisual.RenderOpen())
                {
                    var visualBrush = new VisualBrush(element);
                    dc.DrawRectangle(visualBrush, null, new Rect(0, 0, bounds.Width, bounds.Height));
                }
                renderBitmap.Render(drawingVisual);

                // Save dialog
                var saveDialog = new Microsoft.Win32.SaveFileDialog
                {
                    Title = "Xuất thành ảnh",
                    Filter = "PNG Image|*.png|JPEG Image|*.jpg|BMP Image|*.bmp",
                    DefaultExt = ".png",
                    FileName = $"Export_{DateTime.Now:yyyyMMdd_HHmmss}"
                };

                if (saveDialog.ShowDialog() == true)
                {
                    System.Windows.Media.Imaging.BitmapEncoder encoder;
                    string ext = System.IO.Path.GetExtension(saveDialog.FileName).ToLower();
                    switch (ext)
                    {
                        case ".jpg":
                        case ".jpeg":
                            encoder = new System.Windows.Media.Imaging.JpegBitmapEncoder { QualityLevel = 95 };
                            break;
                        case ".bmp":
                            encoder = new System.Windows.Media.Imaging.BmpBitmapEncoder();
                            break;
                        default:
                            encoder = new System.Windows.Media.Imaging.PngBitmapEncoder();
                            break;
                    }
                    encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(renderBitmap));

                    using (var fs = System.IO.File.Create(saveDialog.FileName))
                    {
                        encoder.Save(fs);
                    }

                    System.Diagnostics.Debug.WriteLine($"💾 Exported to: {saveDialog.FileName}");
                    MessageBox.Show($"Đã xuất thành công!\n\n📁 {saveDialog.FileName}",
                        "Xuất ảnh", MessageBoxButton.OK, MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Export Error: {ex.Message}");
                MessageBox.Show($"Lỗi khi xuất ảnh: {ex.Message}", "Lỗi",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Thông tin đối tượng — show properties dialog
        /// </summary>
        private void OnMoreMenuObjectInfo(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("â„¹ï¸ Object Info clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj == null)
            {
                _moreMenu?.Hide();
                return;
            }

            try
            {
                string info = $"📋 THÔNG TIN ĐỐI TƯỢNG\n\n" +
                    $"🔹 Loại: {obj.Type}\n" +
                    $"🔹 Element: {obj.Element?.GetType().Name ?? "null"}\n" +
                    $"🔹 Vị trí: ({obj.Position.X:F0}, {obj.Position.Y:F0})\n" +
                    $"🔹 Kích thước: {obj.Size.Width:F0} × {obj.Size.Height:F0}\n" +
                    $"🔹 Góc xoay: {obj.RotationAngle:F0}°\n" +
                    $"🔹 ZIndex: {obj.ZIndex}\n" +
                    $"🔹 Khóa: {(obj.IsLocked ? "Có" : "Không")}\n" +
                    $"🔹 Nhóm: {(obj.GroupId ?? "Không")}\n" +
                    $"🔹 Liên kết: {(obj.LinkUrl ?? "Không")}\n" +
                    $"🔹 Màu nét: {obj.StrokeColor}\n" +
                    $"🔹 Độ dày nét: {obj.StrokeThickness:F1}\n" +
                    $"🔹 Màu tô: {obj.FillColor}\n" +
                    $"🔹 ID: {obj.Id}";

                MessageBox.Show(info, "Thông tin đối tượng", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ ObjectInfo Error: {ex.Message}");
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Kích thước & vị trí — edit X, Y, Width, Height precisely
        /// </summary>
        private void OnMoreMenuSizePosition(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("📏 Size/Position clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj?.Element == null)
            {
                _moreMenu?.Hide();
                return;
            }

            try
            {
                var inputWindow = new Window
                {
                    Title = "Kích thước & Vị trí",
                    Width = 360, Height = 340,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize,
                    Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                // X position
                stackPanel.Children.Add(new TextBlock { Text = "Vị trí X:", Foreground = Brushes.White, FontSize = 14 });
                var txtX = new TextBox { Text = obj.Position.X.ToString("F0"), FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 8) };
                stackPanel.Children.Add(txtX);

                // Y position
                stackPanel.Children.Add(new TextBlock { Text = "Vị trí Y:", Foreground = Brushes.White, FontSize = 14 });
                var txtY = new TextBox { Text = obj.Position.Y.ToString("F0"), FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 8) };
                stackPanel.Children.Add(txtY);

                // Width
                stackPanel.Children.Add(new TextBlock { Text = "Chiều rộng:", Foreground = Brushes.White, FontSize = 14 });
                var txtW = new TextBox { Text = obj.Size.Width.ToString("F0"), FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 8) };
                stackPanel.Children.Add(txtW);

                // Height
                stackPanel.Children.Add(new TextBlock { Text = "Chiều cao:", Foreground = Brushes.White, FontSize = 14 });
                var txtH = new TextBox { Text = obj.Size.Height.ToString("F0"), FontSize = 14, Padding = new Thickness(5), Margin = new Thickness(0, 4, 0, 12) };
                stackPanel.Children.Add(txtH);

                // Buttons
                var btnPanel = new StackPanel { Orientation = Orientation.Horizontal, HorizontalAlignment = HorizontalAlignment.Right };
                var btnOK = new Button
                {
                    Content = "Áp dụng", Width = 90, Height = 32, Margin = new Thickness(0, 0, 8, 0),
                    Background = new SolidColorBrush(Color.FromRgb(0, 122, 204)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };
                var btnCancel = new Button
                {
                    Content = "Hủy", Width = 70, Height = 32,
                    Background = new SolidColorBrush(Color.FromRgb(100, 100, 100)), Foreground = Brushes.White,
                    BorderThickness = new Thickness(0), Cursor = Cursors.Hand
                };
                btnOK.Click += (s, args) => { inputWindow.DialogResult = true; };
                btnCancel.Click += (s, args) => { inputWindow.DialogResult = false; };
                btnPanel.Children.Add(btnOK);
                btnPanel.Children.Add(btnCancel);
                stackPanel.Children.Add(btnPanel);

                inputWindow.Content = stackPanel;

                if (inputWindow.ShowDialog() == true)
                {
                    if (double.TryParse(txtX.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double newX) &&
                        double.TryParse(txtY.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double newY) &&
                        double.TryParse(txtW.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double newW) && newW > 0 &&
                        double.TryParse(txtH.Text, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out double newH) && newH > 0)
                    {
                        var initialStates = CaptureTargetTransformStates(obj);

                        // Apply position
                        if (_transformService != null)
                        {
                            _transformService.Move(obj, new Point(newX, newY));
                            _transformService.Resize(obj, new Size(newW, newH));
                        }

                        _selectionBox?.UpdatePosition();

                        // ✅ G2.1: Auto-Flip toolbar position
                        var toolbarPos = CalculateOptimalToolbarPosition(obj.Bounds);
                        _contextToolbar?.ShowAt(toolbarPos, obj);

                        var finalStates = CaptureTargetTransformStates(obj);
                        RecordTransformAction(initialStates, finalStates, "Edit Size & Position");

                        System.Diagnostics.Debug.WriteLine(
                            $"📏 Size/Position set & recorded Undo: ({newX:F0},{newY:F0}) {newW:F0}×{newH:F0}");
                    }
                    else
                    {
                        MessageBox.Show("Giá trị không hợp lệ. Kích thước phải > 0.", "Lỗi",
                            MessageBoxButton.OK, MessageBoxImage.Warning);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ SizePosition Error: {ex.Message}");
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Kiểu đường nét — choose stroke dash style
        /// </summary>
        private void OnMoreMenuStrokeStyle(object? sender, EventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("🎨 Stroke Style clicked");
            var obj = _selectionManager?.SelectedObject;
            if (obj?.Element == null)
            {
                _moreMenu?.Hide();
                return;
            }

            try
            {
                var styleWindow = new Window
                {
                    Title = "Kiểu đường nét",
                    Width = 320, Height = 340,
                    WindowStartupLocation = WindowStartupLocation.CenterScreen,
                    ResizeMode = System.Windows.ResizeMode.NoResize,
                    Background = new SolidColorBrush(Color.FromRgb(45, 45, 48))
                };

                var stackPanel = new StackPanel { Margin = new Thickness(20) };

                stackPanel.Children.Add(new TextBlock
                {
                    Text = "Chọn kiểu đường nét:",
                    Foreground = Brushes.White, FontSize = 14,
                    Margin = new Thickness(0, 0, 0, 12)
                });

                string[] styleNames = { "Nét liền", "Nét đứt", "Nét chấm", "Nét gạch-chấm", "Nét gạch-chấm-chấm" };
                DoubleCollection?[] dashArrays = {
                    null,                               // Solid
                    new DoubleCollection { 4, 2 },       // Dashed
                    new DoubleCollection { 1, 2 },       // Dotted
                    new DoubleCollection { 4, 2, 1, 2 }, // DashDot
                    new DoubleCollection { 4, 2, 1, 2, 1, 2 } // DashDotDot
                };
                string[] styleIcons = { "━━━━━━", "━ ━ ━ ━", "• • • • • •", "━ • ━ • ━", "━ • • ━ • •" };

                for (int i = 0; i < styleNames.Length; i++)
                {
                    int index = i; // Capture for closure
                    var btn = new Button
                    {
                        Height = 44,
                        Background = Brushes.Transparent,
                        BorderThickness = new Thickness(0),
                        Cursor = Cursors.Hand,
                        HorizontalContentAlignment = HorizontalAlignment.Left,
                        Padding = new Thickness(12, 0, 12, 0)
                    };

                    var content = new StackPanel { Orientation = Orientation.Horizontal };
                    content.Children.Add(new TextBlock
                    {
                        Text = styleIcons[i],
                        FontSize = 16, Width = 120,
                        Foreground = Brushes.White,
                        VerticalAlignment = VerticalAlignment.Center
                    });
                    content.Children.Add(new TextBlock
                    {
                        Text = styleNames[i],
                        FontSize = 14,
                        Foreground = Brushes.White,
                        VerticalAlignment = VerticalAlignment.Center,
                        Margin = new Thickness(8, 0, 0, 0)
                    });
                    btn.Content = content;

                    btn.Click += (s, args) =>
                    {
                        ApplyStrokeDashStyle(obj, dashArrays[index]);
                        styleWindow.Close();
                        System.Diagnostics.Debug.WriteLine($"🎨 Applied dash style: {styleNames[index]}");
                    };

                    // Hover effect
                    btn.MouseEnter += (s, args) => btn.Background = new SolidColorBrush(Color.FromRgb(60, 60, 65));
                    btn.MouseLeave += (s, args) => btn.Background = Brushes.Transparent;

                    stackPanel.Children.Add(btn);
                }

                styleWindow.Content = stackPanel;
                styleWindow.ShowDialog();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ StrokeStyle Error: {ex.Message}");
            }
            finally
            {
                _moreMenu?.Hide();
            }
        }

        /// <summary>
        /// Apply dash style to a shape / stroke element
        /// </summary>
        private void ApplyStrokeDashStyle(SelectableObject obj, DoubleCollection? dashArray)
        {
            if (obj.Element is System.Windows.Shapes.Shape shape)
            {
                shape.StrokeDashArray = dashArray ?? new DoubleCollection();
                RecordModifyAction(obj.Element, "StrokeStyle",
                    dashArray == null ? "Solid" : string.Join(",", dashArray), "Change stroke style");
            }
        }

        /// <summary>
        /// Sprint 5 Module 5.3: Align selected objects
        /// </summary>
        private void AlignObjects(string alignment)
        {
            System.Diagnostics.Debug.WriteLine($"📐 Align {alignment} clicked");

            try
            {
                var selectedObjects = _selectionManager?.SelectedObjects;
                
                if (selectedObjects == null || selectedObjects.Count < 2)
                {
                    MessageBox.Show(
                        "Please select at least 2 objects to align.",
                        "Align Objects",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                    return;
                }

                double referenceValue = 0;

                switch (alignment.ToLower())
                {
                    case "left":
                        referenceValue = selectedObjects.Min(o => o.Position.X);
                        foreach (var obj in selectedObjects)
                        {
                            Canvas.SetLeft(obj.Element, referenceValue);
                            obj.Position = new Point(referenceValue, obj.Position.Y);
                            obj.UpdateBounds();
                        }
                        break;

                    case "center":
                        double minX = selectedObjects.Min(o => o.Position.X);
                        double maxX = selectedObjects.Max(o => o.Position.X + o.Size.Width);
                        referenceValue = (minX + maxX) / 2;
                        foreach (var obj in selectedObjects)
                        {
                            double newX = referenceValue - (obj.Size.Width / 2);
                            Canvas.SetLeft(obj.Element, newX);
                            obj.Position = new Point(newX, obj.Position.Y);
                            obj.UpdateBounds();
                        }
                        break;

                    case "right":
                        referenceValue = selectedObjects.Max(o => o.Position.X + o.Size.Width);
                        foreach (var obj in selectedObjects)
                        {
                            double newX = referenceValue - obj.Size.Width;
                            Canvas.SetLeft(obj.Element, newX);
                            obj.Position = new Point(newX, obj.Position.Y);
                            obj.UpdateBounds();
                        }
                        break;

                    case "top":
                        referenceValue = selectedObjects.Min(o => o.Position.Y);
                        foreach (var obj in selectedObjects)
                        {
                            Canvas.SetTop(obj.Element, referenceValue);
                            obj.Position = new Point(obj.Position.X, referenceValue);
                            obj.UpdateBounds();
                        }
                        break;

                    case "middle":
                        double minY = selectedObjects.Min(o => o.Position.Y);
                        double maxY = selectedObjects.Max(o => o.Position.Y + o.Size.Height);
                        referenceValue = (minY + maxY) / 2;
                        foreach (var obj in selectedObjects)
                        {
                            double newY = referenceValue - (obj.Size.Height / 2);
                            Canvas.SetTop(obj.Element, newY);
                            obj.Position = new Point(obj.Position.X, newY);
                            obj.UpdateBounds();
                        }
                        break;

                    case "bottom":
                        referenceValue = selectedObjects.Max(o => o.Position.Y + o.Size.Height);
                        foreach (var obj in selectedObjects)
                        {
                            double newY = referenceValue - obj.Size.Height;
                            Canvas.SetTop(obj.Element, newY);
                            obj.Position = new Point(obj.Position.X, newY);
                            obj.UpdateBounds();
                        }
                        break;
                }

                System.Diagnostics.Debug.WriteLine($"📐 Aligned {selectedObjects.Count} objects to {alignment}");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Align Error: {ex.Message}");
                MessageBox.Show($"Failed to align objects: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// Sprint 5 Module 5.4: Apply same property to all selected objects
        /// </summary>
        private void ApplyToAllSelected(string property, object value)
        {
            System.Diagnostics.Debug.WriteLine($"🎨 Apply {property} to all selected");

            try
            {
                var selectedObjects = _selectionManager?.SelectedObjects;
                
                if (selectedObjects == null || selectedObjects.Count == 0)
                {
                    MessageBox.Show(
                        "Please select objects first.",
                        "Batch Operation",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                    return;
                }

                int appliedCount = 0;

                foreach (var obj in selectedObjects)
                {
                    if (obj.Element == null) continue;

                    switch (property.ToLower())
                    {
                        case "color":
                            if (value is Color color)
                            {
                                obj.StrokeColor = color;
                                
                                if (obj.Element is System.Windows.Shapes.Shape shape)
                                {
                                    shape.Stroke = new SolidColorBrush(color);
                                    appliedCount++;
                                }
                                else if (obj.Element is Border border)
                                {
                                    border.BorderBrush = new SolidColorBrush(color);
                                    appliedCount++;
                                }
                            }
                            break;

                        case "thickness":
                            if (value is double thickness)
                            {
                                obj.StrokeThickness = thickness;
                                
                                if (obj.Element is System.Windows.Shapes.Shape shape)
                                {
                                    shape.StrokeThickness = thickness;
                                    appliedCount++;
                                }
                                else if (obj.Element is Border border)
                                {
                                    border.BorderThickness = new Thickness(thickness);
                                    appliedCount++;
                                }
                                else if (obj.Element is System.Windows.Shapes.Polyline polyline)
                                {
                                    polyline.StrokeThickness = thickness;
                                    appliedCount++;
                                }
                            }
                            break;

                        case "rotation":
                            if (value is double angle)
                            {
                                obj.RotationAngle = angle;
                                
                                var rotateTransform = new RotateTransform(angle, 
                                    obj.Size.Width / 2, obj.Size.Height / 2);
                                obj.Element.RenderTransform = rotateTransform;
                                appliedCount++;
                            }
                            break;
                    }
                }

                System.Diagnostics.Debug.WriteLine($"🎨 Applied {property} to {appliedCount}/{selectedObjects.Count} objects");
                
                if (appliedCount > 0)
                {
                    MessageBox.Show(
                        $"Successfully applied {property} to {appliedCount} object(s)!",
                        "Batch Operation Complete",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information
                    );
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Batch Operation Error: {ex.Message}");
                MessageBox.Show($"Failed to apply batch operation: {ex.Message}", "Error", 
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        #endregion
    }
}