using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.BoardManagement.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 21747-22679
// #region Board Management, ScreenCurtain, Pan, Pointer, MultiUser
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Board Management - Background

        /// <summary>
        /// Apply background to MainInteractiveBoard (âœ¨ Updated to support color + pattern combination + dynamic spacing)
        /// </summary>
        public void ApplyCanvasBackground(string? color, string? pattern, int lineSpacing = 40, int lineOpacity = 10)
        {
            try
            {
                // Store line spacing and opacity for pattern creation
                _currentLineSpacing = lineSpacing;
                _currentLineOpacity = lineOpacity;
                
                // âœ¨ Remove old background rectangles if any
                var oldBgRects = MainInteractiveBoard.Children.OfType<Rectangle>()
                    .Where(r => r.Tag?.ToString() == "BackgroundLayer")
                    .ToList();
                foreach (var rect in oldBgRects)
                {
                    MainInteractiveBoard.Children.Remove(rect);
                }
                
                if (!string.IsNullOrEmpty(pattern))
                {
                    // Create background color rectangle with dynamic bindings
                    var bgRect = new Rectangle
                    {
                        Tag = "BackgroundLayer",
                        // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                        IsHitTestVisible = false
                    };
                    bgRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                    bgRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });
                    
                    if (!string.IsNullOrEmpty(color))
                    {
                        try
                        {
                            bgRect.Fill = new SolidColorBrush(
                                (Color)ColorConverter.ConvertFromString(color)
                            );
                        }
                        catch
                        {
                            bgRect.Fill = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                        }
                    }
                    else
                    {
                        bgRect.Fill = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                    }
                    
                    // Create pattern rectangle with dynamic bindings
                    var patternRect = new Rectangle
                    {
                        Fill = CreatePatternBrushByName(pattern),
                        Tag = "BackgroundLayer",
                        // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                        IsHitTestVisible = false
                    };
                    patternRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                    patternRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });
                    
                    // Add to canvas at index 0 (bottom layer)
                    MainInteractiveBoard.Children.Insert(0, bgRect);
                    MainInteractiveBoard.Children.Insert(1, patternRect);
                    // ✅ QC_4.2_GRID_PROTECT (G-2): Pin tại (0,0) tránh NaN position khi layout thay đổi
                    Canvas.SetLeft(bgRect, 0);
                    Canvas.SetTop(bgRect, 0);
                    Canvas.SetLeft(patternRect, 0);
                    Canvas.SetTop(patternRect, 0);
                    Panel.SetZIndex(bgRect, ZIndexConstants.Background);
                    Panel.SetZIndex(patternRect, ZIndexConstants.GridOverlay);
                    
                    // Set canvas background to transparent
                    MainInteractiveBoard.Background = Brushes.Transparent;
                }
                else if (!string.IsNullOrEmpty(color))
                {
                    // Only color, no pattern - use Canvas.Background
                    MainInteractiveBoard.Background = new SolidColorBrush(
                        (Color)ColorConverter.ConvertFromString(color)
                    );
                }
                else
                {
                    // Default chalkboard green
                    MainInteractiveBoard.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi áp dụng nền: {ex.Message}", "Lỗi", 
                              MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// âœ¨ Apply default background on startup
        /// </summary>
        private void ApplyDefaultBackground()
        {
            try
            {
                // Load default values from Settings
                string defaultColor = QASmartClass.Properties.Settings.Default.DefaultBackgroundColor;
                string defaultPattern = QASmartClass.Properties.Settings.Default.DefaultBackgroundPattern;
                
                System.Diagnostics.Debug.WriteLine($"🔍 Loading defaults from Settings: Color='{defaultColor}', Pattern='{defaultPattern}'");
                
                // âœ¨ TEMPORARY: Hard-code for testing
                if (string.IsNullOrEmpty(defaultColor))
                {
                    defaultColor = "#3D6D64"; // Traditional chalkboard green
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ Color was empty, using hard-coded: {defaultColor}");
                }
                if (string.IsNullOrEmpty(defaultPattern))
                {
                    defaultPattern = "Grid";
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ Pattern was empty, using hard-coded: {defaultPattern}");
                }
                
                // Apply if valid
                if (!string.IsNullOrEmpty(defaultColor) || !string.IsNullOrEmpty(defaultPattern))
                {
                    System.Diagnostics.Debug.WriteLine($"📝 Applying background: Color={defaultColor}, Pattern={defaultPattern}, Spacing=40px");
                    ApplyCanvasBackground(defaultColor, defaultPattern, 40); // Default spacing 40px
                    System.Diagnostics.Debug.WriteLine($"✅ Applied default background successfully");
                }
                else
                {
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ No default background to apply (both empty)");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Failed to apply default background: {ex.Message}");
                System.Diagnostics.Debug.WriteLine($"Stack trace: {ex.StackTrace}");
                // Fallback to chalkboard green if error
                MainInteractiveBoard.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
            }
        }

        /// <summary>
        /// âœ¨ NEW: Apply custom background image to MainInteractiveBoard
        /// </summary>
        public void ApplyCanvasBackgroundImage(System.Windows.Media.Imaging.BitmapImage? backgroundImage, string? pattern = null)
        {
            try
            {
                // Remove old background rectangles
                var oldBgRects = MainInteractiveBoard.Children.OfType<Rectangle>()
                    .Where(r => r.Tag?.ToString() == "BackgroundLayer")
                    .ToList();
                foreach (var rect in oldBgRects)
                {
                    MainInteractiveBoard.Children.Remove(rect);
                }

                if (backgroundImage != null)
                {
                    // Create image background rectangle
                    var imageBrush = new ImageBrush
                    {
                        ImageSource = backgroundImage,
                        Stretch = Stretch.UniformToFill
                    };

                    var bgRect = new Rectangle
                    {
                        Fill = imageBrush,
                        Tag = "BackgroundLayer",
                        // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                        IsHitTestVisible = false
                    };
                    bgRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                    bgRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });

                    // Add to canvas at index 0 (bottom layer)
                    MainInteractiveBoard.Children.Insert(0, bgRect);
                    // ✅ QC_4.2_GRID_PROTECT (G-2): Pin tại (0,0) tránh NaN position
                    Canvas.SetLeft(bgRect, 0);
                    Canvas.SetTop(bgRect, 0);
                    Panel.SetZIndex(bgRect, ZIndexConstants.Background);

                    // Optionally add pattern overlay
                    if (!string.IsNullOrEmpty(pattern))
                    {
                        var patternRect = new Rectangle
                        {
                            Fill = CreatePatternBrushByName(pattern),
                            Tag = "BackgroundLayer",
                            // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                            IsHitTestVisible = false
                        };
                        patternRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                        patternRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });
                        MainInteractiveBoard.Children.Insert(1, patternRect);
                        // ✅ QC_4.2_GRID_PROTECT (G-2): Pin tại (0,0) tránh NaN position
                        Canvas.SetLeft(patternRect, 0);
                        Canvas.SetTop(patternRect, 0);
                        Panel.SetZIndex(patternRect, ZIndexConstants.GridOverlay);
                    }

                    // Set canvas background to transparent
                    MainInteractiveBoard.Background = Brushes.Transparent;
                }
                else
                {
                    // No image, fallback to chalkboard green
                    MainInteractiveBoard.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi áp dụng ảnh nền: {ex.Message}", "Lỗi",
                              MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// âœ¨ Create combined brush with background color + pattern overlay
        /// </summary>
        private Brush CreateCombinedBrush(string? backgroundColor, string pattern)
        {
            // Get the pattern brush first to determine viewport size
            var patternBrush = CreatePatternBrushByName(pattern);
            
            // Determine viewport size from pattern
            Rect viewport = new Rect(0, 0, 20, 20); // Default
            if (patternBrush is DrawingBrush pb)
            {
                viewport = pb.Viewport;
            }
            
            // Create a new DrawingBrush for the combined result
            var combinedBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = viewport,
                ViewportUnits = BrushMappingMode.Absolute
            };
            
            var drawingGroup = new DrawingGroup();
            
            // Layer 1: Background color (full tile)
            if (!string.IsNullOrEmpty(backgroundColor))
            {
                try
                {
                    var color = (Color)ColorConverter.ConvertFromString(backgroundColor);
                    drawingGroup.Children.Add(new GeometryDrawing
                    {
                        Brush = new SolidColorBrush(color),
                        Geometry = new RectangleGeometry(viewport)
                    });
                }
                catch
                {
                    // Fallback to white if color parsing fails
                    drawingGroup.Children.Add(new GeometryDrawing
                    {
                        Brush = Brushes.White,
                        Geometry = new RectangleGeometry(viewport)
                    });
                }
            }
            
            // Layer 2: Pattern overlay
            if (patternBrush is DrawingBrush patternDb && patternDb.Drawing is DrawingGroup patternGroup)
            {
                foreach (var child in patternGroup.Children)
                {
                    drawingGroup.Children.Add(child);
                }
            }
            
            combinedBrush.Drawing = drawingGroup;
            return combinedBrush;
        }

        /// <summary>
        /// ✨ Refactor: Tách logic tạo pattern thành method riêng
        /// </summary>
        private Brush? CreatePatternBrushByName(string pattern)
        {
            switch (pattern)
            {
                case "Grid": return CreateGridPattern();
                case "Dots": return CreateDotsPattern();
                case "Lines": return CreateLinesPattern();
                case "MusicStaff": return CreateMusicStaffPattern();
                default: return null;
            }
        }

        private Brush CreateGridPattern()
        {
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, _currentLineSpacing, _currentLineSpacing), // Dynamic spacing
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // Vertical line
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                Geometry = new LineGeometry(new Point(0, 0), new Point(0, _currentLineSpacing))
            });
            
            // Horizontal line
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                Geometry = new LineGeometry(new Point(0, 0), new Point(_currentLineSpacing, 0))
            });

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        private Brush CreateDotsPattern()
        {
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 30, 30),
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Dot
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Brush = new SolidColorBrush(Color.FromArgb(40, 0, 0, 0)),
                Geometry = new EllipseGeometry(new Point(15, 15), 0.5, 0.5)
            });

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        /// <summary>
        /// Create horizontal lines pattern (with dynamic spacing)
        /// </summary>
        private Brush CreateLinesPattern()
        {
            // Create drawing brush with dynamic spacing
            var brush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 1, _currentLineSpacing), // Dynamic spacing
                ViewportUnits = BrushMappingMode.Absolute,
                Stretch = Stretch.None
            };

            // Create drawing group
            var group = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // Draw a single horizontal line at the top of the tile
            var linePen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1);
            linePen.Freeze(); // Freeze for performance
            
            group.Children.Add(new GeometryDrawing
            {
                Pen = linePen,
                Geometry = new LineGeometry(new Point(0, 0), new Point(1, 0))
            });

            brush.Drawing = group;
            brush.Freeze(); // Freeze for performance
            
            return brush;
        }

        private Brush CreateMusicStaffPattern()
        {
            // Calculate total height for 5 lines with dynamic spacing
            int totalHeight = _currentLineSpacing * 4; // 4 gaps between 5 lines
            
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 100, totalHeight),
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // 5 lines for music staff with dynamic spacing
            for (int i = 0; i < 5; i++)
            {
                drawingGroup.Children.Add(new GeometryDrawing
                {
                    Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                    Geometry = new LineGeometry(new Point(0, i * _currentLineSpacing), new Point(100, i * _currentLineSpacing))
                });
            }

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        #endregion

        #region Screen Curtain (Màn che bảng)

        private Form2_18_ScreenCurtain _screenCurtain;

        /// <summary>
        /// Toggle Screen Curtain (Màn che bảng)
        /// </summary>
        private void btn9_5_ScreenCurtain_Click(object sender, RoutedEventArgs e)
        {
            if (_screenCurtain == null || !_screenCurtain.IsVisible)
            {
                // ✅ PHASE 2: Deactivate tools and close submenus before showing curtain
                DeactivateAllTools();
                CloseAllSubmenus();
                
                // Show curtain
                _screenCurtain = new Form2_18_ScreenCurtain();
                _screenCurtain.Closed += (s, args) =>
                {
                    _screenCurtain = null;
                    // Reset button appearance
                    btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(241, 242, 246)); // #F1F2F6
                };
                _screenCurtain.Show();
                
                // Highlight button when active
                btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(103, 126, 234)); // #667EEA
            }
            else
            {
                // Close curtain
                _screenCurtain.Close();
                _screenCurtain = null;
                btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(241, 242, 246)); // #F1F2F6
            }
        }

        #endregion

        #region Pan Mode (Drag to Scroll)

        private bool _isPanModeActive = false;
        private Point _scrollPanStartPoint;
        private double _scrollPanStartHorizontalOffset;
        private double _scrollPanStartVerticalOffset;

        /// <summary>
        /// Enable pan mode - allows dragging to scroll the canvas
        /// </summary>
        public void EnablePanMode()
        {
            if (_isPanModeActive)
            {
                // Disable pan mode
                DisablePanMode();
                return;
            }

            // QC_4.2_PAN_MODE_CLEANUP: Tắt hoàn toàn chế độ Bút vẽ và dọn dẹp stroke khi bắt đầu Pan Mode
            _drawingEnabled = false;
            _isDrawing = false;
            _currentStroke = null;
            _eraserEnabled = false;

            _isPanModeActive = true;

            // Change cursor to hand
            MainScrollViewer.Cursor = Cursors.Hand;
            MainInteractiveBoard.Cursor = Cursors.Hand;

            // Subscribe to mouse events for dragging
            MainScrollViewer.PreviewMouseLeftButtonDown += ScrollViewer_PreviewMouseLeftButtonDown;
            MainScrollViewer.PreviewMouseMove += ScrollViewer_PreviewMouseMove;
            MainScrollViewer.PreviewMouseLeftButtonUp += ScrollViewer_PreviewMouseLeftButtonUp;

            // Subscribe to ESC key to exit pan mode
            this.PreviewKeyDown += PanMode_PreviewKeyDown;

            System.Diagnostics.Debug.WriteLine("✅ Pan mode enabled - drag to scroll, ESC to exit");
        }

        private void DisablePanMode()
        {
            _isPanModeActive = false;

            // Release capture if held
            if (MainScrollViewer.IsMouseCaptured)
                MainScrollViewer.ReleaseMouseCapture();
            if (MainInteractiveBoard.IsMouseCaptured)
                MainInteractiveBoard.ReleaseMouseCapture();

            // Restore cursor based on current tool mode
            Cursor defaultCursor = _drawingEnabled ? Cursors.Pen : Cursors.Arrow;
            MainScrollViewer.Cursor = defaultCursor;
            MainInteractiveBoard.Cursor = defaultCursor;

            // Unsubscribe from events
            MainScrollViewer.PreviewMouseLeftButtonDown -= ScrollViewer_PreviewMouseLeftButtonDown;
            MainScrollViewer.PreviewMouseMove -= ScrollViewer_PreviewMouseMove;
            MainScrollViewer.PreviewMouseLeftButtonUp -= ScrollViewer_PreviewMouseLeftButtonUp;
            this.PreviewKeyDown -= PanMode_PreviewKeyDown;

            System.Diagnostics.Debug.WriteLine("✅ Pan mode disabled - restored cursor & released mouse capture");
        }

        #region Pointer Mode (Chỉ Bảng) Implementation
        public bool _isPointerModeActive = false;
        private Grid? _pointerGraphicContainer;

        /// <summary>
        /// Enable Pointer Tool (Chỉ Bảng) - High-visibility animated laser pointer arrow for teaching
        /// </summary>
        public void EnablePointerMode()
        {
            if (_isPointerModeActive)
            {
                DisablePointerMode();
                return;
            }

            // Mode Guard: Turn off all other active tools
            if (_isPanModeActive) DisablePanMode();
            if (_eraserEnabled) DisableEraserMode();

            if (MainScrollViewer.IsMouseCaptured) MainScrollViewer.ReleaseMouseCapture();
            if (MainInteractiveBoard.IsMouseCaptured) MainInteractiveBoard.ReleaseMouseCapture();

            _isDrawing = false;
            _currentStroke = null;

            _drawingEnabled = false;
            _eraserEnabled = false;
            _shapeDrawingEnabled = false;
            _textToolEnabled = false;
            _selectionToolEnabled = false;
            _objectSelectionMode = false;
            _isPointerModeActive = true;

            _selectionManager?.DeselectAll();

            MainInteractiveBoard.Cursor = Cursors.None;
            MainScrollViewer.Cursor = Cursors.None;

            if (_touchHandler != null)
            {
                _touchHandler.SetToolMode(QASmartTouch.Handlers.TouchToolMode.Pointer);
                _touchHandler.SetUpdatePointerAction(UpdatePointerPosition);
            }

            CreatePointerGraphic();
            ShowSmartStatusBadge("📌 Đang bật công cụ Chỉ bảng - Chạm hoặc di chuyển để chỉ điểm");
            System.Diagnostics.Debug.WriteLine("📌 Pointer mode enabled");
        }

        /// <summary>
        /// Disable Pointer Tool (Chỉ Bảng)
        /// </summary>
        public void DisablePointerMode()
        {
            _isPointerModeActive = false;
            RemovePointerGraphic();
            HideSmartStatusBadge();

            MainInteractiveBoard.Cursor = Cursors.Arrow;
            MainScrollViewer.Cursor = Cursors.Arrow;
            System.Diagnostics.Debug.WriteLine("📌 Pointer mode disabled");
        }

        private void CreatePointerGraphic()
        {
            RemovePointerGraphic();

            _pointerGraphicContainer = new Grid
            {
                Width = 72,
                Height = 72,
                IsHitTestVisible = false,
                Tag = "PointerGraphicOverlay"
            };

            // 1. Glowing Laser Pulsing Outer Ring
            var laserPulse = new System.Windows.Shapes.Ellipse
            {
                Width = 28,
                Height = 28,
                Fill = new SolidColorBrush(Color.FromArgb(120, 255, 0, 80)),
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top,
                Margin = new Thickness(-14, -14, 0, 0)
            };

            // 2. Center Laser Red Dot
            var laserDot = new System.Windows.Shapes.Ellipse
            {
                Width = 14,
                Height = 14,
                Fill = new SolidColorBrush(Color.FromRgb(255, 30, 60)),
                Stroke = new SolidColorBrush(Colors.White),
                StrokeThickness = 2,
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top,
                Margin = new Thickness(-7, -7, 0, 0)
            };

            // 3. Large High-Contrast Pointer Arrow (Mũi tên Đỏ + Viền Vàng + Bóng Đổ 3D)
            var pointerArrow = new System.Windows.Shapes.Polygon
            {
                Points = new PointCollection
                {
                    new Point(0, 0),       // Arrow Tip
                    new Point(0, 48),      // Bottom Left
                    new Point(14, 34),     // Inner notch
                    new Point(28, 56),     // Tail tip
                    new Point(38, 50),     // Tail right
                    new Point(24, 28),     // Tail inner
                    new Point(42, 28)      // Right tip
                },
                Fill = new LinearGradientBrush(
                    Color.FromRgb(255, 45, 85),
                    Color.FromRgb(220, 0, 50),
                    90),
                Stroke = new SolidColorBrush(Color.FromRgb(255, 215, 0)),
                StrokeThickness = 3.5,
                StrokeLineJoin = PenLineJoin.Round,
                Effect = new System.Windows.Media.Effects.DropShadowEffect
                {
                    Color = Colors.Black,
                    BlurRadius = 10,
                    ShadowDepth = 4,
                    Opacity = 0.6
                }
            };

            _pointerGraphicContainer.Children.Add(laserPulse);
            _pointerGraphicContainer.Children.Add(pointerArrow);
            _pointerGraphicContainer.Children.Add(laserDot);

            Canvas.SetLeft(_pointerGraphicContainer, MainInteractiveBoard.ActualWidth / 2);
            Canvas.SetTop(_pointerGraphicContainer, MainInteractiveBoard.ActualHeight / 2);
            Panel.SetZIndex(_pointerGraphicContainer, 999999);

            MainInteractiveBoard.Children.Add(_pointerGraphicContainer);
        }

        public void UpdatePointerPosition(Point pos)
        {
            if (_pointerGraphicContainer == null || !_isPointerModeActive) return;

            Canvas.SetLeft(_pointerGraphicContainer, pos.X);
            Canvas.SetTop(_pointerGraphicContainer, pos.Y);
        }

        private void RemovePointerGraphic()
        {
            if (_pointerGraphicContainer != null)
            {
                if (MainInteractiveBoard.Children.Contains(_pointerGraphicContainer))
                {
                    MainInteractiveBoard.Children.Remove(_pointerGraphicContainer);
                }
                _pointerGraphicContainer = null;
            }
        }
        #endregion

        private void ScrollViewer_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (!_isPanModeActive || _drawingEnabled)
            {
                if (MainScrollViewer.IsMouseCaptured)
                    MainScrollViewer.ReleaseMouseCapture();
                return;
            }

            // Ensure no drawing occurs during pan drag
            _isDrawing = false;
            _currentStroke = null;

            _scrollPanStartPoint = e.GetPosition(MainScrollViewer);
            _scrollPanStartHorizontalOffset = MainScrollViewer.HorizontalOffset;
            _scrollPanStartVerticalOffset = MainScrollViewer.VerticalOffset;

            MainScrollViewer.CaptureMouse();
            MainScrollViewer.Cursor = Cursors.ScrollAll; // Change to move cursor while dragging
        }

        private void ScrollViewer_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            // QC_4.2_PREVENT_AUTO_SCROLL: Tuyệt đối không cuộn màn hình nếu đang vẽ nét bút hoặc ngắt Pan Mode
            if (!_isPanModeActive || _drawingEnabled || _isDrawing || !MainScrollViewer.IsMouseCaptured)
            {
                return;
            }

            Point currentPoint = e.GetPosition(MainScrollViewer);
            double deltaX = _scrollPanStartPoint.X - currentPoint.X;
            double deltaY = _scrollPanStartPoint.Y - currentPoint.Y;

            MainScrollViewer.ScrollToHorizontalOffset(_scrollPanStartHorizontalOffset + deltaX);
            MainScrollViewer.ScrollToVerticalOffset(_scrollPanStartVerticalOffset + deltaY);
        }

        private void ScrollViewer_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            if (MainScrollViewer.IsMouseCaptured)
            {
                MainScrollViewer.ReleaseMouseCapture();
            }

            if (!_isPanModeActive) return;

            MainScrollViewer.Cursor = Cursors.Hand; // Restore hand cursor
        }

        private void PanMode_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Escape && _isPanModeActive)
            {
                DisablePanMode();
                e.Handled = true;
            }
        }

        #endregion

        #region Multi-User Mode (Split Screen for 2 Students)

        private bool _isMultiUserModeActive = false;
        private bool _isCustomColorSelected = false; // Flag to allow custom color override
        private SplitMode _currentSplitMode;
        private StudentProfile? _student1;
        private StudentProfile? _student2;
        private Border? _splitLine;
        private TextBlock? _student1Label;
        private TextBlock? _student2Label;
        private bool _zoneIsolationEnabled = false;
        private bool _showSplitLine = true;

        /// <summary>
        /// Enable multi-user mode with split screen
        /// </summary>
        public void EnableMultiUserMode(SplitMode splitMode, StudentProfile student1, StudentProfile student2, bool zoneIsolation = false, bool showSplitLine = true)
        {
            _isMultiUserModeActive = true;
            _isCustomColorSelected = false; // Reset to use student team colors initially
            _currentSplitMode = splitMode;
            _student1 = student1;
            _student2 = student2;
            _zoneIsolationEnabled = zoneIsolation;
            _showSplitLine = showSplitLine;

            // Create visual split line
            CreateSplitLine();

            // Create student labels
            CreateStudentLabels();

            System.Diagnostics.Debug.WriteLine($"✅ Multi-user mode enabled - {splitMode}, {student1.Name} vs {student2.Name}, Isolation={zoneIsolation}, ShowLine={showSplitLine}");
        }

        /// <summary>
        /// Disable multi-user mode
        /// </summary>
        public void DisableMultiUserMode()
        {
            _isMultiUserModeActive = false;
            _isCustomColorSelected = false;
            _student1 = null;
            _student2 = null;

            // Remove split line
            if (_splitLine != null && MainInteractiveBoard.Children.Contains(_splitLine))
            {
                MainInteractiveBoard.Children.Remove(_splitLine);
                _splitLine = null;
            }

            // Remove labels
            if (_student1Label != null && MainInteractiveBoard.Children.Contains(_student1Label))
            {
                MainInteractiveBoard.Children.Remove(_student1Label);
                _student1Label = null;
            }

            if (_student2Label != null && MainInteractiveBoard.Children.Contains(_student2Label))
            {
                MainInteractiveBoard.Children.Remove(_student2Label);
                _student2Label = null;
            }

            System.Diagnostics.Debug.WriteLine("✅ Multi-user mode disabled");
        }

        private void CreateSplitLine()
        {
            // Remove old split line if exists
            if (_splitLine != null && MainInteractiveBoard.Children.Contains(_splitLine))
            {
                MainInteractiveBoard.Children.Remove(_splitLine);
            }

            _splitLine = new Border
            {
                Tag = "MultiUserSplitLine",
                Background = new SolidColorBrush(Color.FromArgb(100, 0, 0, 0)), // Semi-transparent
                BorderBrush = new SolidColorBrush(Colors.Gray),
                BorderThickness = new Thickness(2),
                Visibility = _showSplitLine ? Visibility.Visible : Visibility.Collapsed
            };

            if (_currentSplitMode == SplitMode.Vertical)
            {
                // Vertical split line (middle of canvas)
                _splitLine.Width = 4;
                _splitLine.Height = MainInteractiveBoard.ActualHeight;
                Canvas.SetLeft(_splitLine, MainInteractiveBoard.ActualWidth / 2 - 2);
                Canvas.SetTop(_splitLine, 0);
            }
            else
            {
                // Horizontal split line (middle of canvas)
                _splitLine.Width = MainInteractiveBoard.ActualWidth;
                _splitLine.Height = 4;
                Canvas.SetLeft(_splitLine, 0);
                Canvas.SetTop(_splitLine, MainInteractiveBoard.ActualHeight / 2 - 2);
            }

            MainInteractiveBoard.Children.Add(_splitLine);
        }

        private void CreateStudentLabels()
        {
            // Remove old labels
            if (_student1Label != null && MainInteractiveBoard.Children.Contains(_student1Label))
            {
                MainInteractiveBoard.Children.Remove(_student1Label);
            }
            if (_student2Label != null && MainInteractiveBoard.Children.Contains(_student2Label))
            {
                MainInteractiveBoard.Children.Remove(_student2Label);
            }

            if (_student1 == null || _student2 == null) return;

            // Create student 1 label
            _student1Label = new TextBlock
            {
                Tag = "MultiUserLabel",
                Text = _student1.Name,
                FontSize = 24,
                FontWeight = FontWeights.Bold,
                Foreground = _student1.GetBrush(),
                Background = new SolidColorBrush(Color.FromArgb(200, 255, 255, 255)),
                Padding = new Thickness(15, 8, 15, 8)
            };

            // Create student 2 label
            _student2Label = new TextBlock
            {
                Tag = "MultiUserLabel",
                Text = _student2.Name,
                FontSize = 24,
                FontWeight = FontWeights.Bold,
                Foreground = _student2.GetBrush(),
                Background = new SolidColorBrush(Color.FromArgb(200, 255, 255, 255)),
                Padding = new Thickness(15, 8, 15, 8)
            };

            if (_currentSplitMode == SplitMode.Vertical)
            {
                // Position labels for vertical split
                Canvas.SetLeft(_student1Label, 20);
                Canvas.SetTop(_student1Label, 20);

                Canvas.SetLeft(_student2Label, MainInteractiveBoard.ActualWidth / 2 + 20);
                Canvas.SetTop(_student2Label, 20);
            }
            else
            {
                // Position labels for horizontal split
                Canvas.SetLeft(_student1Label, 20);
                Canvas.SetTop(_student1Label, 20);

                Canvas.SetLeft(_student2Label, 20);
                Canvas.SetTop(_student2Label, MainInteractiveBoard.ActualHeight / 2 + 20);
            }

            MainInteractiveBoard.Children.Add(_student1Label);
            MainInteractiveBoard.Children.Add(_student2Label);
        }

        /// <summary>
        /// Get student profile based on touch position
        /// </summary>
        private StudentProfile? GetStudentByPosition(Point position)
        {
            if (!_isMultiUserModeActive || _student1 == null || _student2 == null || _isCustomColorSelected)
                return null;

            if (_currentSplitMode == SplitMode.Vertical)
            {
                // Left half = Student 1, Right half = Student 2
                return position.X < MainInteractiveBoard.ActualWidth / 2 ? _student1 : _student2;
            }
            else
            {
                // Top half = Student 1, Bottom half = Student 2
                return position.Y < MainInteractiveBoard.ActualHeight / 2 ? _student1 : _student2;
            }
        }

        #endregion

    }
}
