using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using QASmartTouch.Handlers;
using QASmartTouch.Managers;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using Path = System.Windows.Shapes.Path;
using System.Windows.Input;
using System.Collections.Generic;
using System.Globalization;
using System.Speech.Synthesis;
using QASmartTouch.Services;
using QASmartTouch.Helpers;
using QASmartTouch.Models;
using QASmartTouch.Controls;
using QASmartTouch.Controllers;
using QASmartTouch.Shared;
using QASmartClass.Properties;
using System.Windows.Documents;
// ══════════════════════════════════════════════════════════════════
// Form2_MainDashboard.BoardManagement.cs — Partial Class (Auto-generated by Refactor Workflow)
// Nguồn gốc: Form2_MainDashboard.xaml.cs, dòng 21747-22679
// #region Board Management, ScreenCurtain, Pan, Pointer, MultiUser
// ══════════════════════════════════════════════════════════════════

namespace QASmartTouch.Forms
{
    public partial class Form2_MainDashboard
    {
        #region Board Management - Background

        /// <summary>
        /// Apply background to MainInteractiveBoard (âœ¨ Updated to support color + pattern combination + dynamic spacing)
        /// </summary>
        public void ApplyCanvasBackground(string? color, string? pattern, int lineSpacing = 40, int lineOpacity = 10)
        {
            try
            {
                bool hasPattern = !string.IsNullOrWhiteSpace(pattern) && !pattern.Equals("none", StringComparison.OrdinalIgnoreCase);

                // Store line spacing, opacity, color and pattern for pattern creation & board persistence
                _currentBackgroundColor = color ?? "#3D6D64";
                _currentBackgroundPattern = hasPattern ? pattern : null;
                _currentLineSpacing = lineSpacing > 0 ? lineSpacing : 40;
                _currentLineOpacity = lineOpacity > 0 ? lineOpacity : 10;
                
                // Cập nhật ngay lập tức vào CurrentBoard của BoardManager nếu có
                if (_boardManager?.CurrentBoard != null)
                {
                    _boardManager.CurrentBoard.BackgroundColorHex = _currentBackgroundColor;
                    _boardManager.CurrentBoard.BackgroundPattern = _currentBackgroundPattern;
                    _boardManager.CurrentBoard.LineSpacing = _currentLineSpacing;
                    _boardManager.CurrentBoard.LineOpacity = _currentLineOpacity;
                }
                
                // ✨ Remove old background rectangles if any
                var oldBgRects = MainInteractiveBoard.Children.OfType<Rectangle>()
                    .Where(r => r.Tag?.ToString() == "BackgroundLayer")
                    .ToList();
                foreach (var rect in oldBgRects)
                {
                    MainInteractiveBoard.Children.Remove(rect);
                }
                
                // Khởi tạo màu nền cơ bản
                Color bgColor;
                if (!string.IsNullOrEmpty(color))
                {
                    try
                    {
                        bgColor = (Color)ColorConverter.ConvertFromString(color);
                    }
                    catch
                    {
                        bgColor = (Color)ColorConverter.ConvertFromString("#3D6D64");
                    }
                }
                else
                {
                    bgColor = (Color)ColorConverter.ConvertFromString("#3D6D64");
                }
                var solidBgBrush = new SolidColorBrush(bgColor);

                // Đồng bộ màu nền ra khung chứa ngoài cùng (ContentGrid & MainScrollViewer)
                if (ContentGrid != null)
                {
                    ContentGrid.Background = solidBgBrush;
                }
                if (MainScrollViewer != null)
                {
                    MainScrollViewer.Background = Brushes.Transparent;
                }

                // Không gian nền ảo rộng lớn: đảm bảo khi zoom nhỏ (50%) hay pan, nền và đường kẻ vẫn bao phủ toàn màn hình
                int spacing;
                if (pattern == "Dots") spacing = 30;
                else if (pattern == "MusicStaff") spacing = Math.Max(10, _currentLineSpacing) * 4;
                else spacing = Math.Max(10, _currentLineSpacing);

                const double VIRTUAL_OFFSET = 50000.0;
                double alignedOffset = Math.Ceiling(VIRTUAL_OFFSET / spacing) * spacing;
                double virtualSize = alignedOffset * 2 + 20000.0;

                // Tạo Rectangle màu nền bao phủ toàn bộ không gian
                var bgRect = new Rectangle
                {
                    Tag = "BackgroundLayer",
                    Width = virtualSize,
                    Height = virtualSize,
                    Fill = solidBgBrush,
                    IsHitTestVisible = false
                };
                Canvas.SetLeft(bgRect, -alignedOffset);
                Canvas.SetTop(bgRect, -alignedOffset);
                MainInteractiveBoard.Children.Insert(0, bgRect);
                Panel.SetZIndex(bgRect, ZIndexConstants.Background);

                if (hasPattern)
                {
                    // Tạo Rectangle mẫu kẻ ô ly/đường kẻ bao phủ cùng không gian và căn chuẩn theo tile
                    var patternRect = new Rectangle
                    {
                        Fill = CreatePatternBrushByName(pattern),
                        Tag = "BackgroundLayer",
                        Width = virtualSize,
                        Height = virtualSize,
                        IsHitTestVisible = false
                    };
                    Canvas.SetLeft(patternRect, -alignedOffset);
                    Canvas.SetTop(patternRect, -alignedOffset);
                    MainInteractiveBoard.Children.Insert(1, patternRect);
                    Panel.SetZIndex(patternRect, ZIndexConstants.GridOverlay);
                }

                MainInteractiveBoard.Background = Brushes.Transparent;
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi áp dụng nền: {ex.Message}", "Lỗi", 
                              MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// âœ¨ Apply default background on startup
        /// </summary>
        private void ApplyDefaultBackground()
        {
            try
            {
                // Load default values from Settings
                string defaultColor = QASmartClass.Properties.Settings.Default.DefaultBackgroundColor;
                string defaultPattern = QASmartClass.Properties.Settings.Default.DefaultBackgroundPattern;
                
                System.Diagnostics.Debug.WriteLine($"🔍 Loading defaults from Settings: Color='{defaultColor}', Pattern='{defaultPattern}'");
                
                // âœ¨ TEMPORARY: Hard-code for testing
                if (string.IsNullOrEmpty(defaultColor))
                {
                    defaultColor = "#3D6D64"; // Traditional chalkboard green
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ Color was empty, using hard-coded: {defaultColor}");
                }
                if (string.IsNullOrEmpty(defaultPattern))
                {
                    defaultPattern = "Grid";
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ Pattern was empty, using hard-coded: {defaultPattern}");
                }
                
                // Apply if valid
                if (!string.IsNullOrEmpty(defaultColor) || !string.IsNullOrEmpty(defaultPattern))
                {
                    System.Diagnostics.Debug.WriteLine($"📝 Applying background: Color={defaultColor}, Pattern={defaultPattern}, Spacing=40px");
                    ApplyCanvasBackground(defaultColor, defaultPattern, 40); // Default spacing 40px
                    System.Diagnostics.Debug.WriteLine($"✅ Applied default background successfully");
                }
                else
                {
                    System.Diagnostics.Debug.WriteLine($"âš ï¸ No default background to apply (both empty)");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Failed to apply default background: {ex.Message}");
                System.Diagnostics.Debug.WriteLine($"Stack trace: {ex.StackTrace}");
                // Fallback to chalkboard green if error
                var fallbackBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                MainInteractiveBoard.Background = fallbackBrush;
                if (ContentGrid != null) ContentGrid.Background = fallbackBrush;
            }
        }

        /// <summary>
        /// ✨ NEW: Apply custom background image to MainInteractiveBoard
        /// </summary>
        public void ApplyCanvasBackgroundImage(System.Windows.Media.Imaging.BitmapImage? backgroundImage, string? pattern = null)
        {
            try
            {
                // Remove old background rectangles
                var oldBgRects = MainInteractiveBoard.Children.OfType<Rectangle>()
                    .Where(r => r.Tag?.ToString() == "BackgroundLayer")
                    .ToList();
                foreach (var rect in oldBgRects)
                {
                    MainInteractiveBoard.Children.Remove(rect);
                }

                if (backgroundImage != null)
                {
                    if (ContentGrid != null)
                    {
                        ContentGrid.Background = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#1E1E1E"));
                    }

                    // Create image background rectangle
                    var imageBrush = new ImageBrush
                    {
                        ImageSource = backgroundImage,
                        Stretch = Stretch.UniformToFill
                    };

                    var bgRect = new Rectangle
                    {
                        Fill = imageBrush,
                        Tag = "BackgroundLayer",
                        // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                        IsHitTestVisible = false
                    };
                    bgRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                    bgRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });

                    // Add to canvas at index 0 (bottom layer)
                    MainInteractiveBoard.Children.Insert(0, bgRect);
                    // ✅ QC_4.2_GRID_PROTECT (G-2): Pin tại (0,0) tránh NaN position
                    Canvas.SetLeft(bgRect, 0);
                    Canvas.SetTop(bgRect, 0);
                    Panel.SetZIndex(bgRect, ZIndexConstants.Background);

                    // Optionally add pattern overlay
                    if (!string.IsNullOrEmpty(pattern))
                    {
                        var patternRect = new Rectangle
                        {
                            Fill = CreatePatternBrushByName(pattern),
                            Tag = "BackgroundLayer",
                            // ✅ QC_4.2_GRID_PROTECT (G-1): Grid không bao giờ nhận touch/click
                            IsHitTestVisible = false
                        };
                        patternRect.SetBinding(FrameworkElement.WidthProperty, new System.Windows.Data.Binding("ActualWidth") { Source = MainInteractiveBoard });
                        patternRect.SetBinding(FrameworkElement.HeightProperty, new System.Windows.Data.Binding("ActualHeight") { Source = MainInteractiveBoard });
                        MainInteractiveBoard.Children.Insert(1, patternRect);
                        // ✅ QC_4.2_GRID_PROTECT (G-2): Pin tại (0,0) tránh NaN position
                        Canvas.SetLeft(patternRect, 0);
                        Canvas.SetTop(patternRect, 0);
                        Panel.SetZIndex(patternRect, ZIndexConstants.GridOverlay);
                    }

                    // Set canvas background to transparent
                    MainInteractiveBoard.Background = Brushes.Transparent;
                }
                else
                {
                    // No image, fallback to chalkboard green
                    var fallbackBrush = new SolidColorBrush((Color)ColorConverter.ConvertFromString("#3D6D64"));
                    MainInteractiveBoard.Background = fallbackBrush;
                    if (ContentGrid != null) ContentGrid.Background = fallbackBrush;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi khi áp dụng ảnh nền: {ex.Message}", "Lỗi",
                              MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }


        /// <summary>
        /// ✨ Refactor: Tách logic tạo pattern thành method riêng
        /// </summary>
        private Brush? CreatePatternBrushByName(string pattern)
        {
            switch (pattern)
            {
                case "Grid": return CreateGridPattern();
                case "Dots": return CreateDotsPattern();
                case "Lines": return CreateLinesPattern();
                case "MusicStaff": return CreateMusicStaffPattern();
                default: return null;
            }
        }

        private Brush CreateGridPattern()
        {
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, _currentLineSpacing, _currentLineSpacing), // Dynamic spacing
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // Vertical line
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                Geometry = new LineGeometry(new Point(0, 0), new Point(0, _currentLineSpacing))
            });
            
            // Horizontal line
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                Geometry = new LineGeometry(new Point(0, 0), new Point(_currentLineSpacing, 0))
            });

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        private Brush CreateDotsPattern()
        {
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 30, 30),
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Dot
            drawingGroup.Children.Add(new GeometryDrawing
            {
                Brush = new SolidColorBrush(Color.FromArgb(40, 0, 0, 0)),
                Geometry = new EllipseGeometry(new Point(15, 15), 0.5, 0.5)
            });

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        /// <summary>
        /// Create horizontal lines pattern (with dynamic spacing)
        /// </summary>
        private Brush CreateLinesPattern()
        {
            // Create drawing brush with dynamic spacing
            var brush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 1, _currentLineSpacing), // Dynamic spacing
                ViewportUnits = BrushMappingMode.Absolute,
                Stretch = Stretch.None
            };

            // Create drawing group
            var group = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // Draw a single horizontal line at the top of the tile
            var linePen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1);
            linePen.Freeze(); // Freeze for performance
            
            group.Children.Add(new GeometryDrawing
            {
                Pen = linePen,
                Geometry = new LineGeometry(new Point(0, 0), new Point(1, 0))
            });

            brush.Drawing = group;
            brush.Freeze(); // Freeze for performance
            
            return brush;
        }

        private Brush CreateMusicStaffPattern()
        {
            // Calculate total height for 5 lines with dynamic spacing
            int totalHeight = _currentLineSpacing * 4; // 4 gaps between 5 lines
            
            var drawingBrush = new DrawingBrush
            {
                TileMode = TileMode.Tile,
                Viewport = new Rect(0, 0, 100, totalHeight),
                ViewportUnits = BrushMappingMode.Absolute
            };

            var drawingGroup = new DrawingGroup();
            
            // Calculate alpha from opacity percentage (0-100 → 0-255)
            byte alpha = (byte)(_currentLineOpacity * 255 / 100);
            
            // 5 lines for music staff with dynamic spacing
            for (int i = 0; i < 5; i++)
            {
                drawingGroup.Children.Add(new GeometryDrawing
                {
                    Pen = new Pen(new SolidColorBrush(Color.FromArgb(alpha, 0, 0, 0)), 1),
                    Geometry = new LineGeometry(new Point(0, i * _currentLineSpacing), new Point(100, i * _currentLineSpacing))
                });
            }

            drawingBrush.Drawing = drawingGroup;
            return drawingBrush;
        }

        #endregion

        #region Screen Curtain (Màn che bảng)

        private Form2_18_ScreenCurtain _screenCurtain;

        /// <summary>
        /// Toggle Screen Curtain (Màn che bảng)
        /// </summary>
        private void btn9_5_ScreenCurtain_Click(object sender, RoutedEventArgs e)
        {
            if (_screenCurtain == null || !_screenCurtain.IsVisible)
            {
                // ✅ PHASE 2: Deactivate tools and close submenus before showing curtain
                DeactivateAllTools();
                CloseAllSubmenus();
                
                // Show curtain
                _screenCurtain = new Form2_18_ScreenCurtain();
                _screenCurtain.Closed += (s, args) =>
                {
                    _screenCurtain = null;
                    // Reset button appearance
                    btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(241, 242, 246)); // #F1F2F6
                };
                _screenCurtain.Show();
                
                // Highlight button when active
                btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(103, 126, 234)); // #667EEA
            }
            else
            {
                // Close curtain
                _screenCurtain.Close();
                _screenCurtain = null;
                btn9_5_ScreenCurtain.Background = new SolidColorBrush(Color.FromRgb(241, 242, 246)); // #F1F2F6
            }
        }

        #endregion

        #region Pan Mode (Drag to Scroll)

        private bool _isPanModeActive = false;
        private Point _scrollPanStartPoint;
        private double _scrollPanStartHorizontalOffset;
        private double _scrollPanStartVerticalOffset;

        /// <summary>
        /// Enable pan mode - allows dragging to scroll the canvas
        /// </summary>
        public void EnablePanMode()
        {
            if (_isPanModeActive)
            {
                // Disable pan mode
                DisablePanMode();
                return;
            }

            // QC_4.2_PAN_MODE_CLEANUP: Tắt hoàn toàn chế độ Bút vẽ và dọn dẹp stroke khi bắt đầu Pan Mode
            _drawingEnabled = false;
            _isDrawing = false;
            _currentStroke = null;
            _eraserEnabled = false;

            _isPanModeActive = true;

            // Change cursor to hand
            MainScrollViewer.Cursor = Cursors.Hand;
            MainInteractiveBoard.Cursor = Cursors.Hand;

            // Subscribe to mouse events for dragging
            MainScrollViewer.PreviewMouseLeftButtonDown += ScrollViewer_PreviewMouseLeftButtonDown;
            MainScrollViewer.PreviewMouseMove += ScrollViewer_PreviewMouseMove;
            MainScrollViewer.PreviewMouseLeftButtonUp += ScrollViewer_PreviewMouseLeftButtonUp;

            // Subscribe to ESC key to exit pan mode
            this.PreviewKeyDown += PanMode_PreviewKeyDown;

            System.Diagnostics.Debug.WriteLine("✅ Pan mode enabled - drag to scroll, ESC to exit");
        }

        private void DisablePanMode()
        {
            _isPanModeActive = false;

            // Release capture if held
            if (MainScrollViewer.IsMouseCaptured)
                MainScrollViewer.ReleaseMouseCapture();
            if (MainInteractiveBoard.IsMouseCaptured)
                MainInteractiveBoard.ReleaseMouseCapture();

            // Restore cursor based on current tool mode
            Cursor defaultCursor = _drawingEnabled ? Cursors.Pen : Cursors.Arrow;
            MainScrollViewer.Cursor = defaultCursor;
            MainInteractiveBoard.Cursor = defaultCursor;

            // Unsubscribe from events
            MainScrollViewer.PreviewMouseLeftButtonDown -= ScrollViewer_PreviewMouseLeftButtonDown;
            MainScrollViewer.PreviewMouseMove -= ScrollViewer_PreviewMouseMove;
            MainScrollViewer.PreviewMouseLeftButtonUp -= ScrollViewer_PreviewMouseLeftButtonUp;
            this.PreviewKeyDown -= PanMode_PreviewKeyDown;

            System.Diagnostics.Debug.WriteLine("✅ Pan mode disabled - restored cursor & released mouse capture");
        }

        #region Pointer Mode (Chỉ Bảng) Implementation
        public bool _isPointerModeActive = false;
        private Grid? _pointerGraphicContainer;

        /// <summary>
        /// Enable Pointer Tool (Chỉ Bảng) - High-visibility animated laser pointer arrow for teaching
        /// </summary>
        public void EnablePointerMode()
        {
            if (_isPointerModeActive)
            {
                DisablePointerMode();
                return;
            }

            // Mode Guard: Turn off all other active tools
            if (_isPanModeActive) DisablePanMode();
            if (_eraserEnabled) DisableEraserMode();

            if (MainScrollViewer.IsMouseCaptured) MainScrollViewer.ReleaseMouseCapture();
            if (MainInteractiveBoard.IsMouseCaptured) MainInteractiveBoard.ReleaseMouseCapture();

            _isDrawing = false;
            _currentStroke = null;

            _drawingEnabled = false;
            _eraserEnabled = false;
            _shapeDrawingEnabled = false;
            _textToolEnabled = false;
            _selectionToolEnabled = false;
            _objectSelectionMode = false;
            _isPointerModeActive = true;

            _selectionManager?.DeselectAll();

            MainInteractiveBoard.Cursor = Cursors.None;
            MainScrollViewer.Cursor = Cursors.None;

            if (_touchHandler != null)
            {
                _touchHandler.SetToolMode(QASmartTouch.Handlers.TouchToolMode.Pointer);
                _touchHandler.SetUpdatePointerAction(UpdatePointerPosition);
            }

            CreatePointerGraphic();
            ShowSmartStatusBadge("📌 Đang bật công cụ Chỉ bảng - Chạm hoặc di chuyển để chỉ điểm");
            System.Diagnostics.Debug.WriteLine("📌 Pointer mode enabled");
        }

        /// <summary>
        /// Disable Pointer Tool (Chỉ Bảng)
        /// </summary>
        public void DisablePointerMode()
        {
            _isPointerModeActive = false;
            RemovePointerGraphic();
            HideSmartStatusBadge();

            MainInteractiveBoard.Cursor = Cursors.Arrow;
            MainScrollViewer.Cursor = Cursors.Arrow;
            System.Diagnostics.Debug.WriteLine("📌 Pointer mode disabled");
        }

        private void CreatePointerGraphic()
        {
            RemovePointerGraphic();

            _pointerGraphicContainer = new Grid
            {
                Width = 72,
                Height = 72,
                IsHitTestVisible = false,
                Tag = "PointerGraphicOverlay"
            };

            // 1. Glowing Laser Pulsing Outer Ring
            var laserPulse = new System.Windows.Shapes.Ellipse
            {
                Width = 28,
                Height = 28,
                Fill = new SolidColorBrush(Color.FromArgb(120, 255, 0, 80)),
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top,
                Margin = new Thickness(-14, -14, 0, 0)
            };

            // 2. Center Laser Red Dot
            var laserDot = new System.Windows.Shapes.Ellipse
            {
                Width = 14,
                Height = 14,
                Fill = new SolidColorBrush(Color.FromRgb(255, 30, 60)),
                Stroke = new SolidColorBrush(Colors.White),
                StrokeThickness = 2,
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Top,
                Margin = new Thickness(-7, -7, 0, 0)
            };

            // 3. Large High-Contrast Pointer Arrow (Mũi tên Đỏ + Viền Vàng + Bóng Đổ 3D)
            var pointerArrow = new System.Windows.Shapes.Polygon
            {
                Points = new PointCollection
                {
                    new Point(0, 0),       // Arrow Tip
                    new Point(0, 48),      // Bottom Left
                    new Point(14, 34),     // Inner notch
                    new Point(28, 56),     // Tail tip
                    new Point(38, 50),     // Tail right
                    new Point(24, 28),     // Tail inner
                    new Point(42, 28)      // Right tip
                },
                Fill = new LinearGradientBrush(
                    Color.FromRgb(255, 45, 85),
                    Color.FromRgb(220, 0, 50),
                    90),
                Stroke = new SolidColorBrush(Color.FromRgb(255, 215, 0)),
                StrokeThickness = 3.5,
                StrokeLineJoin = PenLineJoin.Round,
                Effect = new System.Windows.Media.Effects.DropShadowEffect
                {
                    Color = Colors.Black,
                    BlurRadius = 10,
                    ShadowDepth = 4,
                    Opacity = 0.6
                }
            };

            _pointerGraphicContainer.Children.Add(laserPulse);
            _pointerGraphicContainer.Children.Add(pointerArrow);
            _pointerGraphicContainer.Children.Add(laserDot);

            Canvas.SetLeft(_pointerGraphicContainer, MainInteractiveBoard.ActualWidth / 2);
            Canvas.SetTop(_pointerGraphicContainer, MainInteractiveBoard.ActualHeight / 2);
            Panel.SetZIndex(_pointerGraphicContainer, 999999);

            MainInteractiveBoard.Children.Add(_pointerGraphicContainer);
        }

        public void UpdatePointerPosition(Point pos)
        {
            if (_pointerGraphicContainer == null || !_isPointerModeActive) return;

            Canvas.SetLeft(_pointerGraphicContainer, pos.X);
            Canvas.SetTop(_pointerGraphicContainer, pos.Y);
        }

        private void RemovePointerGraphic()
        {
            if (_pointerGraphicContainer != null)
            {
                if (MainInteractiveBoard.Children.Contains(_pointerGraphicContainer))
                {
                    MainInteractiveBoard.Children.Remove(_pointerGraphicContainer);
                }
                _pointerGraphicContainer = null;
            }
        }
        #endregion

        private void ScrollViewer_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (!_isPanModeActive || _drawingEnabled)
            {
                if (MainScrollViewer.IsMouseCaptured)
                    MainScrollViewer.ReleaseMouseCapture();
                return;
            }

            // Ensure no drawing occurs during pan drag
            _isDrawing = false;
            _currentStroke = null;

            _scrollPanStartPoint = e.GetPosition(MainScrollViewer);
            _scrollPanStartHorizontalOffset = MainScrollViewer.HorizontalOffset;
            _scrollPanStartVerticalOffset = MainScrollViewer.VerticalOffset;

            MainScrollViewer.CaptureMouse();
            MainScrollViewer.Cursor = Cursors.ScrollAll; // Change to move cursor while dragging
        }

        private void ScrollViewer_PreviewMouseMove(object sender, MouseEventArgs e)
        {
            // QC_4.2_PREVENT_AUTO_SCROLL: Tuyệt đối không cuộn màn hình nếu đang vẽ nét bút hoặc ngắt Pan Mode
            if (!_isPanModeActive || _drawingEnabled || _isDrawing || !MainScrollViewer.IsMouseCaptured)
            {
                return;
            }

            Point currentPoint = e.GetPosition(MainScrollViewer);
            double deltaX = _scrollPanStartPoint.X - currentPoint.X;
            double deltaY = _scrollPanStartPoint.Y - currentPoint.Y;

            MainScrollViewer.ScrollToHorizontalOffset(_scrollPanStartHorizontalOffset + deltaX);
            MainScrollViewer.ScrollToVerticalOffset(_scrollPanStartVerticalOffset + deltaY);
        }

        private void ScrollViewer_PreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            if (MainScrollViewer.IsMouseCaptured)
            {
                MainScrollViewer.ReleaseMouseCapture();
            }

            if (!_isPanModeActive) return;

            MainScrollViewer.Cursor = Cursors.Hand; // Restore hand cursor
        }

        private void PanMode_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Escape && _isPanModeActive)
            {
                DisablePanMode();
                e.Handled = true;
            }
        }

        #endregion

        #region Multi-User Mode (Dedicated Dual Board Sandbox - Umind style)

        private bool _isMultiUserModeActive = false;
        private bool _zoneIsolationEnabled = false;
        private StudentProfile? _student1;
        private StudentProfile? _student2;

        public bool IsMultiUserModeActive => _isMultiUserModeActive;

        /// <summary>
        /// Khởi chạy Chế độ Đa người dùng (2 học sinh cùng làm bài) theo mô hình Umind Sandbox chuyên biệt
        /// </summary>
        public void StartMultiUserSession(StudentProfile student1, StudentProfile student2)
        {
            try
            {
                _student1 = student1;
                _student2 = student2;
                _isMultiUserModeActive = true;

                // 1. Lưu lại trạng thái bài giảng hiện tại của giáo viên
                _boardManager?.SaveCurrentBoardState();

                // 2. Kế thừa màu nền hiện tại của bảng chính
                Brush currentBg = MainInteractiveBoard.Background?.Clone() ?? new SolidColorBrush(Color.FromRgb(0x3D, 0x6D, 0x64));

                // 3. Đăng ký sự kiện hoàn thành từ overlay (chỉ đăng ký 1 lần)
                multiUserOverlay.SessionCompleted -= MultiUserOverlay_SessionCompleted;
                multiUserOverlay.SessionCompleted += MultiUserOverlay_SessionCompleted;

                // 4. Kích hoạt và hiển thị Sandbox Overlay
                multiUserOverlay.StartSession(
                    student1.Name, student1.Color,
                    student2.Name, student2.Color,
                    currentBg
                );
                multiUserOverlay.Visibility = Visibility.Visible;

                System.Diagnostics.Debug.WriteLine($"✅ Multi-User Sandbox Session started: {student1.Name} vs {student2.Name}");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Error starting Multi-User session: {ex.Message}");
            }
        }

        private void MultiUserOverlay_SessionCompleted(object? sender, QASmartTouch.Controls.MultiUserSessionEventArgs e)
        {
            try
            {
                if (e.SaveAsNewBoard && _boardManager != null)
                {
                    // Tạo một trang bài giảng mới để lưu kết quả bài làm của 2 học sinh
                    string boardTitle = $"Bài làm: {e.Student1Name} vs {e.Student2Name}";
                    var newBoard = _boardManager.CreateBoard(boardTitle);
                    if (newBoard != null)
                    {
                        var elements = new System.Collections.Generic.List<UIElement>();
                        double targetW = 1920;
                        double targetH = 1080;
                        double halfW = targetW / 2;

                        // 1. Thêm đường phân cách giữa (Divider)
                        var dividerLine = new System.Windows.Shapes.Line
                        {
                            X1 = halfW,
                            Y1 = 0,
                            X2 = halfW,
                            Y2 = targetH,
                            Stroke = new SolidColorBrush(Color.FromArgb(120, 255, 255, 255)),
                            StrokeThickness = 3,
                            StrokeDashArray = new DoubleCollection { 4, 2 },
                            Tag = "MultiUserDivider"
                        };
                        Panel.SetZIndex(dividerLine, 10);
                        elements.Add(dividerLine);

                        // 2. Thêm nhãn tên Học sinh 1
                        var labelStudent1 = new TextBlock
                        {
                            Text = $"🔵 {e.Student1Name}",
                            FontSize = 26,
                            FontWeight = FontWeights.Bold,
                            Foreground = new SolidColorBrush(e.Student1Color),
                            Background = new SolidColorBrush(Color.FromArgb(200, 30, 39, 46)),
                            Padding = new Thickness(16, 8, 16, 8),
                            Tag = "MultiUserLabel"
                        };
                        Canvas.SetLeft(labelStudent1, 30);
                        Canvas.SetTop(labelStudent1, 30);
                        Panel.SetZIndex(labelStudent1, 20);
                        elements.Add(labelStudent1);

                        // 3. Thêm nhãn tên Học sinh 2
                        var labelStudent2 = new TextBlock
                        {
                            Text = $"🔴 {e.Student2Name}",
                            FontSize = 26,
                            FontWeight = FontWeights.Bold,
                            Foreground = new SolidColorBrush(e.Student2Color),
                            Background = new SolidColorBrush(Color.FromArgb(200, 30, 39, 46)),
                            Padding = new Thickness(16, 8, 16, 8),
                            Tag = "MultiUserLabel"
                        };
                        Canvas.SetLeft(labelStudent2, halfW + 30);
                        Canvas.SetTop(labelStudent2, 30);
                        Panel.SetZIndex(labelStudent2, 20);
                        elements.Add(labelStudent2);

                        // Tỉ lệ scale nếu kích thước render thực tế khác 1920x1080
                        double scaleX = e.ActualAreaWidth > 0 ? (targetW / e.ActualAreaWidth) : 1.0;
                        double scaleY = e.ActualAreaHeight > 0 ? (targetH / e.ActualAreaHeight) : 1.0;

                        // 4. Clone nét vẽ Học sinh 1 (Nửa trái) — clip trong vùng [0, halfW]
                        var leftClip = new Rect(0, 0, halfW, targetH);
                        foreach (var pl in e.LeftPolylines)
                        {
                            var clone = ClonePolyline(pl, 0, 0, scaleX, scaleY, leftClip);
                            clone.Tag = "Student1Stroke";
                            elements.Add(clone);
                        }

                        // 5. Clone nét vẽ Học sinh 2 (Nửa phải: offset halfW) — clip trong vùng [halfW, targetW]
                        var rightClip = new Rect(halfW, 0, halfW, targetH);
                        foreach (var pl in e.RightPolylines)
                        {
                            var clone = ClonePolyline(pl, halfW, 0, scaleX, scaleY, rightClip);
                            clone.Tag = "Student2Stroke";
                            elements.Add(clone);
                        }

                        newBoard.CanvasElements = elements;
                        newBoard.ObjectCount = elements.Count;
                        newBoard.CanvasWidth = targetW;
                        newBoard.CanvasHeight = targetH;
                        newBoard.LastModifiedAt = DateTime.Now;

                        // FIX BUG 3: Copy background settings từ trang hiện tại
                        // để trang multi-user mới không bị nhận default (Colors.White + grid)
                        var currentBoard = _boardManager.CurrentBoard;
                        newBoard.BackgroundColor = currentBoard.BackgroundColor;
                        newBoard.BackgroundColorHex = currentBoard.BackgroundColorHex;
                        newBoard.BackgroundPattern = currentBoard.BackgroundPattern;
                        newBoard.LineSpacing = currentBoard.LineSpacing;
                        newBoard.LineOpacity = currentBoard.LineOpacity;

                        ShowSmartStatusBadge($"💾 Đã lưu bài làm thành Trang {_boardManager.Boards.Count}: {newBoard.Name}");
                    }
                }
                else
                {
                    ShowSmartStatusBadge("ℹ️ Đã kết thúc chế độ thi đua (Không lưu nháp)");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Error saving multi-user session: {ex.Message}");
            }
            finally
            {
                // Ẩn Sandbox Overlay và trả về trang bài giảng hiện tại
                multiUserOverlay.Visibility = Visibility.Collapsed;
                _isMultiUserModeActive = false;
            }
        }

        private System.Windows.Shapes.Polyline ClonePolyline(
            System.Windows.Shapes.Polyline source, double offsetX, double offsetY,
            double scaleX = 1.0, double scaleY = 1.0, Rect? clipRect = null)
        {
            var polyline = new System.Windows.Shapes.Polyline
            {
                Stroke = source.Stroke?.Clone(),
                StrokeThickness = source.StrokeThickness,
                StrokeStartLineCap = PenLineCap.Round,
                StrokeEndLineCap = PenLineCap.Round,
                StrokeLineJoin = PenLineJoin.Round,
                Opacity = source.Opacity,
                SnapsToDevicePixels = true
            };

            var points = new PointCollection();
            foreach (var pt in source.Points)
            {
                double x = (pt.X * scaleX) + offsetX;
                double y = (pt.Y * scaleY) + offsetY;

                // Clip tọa độ trong vùng cho phép để nét vẽ không tràn sang phần người khác
                if (clipRect.HasValue)
                {
                    x = Math.Max(clipRect.Value.Left, Math.Min(x, clipRect.Value.Right));
                    y = Math.Max(clipRect.Value.Top, Math.Min(y, clipRect.Value.Bottom));
                }

                points.Add(new Point(x, y));
            }
            polyline.Points = points;
            Panel.SetZIndex(polyline, QASmartTouch.Helpers.ZIndexConstants.UserContentBase);
            return polyline;
        }

        /// <summary>
        /// Tương thích ngược: Bật chế độ đa người dùng
        /// </summary>
        public void EnableMultiUserMode(SplitMode splitMode, StudentProfile student1, StudentProfile student2, bool zoneIsolation = false, bool showSplitLine = true)
        {
            StartMultiUserSession(student1, student2);
        }

        /// <summary>
        /// Tương thích ngược: Tắt chế độ đa người dùng
        /// </summary>
        public void DisableMultiUserMode()
        {
            _isMultiUserModeActive = false;
            if (multiUserOverlay != null)
            {
                multiUserOverlay.Visibility = Visibility.Collapsed;
            }
        }

        /// <summary>
        /// Tương thích ngược: Lấy profile học sinh theo tọa độ
        /// </summary>
        private StudentProfile? GetStudentByPosition(Point position)
        {
            if (!_isMultiUserModeActive || _student1 == null || _student2 == null)
                return null;

            return position.X < MainInteractiveBoard.ActualWidth / 2 ? _student1 : _student2;
        }

        #endregion

        #region Board Management - Page Switching & Isolation

        /// <summary>
        /// ✅ GIAI ĐOẠN 2: Xử lý chuyển trang/bảng an toàn, cách ly Undo/Redo và đồng bộ SelectionManager
        /// </summary>
        private void OnBoardSwitched(object? sender, QASmartTouch.Managers.BoardSwitchEventArgs e)
        {
            try
            {
                // 1. Đảm bảo toàn bộ Selection UI được reset sạch sẽ
                _selectionManager?.DeselectAll();
                _selectionBox?.Detach();
                _contextToolbar?.Hide();
                _thicknessPicker?.Hide();
                _colorPicker?.Hide();
                _moreMenu?.Hide();

                // 2. Phục hồi ngăn xếp Undo / Redo của trang mới
                if (e.NewBoard != null)
                {
                    _undoStack = new System.Collections.Generic.Stack<UndoRedoAction>(e.NewBoard.UndoStack.Reverse());
                    _redoStack = new System.Collections.Generic.Stack<UndoRedoAction>(e.NewBoard.RedoStack.Reverse());
                    UpdateButtonStates();

                    // Phục hồi kích thước Canvas riêng biệt của trang mới
                    double targetW = e.NewBoard.CanvasWidth > 0 ? e.NewBoard.CanvasWidth : 1920;
                    double targetH = e.NewBoard.CanvasHeight > 0 ? e.NewBoard.CanvasHeight : 1080;
                    SetCanvasSize(targetW, targetH);
                    UpdateScrollBarVisibility();

                    // 3. Tái tạo nền bảng của trang mới (hỗ trợ ảnh nền hoặc màu sắc + hoa văn)
                    if (!string.IsNullOrEmpty(e.NewBoard.BackgroundImagePath) && System.IO.File.Exists(e.NewBoard.BackgroundImagePath))
                    {
                        try
                        {
                            var bitmap = new BitmapImage(new Uri(e.NewBoard.BackgroundImagePath, UriKind.Absolute));
                            ApplyCanvasBackgroundImage(bitmap, e.NewBoard.BackgroundPattern);
                        }
                        catch
                        {
                            ApplyCanvasBackground(
                                e.NewBoard.BackgroundColorHex ?? "#3D6D64",
                                e.NewBoard.BackgroundPattern,
                                e.NewBoard.LineSpacing > 0 ? e.NewBoard.LineSpacing : 40,
                                e.NewBoard.LineOpacity > 0 ? e.NewBoard.LineOpacity : 10
                            );
                        }
                    }
                    else
                    {
                        ApplyCanvasBackground(
                            e.NewBoard.BackgroundColorHex ?? "#3D6D64",
                            e.NewBoard.BackgroundPattern,
                            e.NewBoard.LineSpacing > 0 ? e.NewBoard.LineSpacing : 40,
                            e.NewBoard.LineOpacity > 0 ? e.NewBoard.LineOpacity : 10
                        );
                    }
                }
                else
                {
                    _undoStack.Clear();
                    _redoStack.Clear();
                    UpdateButtonStates();
                    SetCanvasSize(1920, 1080);
                    UpdateScrollBarVisibility();
                }

                // 4. Đồng bộ lại toàn bộ đối tượng của trang mới vào SelectionManager
                RefreshSelectableObjects();

                // 5. Kích hoạt lại tương tác kéo thả cho các khối 3D trên trang mới
                foreach (UIElement child in MainInteractiveBoard.Children)
                {
                    if (child is Canvas canvas && canvas.Tag?.ToString() == "3DShape")
                    {
                        Enable3DShapeDragging(canvas);
                    }
                }

                // 6. Hiển thị thông báo trạng thái
                ShowSmartStatusBadge($"📋 Đang hiển thị: {e.NewBoard?.Name ?? "Bảng mới"}");
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"❌ Error in OnBoardSwitched: {ex.Message}");
            }
        }

        private void OnBoardDeleted(object? sender, QASmartTouch.Managers.BoardEventArgs e)
        {
            MarkAsDirty();
            UpdateButtonStates();
            ShowSmartStatusBadge($"🗑️ Đã xóa: {e.Board.Name}");
        }

        #endregion

        #region Dirty State & Unsaved Changes Tracking

        private bool _isDirty = false;

        /// <summary>
        /// Cho biết bài giảng có các thay đổi chưa lưu hay không
        /// </summary>
        public bool HasUnsavedChanges => _isDirty;

        /// <summary>
        /// Đánh dấu bài giảng đã bị thay đổi (cần lưu)
        /// </summary>
        public void MarkAsDirty()
        {
            _isDirty = true;
        }

        /// <summary>
        /// Xóa cờ thay đổi (sau khi lưu hoặc mở bài giảng thành công)
        /// </summary>
        public void ClearDirty()
        {
            _isDirty = false;
        }

        /// <summary>
        /// Kiểm tra xem có dữ liệu bài giảng thực sự chưa lưu hay không
        /// </summary>
        public bool CheckHasUnsavedChanges()
        {
            if (!_isDirty) return false;

            // Kiểm tra các trang bảng trong BoardManager
            if (_boardManager != null)
            {
                bool hasElementsInBoards = _boardManager.Boards.Any(b =>
                    b.CanvasElements != null && b.CanvasElements.Any(el => !_boardManager.IsSystemElement(el)));
                if (hasElementsInBoards) return true;
            }

            // Kiểm tra trang hiện tại trên Canvas
            bool hasCanvasContent = MainInteractiveBoard.Children.OfType<UIElement>()
                .Any(el => _boardManager != null 
                    ? !_boardManager.IsSystemElement(el) 
                    : (el is not FrameworkElement fe || fe.Tag?.ToString() != "BackgroundLayer"));

            return hasCanvasContent;
        }

        #endregion

        #region Lecture Save / Load (.qasc)

        private string? _currentLectureFilePath = null;

        /// <summary>
        /// Đường dẫn tệp bài giảng .qasc hiện tại (null nếu chưa lưu)
        /// </summary>
        public string? CurrentLectureFilePath => _currentLectureFilePath;

        /// <summary>
        /// Lưu bài giảng hiện tại (.qasc)
        /// Nếu filePath rỗng và chưa từng lưu -> mở SaveFileDialog
        /// </summary>
        public bool SaveCurrentLecture(string? customFilePath = null, bool showOpenFolderPrompt = true)
        {
            if (_boardManager == null)
            {
                MessageBox.Show("Bảng vẽ chưa được khởi tạo đầy đủ.", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Warning);
                return false;
            }

            string? targetPath = customFilePath;

            string defaultDir = System.IO.Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "QA SmartClass",
                "BaiGiang");

            if (!System.IO.Directory.Exists(defaultDir))
            {
                System.IO.Directory.CreateDirectory(defaultDir);
            }

            if (string.IsNullOrWhiteSpace(targetPath))
            {
                if (!string.IsNullOrWhiteSpace(_currentLectureFilePath))
                {
                    targetPath = _currentLectureFilePath;
                }
                else
                {
                    var saveDialog = new Microsoft.Win32.SaveFileDialog
                    {
                        Title = "Lưu bài giảng QA SmartClass",
                        Filter = "Bài giảng QA SmartClass (*.qasc)|*.qasc",
                        DefaultExt = ".qasc",
                        InitialDirectory = defaultDir,
                        FileName = $"BaiGiang_{DateTime.Now:yyyyMMdd_HHmm}.qasc"
                    };

                    if (saveDialog.ShowDialog(this) != true)
                    {
                        return false;
                    }

                    targetPath = saveDialog.FileName;
                }
            }

            try
            {
                string title = System.IO.Path.GetFileNameWithoutExtension(targetPath);
                bool success = QASmartTouch.WhiteboardCore.IO.SaveLoadService.SaveLecture(_boardManager, targetPath, title);

                if (success)
                {
                    _currentLectureFilePath = targetPath;
                    _isDirty = false;
                    RecentFilesService.Instance.AddFile(targetPath, title);

                    if (showOpenFolderPrompt)
                    {
                        // Hiển thị thông báo xác nhận vị trí lưu và cho phép mở thư mục ngay
                        var msgResult = MessageBox.Show(
                            $"Đã lưu bài giảng thành công!\n\n📁 Vị trí lưu:\n{targetPath}\n\nBạn có muốn mở thư mục chứa tệp này không?",
                            "Lưu bài giảng",
                            MessageBoxButton.YesNo,
                            MessageBoxImage.Information);

                        if (msgResult == MessageBoxResult.Yes)
                        {
                            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
                            {
                                FileName = "explorer.exe",
                                Arguments = $"/select,\"{targetPath}\"",
                                UseShellExecute = true
                            });
                        }
                    }
                    else
                    {
                        ShowSmartStatusBadge($"💾 Đã lưu bài giảng: {System.IO.Path.GetFileName(targetPath)}");
                    }

                    return true;
                }
                else
                {
                    MessageBox.Show("Không thể lưu bài giảng. Vui lòng kiểm tra lại quyền ghi tệp tin.", "Lỗi lưu tệp", MessageBoxButton.OK, MessageBoxImage.Error);
                    return false;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi lưu bài giảng: {ex.Message}", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Error);
                return false;
            }
            finally
            {
                try { this.Activate(); } catch { }
            }
        }

        /// <summary>
        /// Mở bài giảng từ tệp .qasc
        /// </summary>
        public bool LoadLecture(string filePath)
        {
            if (_boardManager == null || !System.IO.File.Exists(filePath)) return false;

            try
            {
                var manifest = QASmartTouch.WhiteboardCore.IO.SaveLoadService.LoadLecture(_boardManager, filePath);
                if (manifest != null)
                {
                    _currentLectureFilePath = filePath;
                    _isDirty = false;
                    RecentFilesService.Instance.AddFile(filePath, manifest.Title);
                    UpdateButtonStates();
                    ShowSmartStatusBadge($"📂 Đã mở bài giảng: {System.IO.Path.GetFileName(filePath)}");
                    return true;
                }
                else
                {
                    MessageBox.Show("Không thể đọc tệp bài giảng. Tệp có thể bị hỏng hoặc không đúng định dạng .qasc.", "Lỗi mở tệp", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return false;
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Lỗi mở bài giảng: {ex.Message}", "Lỗi", MessageBoxButton.OK, MessageBoxImage.Error);
                return false;
            }
        }

        #endregion

    }
}
