CREATE TABLE IF NOT EXISTS YouthMembers (Id INTEGER PRIMARY KEY AUTOINCREMENT, StudentId INTEGER, StudentName TEXT, ClassName TEXT, MemberType TEXT, JoinDate TEXT, Position TEXT, DoanCardNo TEXT, Status TEXT, PhoneNumber TEXT, Email TEXT, AvatarPath TEXT, TotalScore INTEGER, FeeStatus TEXT);
CREATE TABLE IF NOT EXISTS YouthActivities (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, Date TEXT, Participants TEXT, Points INTEGER, Evidence TEXT, Status TEXT, Budget REAL, Location TEXT, Description TEXT, CreatedBy TEXT, MaxParticipants INTEGER, PlanId INTEGER);
CREATE TABLE IF NOT EXISTS YouthAttendances (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER, SessionDate TEXT, SessionType TEXT, SessionTitle TEXT, IsPresent INTEGER, Note TEXT);
CREATE TABLE IF NOT EXISTS YouthRecruitments (Id INTEGER PRIMARY KEY AUTOINCREMENT, StudentId INTEGER, StudentName TEXT, ClassName TEXT, Reason TEXT, Status TEXT, ApplyDate TEXT, ApproveDate TEXT, ApprovedBy TEXT, Note TEXT);
CREATE TABLE IF NOT EXISTS YouthFees (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER, Amount REAL, Period TEXT, PaidDate TEXT, Status TEXT, CollectedBy TEXT);
CREATE TABLE IF NOT EXISTS YouthPlans (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, PeriodType TEXT, StartDate TEXT, EndDate TEXT, Status TEXT, CreatedBy TEXT, CreatedAt TEXT);
CREATE TABLE IF NOT EXISTS YouthEventRegistrations (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActivityId INTEGER, MemberId INTEGER, RegisteredAt TEXT, AttendedAt TEXT, Role TEXT);
CREATE TABLE IF NOT EXISTS YouthEmulationScores (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER, ActivityId INTEGER, Score INTEGER, Category TEXT, Reason TEXT, AwardedDate TEXT, AwardedBy TEXT);
CREATE TABLE IF NOT EXISTS YouthAwardProposals (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER, ProposalType TEXT, Reason TEXT, Status TEXT, ProposedBy TEXT, ApprovedBy TEXT, CreatedAt TEXT, EvidencePath TEXT);
CREATE TABLE IF NOT EXISTS YouthAwardRecords (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER, AwardTitle TEXT, DecisionNo TEXT, FilePath TEXT, AwardDate TEXT);
CREATE TABLE IF NOT EXISTS YouthVotings (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, Description TEXT, StartDate TEXT, EndDate TEXT, Status TEXT, Candidates TEXT);
CREATE TABLE IF NOT EXISTS YouthVotes (Id INTEGER PRIMARY KEY AUTOINCREMENT, VotingId INTEGER, VoterId INTEGER, CandidateId INTEGER, VotedAt TEXT);
CREATE TABLE IF NOT EXISTS YouthVoterRegistries (Id INTEGER PRIMARY KEY AUTOINCREMENT, VotingId INTEGER, VoterId INTEGER, VotedAt TEXT);
CREATE TABLE IF NOT EXISTS YouthDocuments (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, Category TEXT, FilePath TEXT, UploadedBy TEXT, UploadedAt TEXT);
CREATE TABLE IF NOT EXISTS YouthBudgets (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT, Type TEXT, Amount REAL, Date TEXT, Category TEXT, Note TEXT, CreatedBy TEXT);

