DROP TABLE IF EXISTS YouthMembers;
DROP TABLE IF EXISTS YouthActivities;
DROP TABLE IF EXISTS YouthAttendances;
DROP TABLE IF EXISTS YouthRecruitments;
DROP TABLE IF EXISTS YouthFees;
DROP TABLE IF EXISTS YouthPlans;
DROP TABLE IF EXISTS YouthEventRegistrations;
DROP TABLE IF EXISTS YouthEmulationScores;
DROP TABLE IF EXISTS YouthAwardProposals;
DROP TABLE IF EXISTS YouthVotings;
DROP TABLE IF EXISTS YouthVotes;
DROP TABLE IF EXISTS YouthVoterRegistries;
DROP TABLE IF EXISTS YouthDocuments;
DROP TABLE IF EXISTS YouthAwardRecords;
DROP TABLE IF EXISTS YouthBudgets;

CREATE TABLE YouthMembers (Id INTEGER PRIMARY KEY AUTOINCREMENT, StudentId INTEGER NOT NULL, StudentName TEXT NOT NULL DEFAULT '', ClassName TEXT NOT NULL DEFAULT '', MemberType TEXT NOT NULL DEFAULT 'Doan vien', JoinDate TEXT NOT NULL, Position TEXT NOT NULL DEFAULT 'Thanh vien', DoanCardNo TEXT NOT NULL DEFAULT '', Status TEXT NOT NULL DEFAULT 'Active', PhoneNumber TEXT NOT NULL DEFAULT '', Email TEXT NOT NULL DEFAULT '', AvatarPath TEXT NOT NULL DEFAULT '', TotalScore INTEGER NOT NULL DEFAULT 0, FeeStatus TEXT NOT NULL DEFAULT 'Unpaid');

CREATE TABLE YouthActivities (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL DEFAULT '', Date TEXT NOT NULL, Participants TEXT NOT NULL DEFAULT '', Points INTEGER NOT NULL DEFAULT 0, Evidence TEXT NOT NULL DEFAULT '', Status TEXT NOT NULL DEFAULT 'Draft', Budget REAL NOT NULL DEFAULT 0, Location TEXT NOT NULL DEFAULT '', Description TEXT NOT NULL DEFAULT '', CreatedBy TEXT NOT NULL DEFAULT '', MaxParticipants INTEGER NOT NULL DEFAULT 0, PlanId INTEGER NOT NULL DEFAULT 0);

CREATE TABLE YouthAttendances (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER NOT NULL, SessionDate TEXT NOT NULL, SessionType TEXT NOT NULL DEFAULT 'Chi Doan', SessionTitle TEXT NOT NULL DEFAULT '', IsPresent INTEGER NOT NULL DEFAULT 0, Note TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthRecruitments (Id INTEGER PRIMARY KEY AUTOINCREMENT, StudentId INTEGER NOT NULL DEFAULT 0, StudentName TEXT NOT NULL DEFAULT '', ClassName TEXT NOT NULL DEFAULT '', Reason TEXT NOT NULL DEFAULT '', Status TEXT NOT NULL DEFAULT 'Applied', ApplyDate TEXT NOT NULL, ApproveDate TEXT, ApprovedBy TEXT NOT NULL DEFAULT '', Note TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthFees (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER NOT NULL, Amount REAL NOT NULL DEFAULT 0, Period TEXT NOT NULL DEFAULT '', PaidDate TEXT, Status TEXT NOT NULL DEFAULT 'Unpaid', CollectedBy TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthPlans (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL DEFAULT '', PeriodType TEXT NOT NULL DEFAULT 'Month', StartDate TEXT NOT NULL, EndDate TEXT NOT NULL, Status TEXT NOT NULL DEFAULT 'Draft', CreatedBy TEXT NOT NULL DEFAULT '', CreatedAt TEXT NOT NULL);

CREATE TABLE YouthEventRegistrations (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActivityId INTEGER NOT NULL, MemberId INTEGER NOT NULL, RegisteredAt TEXT NOT NULL, AttendedAt TEXT, Role TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthEmulationScores (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER NOT NULL, ActivityId INTEGER NOT NULL DEFAULT 0, Score INTEGER NOT NULL DEFAULT 0, Category TEXT NOT NULL DEFAULT '', Reason TEXT NOT NULL DEFAULT '', AwardedDate TEXT NOT NULL, AwardedBy TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthAwardProposals (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER NOT NULL, ProposalType TEXT NOT NULL DEFAULT '', Reason TEXT NOT NULL DEFAULT '', Status TEXT NOT NULL DEFAULT 'Pending', ProposedBy TEXT NOT NULL DEFAULT '', ApprovedBy TEXT NOT NULL DEFAULT '', CreatedAt TEXT NOT NULL, EvidencePath TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthVotings (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL DEFAULT '', Description TEXT NOT NULL DEFAULT '', StartDate TEXT NOT NULL, EndDate TEXT NOT NULL, Status TEXT NOT NULL DEFAULT 'Open', Candidates TEXT NOT NULL DEFAULT '');

CREATE TABLE YouthVotes (Id INTEGER PRIMARY KEY AUTOINCREMENT, VotingId INTEGER NOT NULL, VoterId INTEGER NOT NULL DEFAULT 0, CandidateId INTEGER NOT NULL, VotedAt TEXT NOT NULL);

CREATE TABLE YouthVoterRegistries (Id INTEGER PRIMARY KEY AUTOINCREMENT, VotingId INTEGER NOT NULL, VoterId INTEGER NOT NULL, VotedAt TEXT NOT NULL);

CREATE TABLE YouthDocuments (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL DEFAULT '', Category TEXT NOT NULL DEFAULT '', FilePath TEXT NOT NULL DEFAULT '', UploadedBy TEXT NOT NULL DEFAULT '', UploadedAt TEXT NOT NULL);

CREATE TABLE YouthAwardRecords (Id INTEGER PRIMARY KEY AUTOINCREMENT, MemberId INTEGER NOT NULL, AwardTitle TEXT NOT NULL DEFAULT '', DecisionNo TEXT NOT NULL DEFAULT '', AwardDate TEXT NOT NULL);

CREATE TABLE YouthBudgets (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL DEFAULT '', Type TEXT NOT NULL DEFAULT '', Amount REAL NOT NULL DEFAULT 0, Date TEXT NOT NULL, Category TEXT NOT NULL DEFAULT '', Note TEXT NOT NULL DEFAULT '', CreatedBy TEXT NOT NULL DEFAULT '');
