import os

manager_code = """using System;
using System.Collections.Generic;

namespace QASmartClass.LearningTools.Helpers
{
    public class WorkplaceToolInfo
    {
        public string ToolId { get; set; } = "";
        public string Title { get; set; } = "";
        public string Meaning { get; set; } = "";
        public string RealWorldApplication { get; set; } = "";
    }

    public class WorkplaceTemplate
    {
        public string Category { get; set; } = "";
        public string Name { get; set; } = "";
        public object Data { get; set; } = null!; 
    }

    // --- DATA CLASSES ---
    public class FiveWhyData { public string Problem{get;set;}=""; public string Why1{get;set;}=""; public string Why2{get;set;}=""; public string Why3{get;set;}=""; public string Why4{get;set;}=""; public string Why5{get;set;}=""; public string How{get;set;}=""; }
    public class FishboneData { public string MainProblem{get;set;}=""; public Dictionary<string, string[]> Groups{get;set;} = new(); }
    public class ParetoData { public (string Name, double Value)[] Items{get;set;} = Array.Empty<(string, double)>(); }
    public class PdcaData { public string Plan{get;set;}=""; public string Do{get;set;}=""; public string Check{get;set;}=""; public string Act{get;set;}=""; }
    public class SwotData { public string[] S{get;set;}=Array.Empty<string>(); public string[] W{get;set;}=Array.Empty<string>(); public string[] O{get;set;}=Array.Empty<string>(); public string[] T{get;set;}=Array.Empty<string>(); }
    public class EisenhowerData { public string[] UI{get;set;}=Array.Empty<string>(); public string[] NUI{get;set;}=Array.Empty<string>(); public string[] UNI{get;set;}=Array.Empty<string>(); public string[] NUNI{get;set;}=Array.Empty<string>(); }
    public class FiveSData { public string Subject{get;set;}=""; }
    public class KanbanData { public (string Title, string Desc)[] Todo{get;set;}=Array.Empty<(string,string)>(); public (string Title, string Desc)[] Doing{get;set;}=Array.Empty<(string,string)>(); public (string Title, string Desc)[] Done{get;set;}=Array.Empty<(string,string)>(); }
    public class KpiOkrData { public string Obj{get;set;}=""; public (string Name, string Tgt, string Act)[] Data{get;set;}=Array.Empty<(string,string,string)>(); }

    public static class WorkplaceTemplateManager
    {
        public static WorkplaceToolInfo GetToolInfo(string toolId)
        {
            return toolId switch
            {
                "five_why" => new WorkplaceToolInfo { ToolId = toolId, Title = "Phân Tích 5 Why (Sakichi Toyoda - Hãng Toyota)", Meaning = "Đặt câu hỏi 'Tại sao' liên tiếp 5 lần để đào sâu và tìm ra nguyên nhân gốc rễ.", RealWorldApplication = "🏭 Toyota dùng tìm lỗi xe. 🎓 Học sinh dùng sửa tật trì hoãn." },
                "fishbone" => new WorkplaceToolInfo { ToolId = toolId, Title = "Biểu đồ Xương cá (Kaoru Ishikawa - ĐH Tokyo)", Meaning = "Phân loại nguyên nhân thành các nhóm (Con người, Máy móc, Vật liệu...).", RealWorldApplication = "🏭 Các hãng bay tìm nguyên nhân trễ chuyến. 🎓 Lớp phân tích vì sao bị trừ điểm thi đua." },
                "pareto" => new WorkplaceToolInfo { ToolId = toolId, Title = "Nguyên lý Pareto 80/20 (Vilfredo Pareto - Ý)", Meaning = "80% kết quả đến từ 20% nguyên nhân. Giúp tập trung vào yếu tố quan trọng nhất.", RealWorldApplication = "🏭 Microsoft thấy 80% lỗi từ 20% code. 🎓 Học sinh ôn 20% dạng bài chiếm 80% điểm số." },
                "pdca" => new WorkplaceToolInfo { ToolId = toolId, Title = "Chu trình PDCA (Edward Deming)", Meaning = "Plan -> Do -> Check -> Act. Bánh xe cải tiến liên tục.", RealWorldApplication = "🏭 Apple thử nghiệm iPhone mới. 🎓 Học sinh lập kế hoạch tăng điểm, thi thử và rút kinh nghiệm." },
                "swot" => new WorkplaceToolInfo { ToolId = toolId, Title = "Ma trận SWOT (Albert Humphrey - ĐH Stanford)", Meaning = "Đánh giá S(Mạnh), W(Yếu), O(Cơ hội), T(Thách thức) để ra quyết định.", RealWorldApplication = "🏭 Netflix phân tích tự sản xuất phim. 🎓 Học sinh chọn trường Đại học phù hợp." },
                "eisenhower" => new WorkplaceToolInfo { ToolId = toolId, Title = "Ma trận Eisenhower (Dwight D. Eisenhower - Mỹ)", Meaning = "Chia công việc theo độ Khẩn cấp và Quan trọng để xử lý.", RealWorldApplication = "🏭 Elon Musk quản lý thời gian. 🎓 Sắp xếp bài tập và lịch học không bị stress." },
                "five_s" => new WorkplaceToolInfo { ToolId = toolId, Title = "Tiêu chuẩn 5S (Nhật Bản)", Meaning = "Sàng lọc - Sắp xếp - Sạch sẽ - Săn sóc - Sẵn sàng.", RealWorldApplication = "🏭 Nhà máy tránh tai nạn. 🎓 Dọn góc học tập giúp tăng tập trung." },
                "kanban" => new WorkplaceToolInfo { ToolId = toolId, Title = "Bảng Kanban (Taiichi Ohno - Hãng Toyota)", Meaning = "Hệ thống thẻ To Do -> Doing -> Done giúp tránh quá tải.", RealWorldApplication = "🏭 Spotify lập trình phần mềm. 🎓 Tổ nhóm theo dõi tiến độ làm Powerpoint." },
                "kpi_okr" => new WorkplaceToolInfo { ToolId = toolId, Title = "OKR - Quản trị Mục tiêu (Andy Grove - Intel)", Meaning = "Objective (Mục tiêu) và Key Results (Chỉ số đo lường).", RealWorldApplication = "🏭 Google dùng phát triển Chrome. 🎓 Đặt OKR đạt 7.0 IELTS." },
                _ => new WorkplaceToolInfo()
            };
        }

        public static List<WorkplaceTemplate> GetTemplates(string toolId)
        {
            var list = new List<WorkplaceTemplate>();
            switch (toolId)
            {
                case "five_why":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Điểm Tiếng Anh thấp", Data = new FiveWhyData { Problem = "Điểm kiểm tra Tiếng Anh chỉ đạt 5", Why1 = "Làm sai nhiều câu ngữ pháp", Why2 = "Không nhớ cấu trúc câu điều kiện", Why3 = "Ít làm bài tập thực hành", Why4 = "Dành nhiều thời gian chơi game", Why5 = "Chưa nhận thức được tầm quan trọng của Tiếng Anh", How = "Cài app học ngữ pháp, mỗi ngày làm 15p trước khi chơi game" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Hay buồn ngủ trên lớp", Data = new FiveWhyData { Problem = "Hay gục xuống bàn ngủ trong giờ học", Why1 = "Tối qua thức khuya", Why2 = "Lướt TikTok quá 12h đêm", Why3 = "Không kiểm soát được thời gian dùng điện thoại", Why4 = "Mang điện thoại lên giường ngủ", Why5 = "Sợ bỏ lỡ tin nhắn của bạn bè (FOMO)", How = "Để điện thoại ở bàn học, không mang lên giường" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Trễ deadline bài tập nhóm", Data = new FiveWhyData { Problem = "Nộp báo cáo nhóm muộn 1 ngày", Why1 = "Bạn A nộp phần của bạn ấy muộn", Why2 = "Bạn A không biết phải làm phần nào", Why3 = "Lúc họp nhóm không phân công rõ ràng", Why4 = "Trưởng nhóm quên gửi bảng phân công", Why5 = "Chưa có thói quen ghi chép sau cuộc họp", How = "Sử dụng bảng Kanban để chia việc rõ ràng ngay sau họp" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tiêu sạch tiền tiêu vặt", Data = new FiveWhyData { Problem = "Chưa hết tháng đã hết tiền tiêu vặt", Why1 = "Mua trà sữa quá nhiều", Why2 = "Ngày nào cũng đi theo bạn bè vào quán", Why3 = "Không biết từ chối lời rủ rê", Why4 = "Sợ mất lòng bạn bè", Why5 = "Chưa tự tin vào quan điểm cá nhân", How = "Học cách nói 'Không' và chỉ đi 1 lần/tuần" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Bị mẹ la vì phòng bừa bộn", Data = new FiveWhyData { Problem = "Phòng ngủ rất bừa bãi", Why1 = "Quần áo vứt lung tung", Why2 = "Thay ra không treo lên", Why3 = "Móc áo để ở vị trí khó lấy", Why4 = "Tủ quần áo quá chật", Why5 = "Chứa nhiều đồ không còn mặc vừa", How = "Áp dụng 5S: Sàng lọc bỏ đồ cũ đi" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Bị cận thị nặng hơn", Data = new FiveWhyData { Problem = "Độ cận tăng thêm 1 độ", Why1 = "Mắt làm việc quá sức", Why2 = "Nhìn màn hình điện thoại liên tục 3 tiếng", Why3 = "Chơi game trong phòng tối", Why4 = "Lười đi bật đèn", Why5 = "Công tắc đèn ở xa giường", How = "Quy định chỉ dùng điện thoại ở phòng khách" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Sự kiện CLB vắng khách", Data = new FiveWhyData { Problem = "Sự kiện âm nhạc chỉ có 20 người tham gia", Why1 = "Ít người biết đến sự kiện", Why2 = "Bài đăng truyền thông trên Facebook ít tương tác", Why3 = "Đăng vào giờ học (9h sáng)", Why4 = "Ban truyền thông không tìm hiểu giờ vàng", Why5 = "Thiếu quy trình làm truyền thông bài bản", How = "Lập checklist giờ đăng bài (PDCA)" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Thành viên rời CLB", Data = new FiveWhyData { Problem = "5 bạn xin rút khỏi CLB", Why1 = "Các bạn cảm thấy chán", Why2 = "CLB ít hoạt động thú vị", Why3 = "Trưởng ban ít tổ chức bonding", Why4 = "Trưởng ban quá bận rộn việc học", Why5 = "Không biết ủy quyền cho phó ban", How = "Học cách phân việc theo Ma trận Eisenhower" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new FiveWhyData { Problem = "Học sinh lười ôn công thức Toán", Why1 = "Công thức quá dài và khô khan", Why2 = "Chỉ học thuộc lòng qua sách giáo khoa", Why3 = "Chưa có công cụ học tập sinh động", Why4 = "Thầy cô chưa kịp chuẩn bị tài liệu mới", Why5 = "Chưa có nhóm học sinh hỗ trợ làm tài liệu", How = "Nhóm QCC tự làm bộ Flashcard Toán học phát cho lớp" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new FiveWhyData { Problem = "Các bạn lười mang bình nước cá nhân", Why1 = "Cặp sách đã quá nặng", Why2 = "Phải mang nhiều sách giáo khoa và vở bài tập", Why3 = "Mang theo cả những sách không có trong TKB hôm đó", Why4 = "Lười soạn cặp vào buổi tối", Why5 = "Không có checklist chuẩn bị đồ dùng", How = "Dán checklist TKB và khuyến khích để sách ở tủ đồ lớp" } });
                    break;
                case "fishbone":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Bài kiểm tra Lý điểm thấp", Data = new FishboneData { MainProblem = "Điểm Lý < 5", Groups = new Dictionary<string, string[]> { {"Học sinh", new[]{"Không thuộc công thức", "Tính toán sai"}}, {"Giáo viên", new[]{"Giảng quá nhanh"}}, {"Tài liệu", new[]{"Sách tham khảo khó hiểu"}}, {"Môi trường", new[]{"Lớp ồn ào"}}, {"Phương pháp", new[]{"Học vẹt, không hiểu bản chất"}}, {"Khác", new[]{"Đề thi quá dài"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Làm văn hay bị lạc đề", Data = new FishboneData { MainProblem = "Viết văn lạc đề", Groups = new Dictionary<string, string[]> { {"Học sinh", new[]{"Không đọc kỹ đề", "Bị tâm lý trong phòng thi"}}, {"Phương pháp", new[]{"Không lập dàn ý trước khi viết"}}, {"Tài liệu", new[]{"Đọc quá nhiều văn mẫu"}}, {"Môi trường", new[]{"Thiếu không gian yên tĩnh để tư duy"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Học từ vựng tiếng Anh hay quên", Data = new FishboneData { MainProblem = "Quên từ vựng", Groups = new Dictionary<string, string[]> { {"Phương pháp", new[]{"Học nhồi nhét 1 lúc quá nhiều", "Không ôn tập ngắt quãng"}}, {"Học sinh", new[]{"Không tập trung", "Lười chép tay"}}, {"Tài liệu", new[]{"Không có ví dụ minh họa"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Thường xuyên đi học muộn", Data = new FishboneData { MainProblem = "Đi học muộn", Groups = new Dictionary<string, string[]> { {"Con người", new[]{"Ngủ nướng", "Lề mề lúc thay đồ"}}, {"Công cụ", new[]{"Đồng hồ báo thức hỏng", "Điện thoại hết pin"}}, {"Môi trường", new[]{"Kẹt xe", "Mưa ngập đường"}}, {"Phương pháp", new[]{"Không chuẩn bị cặp từ tối hôm trước"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tăng cân mất kiểm soát", Data = new FishboneData { MainProblem = "Béo phì", Groups = new Dictionary<string, string[]> { {"Thói quen", new[]{"Ăn đêm", "Uống trà sữa mỗi ngày"}}, {"Vận động", new[]{"Lười tập thể dục", "Ngồi máy tính >6 tiếng"}}, {"Tâm lý", new[]{"Ăn để xả stress"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Hay quên đồ đạc", Data = new FishboneData { MainProblem = "Mất não", Groups = new Dictionary<string, string[]> { {"Sắp xếp", new[]{"Để đồ không cố định", "Phòng bừa bộn"}}, {"Tâm lý", new[]{"Làm nhiều việc cùng lúc", "Thiếu tập trung"}}, {"Thói quen", new[]{"Không dùng sổ tay ghi chú"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Sự kiện thiếu ngân sách", Data = new FishboneData { MainProblem = "Thiếu tiền quỹ", Groups = new Dictionary<string, string[]> { {"Tài chính", new[]{"Không xin được tài trợ", "Chi tiêu lãng phí"}}, {"Nhân sự", new[]{"Ban đối ngoại thiếu kinh nghiệm"}}, {"Quy trình", new[]{"Không lập bảng dự trù kinh phí"}}, {"Môi trường", new[]{"Kinh tế khó khăn"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Mâu thuẫn nội bộ Ban", Data = new FishboneData { MainProblem = "Cãi nhau nội bộ", Groups = new Dictionary<string, string[]> { {"Con người", new[]{"Cái tôi cao", "Không chịu lắng nghe"}}, {"Quy trình", new[]{"Phân công công việc không đều", "Đánh giá không công bằng"}}, {"Giao tiếp", new[]{"Chỉ nhắn tin, ít họp trực tiếp"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new FishboneData { MainProblem = "Hay nhớ nhầm công thức", Groups = new Dictionary<string, string[]> { {"Học sinh", new[]{"Học vẹt", "Tâm lý chán nản"}}, {"Giáo viên", new[]{"Giảng lướt phần chứng minh"}}, {"Tài liệu", new[]{"Sách in quá nhỏ", "Không có sơ đồ tư duy"}}, {"Môi trường", new[]{"Học lúc mệt mỏi, buồn ngủ"}}, {"Phương pháp", new[]{"Không có trò chơi/Flashcard để ôn tập"}} } } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new FishboneData { MainProblem = "Lạm dụng đồ nhựa 1 lần", Groups = new Dictionary<string, string[]> { {"Con người", new[]{"Lười rửa bình nước", "Thích tiện lợi"}}, {"Cơ sở vật chất", new[]{"Căn tin không có ly giấy", "Hành lang không có máy lọc nước"}}, {"Chính sách", new[]{"Nhà trường chưa cấm mang ly nhựa vào lớp"}}, {"Tâm lý", new[]{"Thấy bạn bè dùng nên dùng theo (Hiệu ứng đám đông)"}} } } });
                    break;
                case "pareto":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Lỗi sai trong bài thi Toán", Data = new ParetoData { Items = new[] { ("Sai dấu", 40.0), ("Tính nhầm", 35.0), ("Quên công thức", 15.0), ("Lạc đề", 5.0), ("Chữ xấu", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Nguyên nhân mất tập trung", Data = new ParetoData { Items = new[] { ("Lướt MXH", 45.0), ("Nhắn tin", 30.0), ("Ồn ào", 15.0), ("Buồn ngủ", 5.0), ("Đói", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Thời gian dùng để ôn thi", Data = new ParetoData { Items = new[] { ("Làm đề", 50.0), ("Đọc SGK", 25.0), ("Tóm tắt", 15.0), ("Học nhóm", 5.0), ("Khác", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Chi tiêu trong tháng", Data = new ParetoData { Items = new[] { ("Trà sữa/Ăn vặt", 45.0), ("Đi chơi", 30.0), ("Mua sắm quần áo", 15.0), ("Tài liệu học", 5.0), ("Tiết kiệm", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Lý do trễ hẹn", Data = new ParetoData { Items = new[] { ("Ngủ quên", 50.0), ("Kẹt xe", 25.0), ("Quên đồ", 15.0), ("Xe hỏng", 5.0), ("Khác", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Lãng phí thời gian", Data = new ParetoData { Items = new[] { ("Chơi Game", 40.0), ("Xem YouTube", 35.0), ("Nằm lười", 15.0), ("Nói chuyện phiếm", 5.0), ("Di chuyển", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Khiếu nại từ thành viên", Data = new ParetoData { Items = new[] { ("Họp quá dài", 50.0), ("Trưởng ban gắt gỏng", 25.0), ("Ít bonding", 15.0), ("Deadline gấp", 5.0), ("Không rõ mục tiêu", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Chi phí Tổ chức Sự kiện", Data = new ParetoData { Items = new[] { ("Thuê âm thanh", 45.0), ("Sân khấu", 30.0), ("Trang trí", 15.0), ("Nước uống", 5.0), ("In ấn", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new ParetoData { Items = new[] { ("Tính toán sai bước cuối", 50.0), ("Nhớ nhầm công thức", 30.0), ("Không hiểu bản chất", 15.0), ("Hết thời gian", 5.0) } } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new ParetoData { Items = new[] { ("Ly trà sữa/Cà phê", 60.0), ("Hộp xốp ăn sáng", 20.0), ("Bao ni lông", 10.0), ("Muỗng nhựa", 5.0), ("Chai nước suối", 5.0) } } });
                    break;
                case "pdca":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Tăng điểm môn Hóa", Data = new PdcaData { Plan = "Đạt 8 điểm Hóa giữa kỳ", Do = "Mỗi ngày giải 5 bài tập Hóa", Check = "Cuối tuần tự test 30 phút", Act = "Nếu sai lý thuyết -> đọc lại SGK" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Luyện IELTS Reading", Data = new PdcaData { Plan = "Đạt 7.0 Reading trong 1 tháng", Do = "Mỗi ngày làm 1 Passage Cam", Check = "So đáp án, tra từ vựng không biết", Act = "Lập sổ từ vựng và review lại cuối tuần" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Tập viết chữ đẹp", Data = new PdcaData { Plan = "Viết nhanh nhưng không bị rối chữ", Do = "Luyện viết đoạn văn 15 phút mỗi sáng", Check = "Đưa cho bạn cùng bàn xem có đọc được không", Act = "Đổi loại bút bi sang bút mực gel" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Luyện tập thể lực", Data = new PdcaData { Plan = "Chạy bộ 5km không nghỉ", Do = "Mỗi buổi chiều chạy 30 phút", Check = "Đo nhịp tim và quãng đường bằng Smartwatch", Act = "Điều chỉnh nhịp thở và mua giày mới" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Cai nghiện mạng xã hội", Data = new PdcaData { Plan = "Giảm thời gian dùng Facebook < 1h/ngày", Do = "Bật chế độ giới hạn ứng dụng", Check = "Xem thống kê Screen Time cuối tuần", Act = "Nếu vượt mức, sẽ xóa app vào tuần sau" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tập dậy sớm", Data = new PdcaData { Plan = "Dậy lúc 5:30 sáng", Do = "Đặt báo thức ở góc phòng", Check = "Ghi chép số ngày dậy đúng giờ", Act = "Ngủ sớm hơn 30 phút vào tối hôm trước" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Tuyển thành viên mới", Data = new PdcaData { Plan = "Tuyển được 20 thành viên chất lượng", Do = "Đăng bài Facebook và mở form đăng ký", Check = "Theo dõi số lượng CV nộp về mỗi ngày", Act = "Nếu ít CV, tổ chức booth trực tiếp ở sân trường" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Cải thiện quy trình Họp", Data = new PdcaData { Plan = "Rút ngắn thời gian họp còn 45p", Do = "Gửi agenda trước 1 ngày, dùng đồng hồ bấm giờ", Check = "Đánh giá xem có bị lố giờ không", Act = "Cắt bỏ phần báo cáo dài dòng, chuyển sang file Docs" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new PdcaData { Plan = "Thử nghiệm chơi Flashcard 15 phút đầu giờ", Do = "Tổ trưởng phát Flashcard và kiểm tra chéo", Check = "Làm bài test 15 phút cuối tuần", Act = "Thay đổi luật chơi nếu các bạn thấy nhàm chán" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new PdcaData { Plan = "100% các bạn dùng bình nước cá nhân", Do = "Lớp mua 1 bình lọc nước 20L đặt ở góc", Check = "Đội sao đỏ đếm số ly nhựa vứt vào thùng rác mỗi ngày", Act = "Tuyên dương các bạn không dùng ly nhựa trong sinh hoạt lớp" } });
                    break;
                case "swot":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Chọn khối thi Đại học (A00 vs D01)", Data = new SwotData { S = new[]{"Tư duy logic tốt", "Thích tính toán"}, W = new[]{"Lười học thuộc lòng", "Từ vựng tiếng Anh yếu"}, O = new[]{"Ngành CNTT đang hot", "Nhiều trường xét tuyển khối A"}, T = new[]{"Điểm chuẩn khối A rất cao", "Tỷ lệ chọi căng thẳng"} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Học nhóm hay Học một mình", Data = new SwotData { S = new[]{"Tự chủ thời gian (Một mình)", "Có người giảng bài khó (Nhóm)"}, W = new[]{"Dễ chán (Một mình)", "Hay buôn chuyện (Nhóm)"}, O = new[]{"Phát triển kỹ năng giao tiếp (Nhóm)"}, T = new[]{"Lệ thuộc vào bạn bè", "Mất tập trung"} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Có nên thi IELTS sớm?", Data = new SwotData { S = new[]{"Có nền tảng ngữ pháp tốt"}, W = new[]{"Kỹ năng Speaking còn rụt rè"}, O = new[]{"Được tuyển thẳng ĐH", "Miễn thi tốt nghiệp môn Anh"}, T = new[]{"Lệ phí thi đắt (4.6 triệu)", "Bằng chỉ có hạn 2 năm"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Ứng cử Lớp Trưởng", Data = new SwotData { S = new[]{"Có trách nhiệm", "Hòa đồng với các bạn"}, W = new[]{"Nóng tính", "Hay quên"}, O = new[]{"Được thầy cô tín nhiệm", "Rèn luyện leadership"}, T = new[]{"Mất nhiều thời gian học", "Dễ bị các bạn ghét nếu khắt khe"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Nên đi làm thêm không?", Data = new SwotData { S = new[]{"Có xe đạp điện", "Sức khỏe tốt"}, W = new[]{"Chưa có kinh nghiệm", "Thiếu kỹ năng giao tiếp"}, O = new[]{"Kiếm thêm thu nhập", "Học kỹ năng xã hội"}, T = new[]{"Ảnh hưởng kết quả học tập", "Bị bóc lột sức lao động"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tham gia CLB Tranh Biện", Data = new SwotData { S = new[]{"Thích lập luận", "Đọc nhiều sách"}, W = new[]{"Sợ nói trước đám đông", "Nói hay bị vấp"}, O = new[]{"Được đi thi đấu", "Mở rộng network"}, T = new[]{"Đụng độ lịch học thêm", "Cạnh tranh gắt gao lúc casting"} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Tổ chức Prom Cuối Năm", Data = new SwotData { S = new[]{"Ban tổ chức nhiệt huyết", "Có sẵn đội Văn nghệ mạnh"}, W = new[]{"Chưa có kinh nghiệm xin tài trợ", "Quỹ CLB eo hẹp"}, O = new[]{"Học sinh khối 12 rất muốn tham gia"}, T = new[]{"Trường không cho phép tổ chức muộn", "Rủi ro thời tiết (mưa)"} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Mời Rapper về trường", Data = new SwotData { S = new[]{"Tạo tiếng vang cực lớn", "Bán được nhiều vé"}, W = new[]{"Chi phí cát-xê quá cao", "Khó liên hệ quản lý"}, O = new[]{"Được tài trợ từ các trung tâm Anh ngữ"}, T = new[]{"Nhà trường e ngại phong cách của Rapper", "Không kiểm soát được an ninh"} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new SwotData { S = new[]{"Bộ Flashcard rất đẹp", "Luật chơi vui nhộn"}, W = new[]{"Tốn tiền in ấn", "Cần thời gian làm thủ công"}, O = new[]{"Cô giáo bộ môn ủng hộ", "Các bạn thích sự mới lạ"}, T = new[]{"Các bạn chỉ mải chơi không chịu nhớ bài", "Dễ làm mất thẻ"} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new SwotData { S = new[]{"Lớp đoàn kết", "Quỹ lớp còn nhiều để mua bình 20L"}, W = new[]{"Một số bạn lười rửa bình", "Thích uống trà sữa lén lút"}, O = new[]{"Được khen thưởng danh hiệu Lớp Xanh"}, T = new[]{"Căn tin bán toàn đồ dùng 1 lần", "Khó thay đổi thói quen ngay lập tức"} } });
                    break;
                case "eisenhower":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Tuần lễ thi Giữa Kỳ", Data = new EisenhowerData { UI = new[]{"Ôn thi Toán (Sáng mai thi)", "Nộp tiểu luận Văn (Tối nay hạn)"}, NUI = new[]{"Ôn Lý (Tuần sau thi)", "Làm Outline đề cương Sử"}, UNI = new[]{"Chép phạt bài hôm qua", "Trả lời tin nhắn lớp trưởng"}, NUNI = new[]{"Lướt TikTok", "Chơi LOL rank"} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Bài tập về nhà ngập đầu", Data = new EisenhowerData { UI = new[]{"Làm 10 bài Hóa (Mai nộp)", "Dịch bài tiếng Anh (Chiều mai)"}, NUI = new[]{"Làm project Sinh học (2 tuần nữa)", "Đọc trước bài mới"}, UNI = new[]{"Nộp quỹ lớp", "Đi mua vở nháp"}, NUNI = new[]{"Cày phim Hàn", "Tranh luận trên Facebook"} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Chuẩn bị Hồ sơ Đại học", Data = new EisenhowerData { UI = new[]{"Nộp đơn xét tuyển (Mai chốt)", "Chụp ảnh thẻ"}, NUI = new[]{"Viết bài luận Personal Statement", "Thi IELTS"}, UNI = new[]{"Photocopy học bạ", "Công chứng CCCD"}, NUNI = new[]{"Chơi game", "Cà phê tán gẫu"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Ngày Chủ Nhật rảnh rỗi", Data = new EisenhowerData { UI = new[]{"Dọn dẹp phòng (Mẹ đang giục)", "Gửi mail xin phép cô"}, NUI = new[]{"Tập Gym", "Đọc sách kỹ năng mềm"}, UNI = new[]{"Đăng status Facebook", "Rep story bạn bè"}, NUNI = new[]{"Ngủ nướng tới trưa", "Cày anime"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Quản lý công việc tuần", Data = new EisenhowerData { UI = new[]{"Đi khám răng (Bị đau)", "Đóng tiền nhà trọ"}, NUI = new[]{"Học khóa Lập trình Online", "Đi thăm họ hàng"}, UNI = new[]{"Mua đồ ăn vặt", "Đi lấy đồ shipper"}, NUNI = new[]{"Lướt Shopee săn sale", "Chơi game"} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Cân bằng Cuộc sống", Data = new EisenhowerData { UI = new[]{"Chữa bệnh", "Kiếm tiền sinh hoạt"}, NUI = new[]{"Xây dựng các mối quan hệ", "Học kỹ năng mới"}, UNI = new[]{"Tham gia tiệc tùng vô bổ", "Trả lời tin nhắn rác"}, NUNI = new[]{"So sánh bản thân với người khác", "Suy nghĩ tiêu cực"} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Giai đoạn chạy Sự kiện", Data = new EisenhowerData { UI = new[]{"Ký hợp đồng thuê loa đài", "Chốt MC chương trình"}, NUI = new[]{"Viết kịch bản chi tiết", "Xin tài trợ"}, UNI = new[]{"Mua nước uống cho BTC", "Thiết kế thẻ đeo"}, NUNI = new[]{"Thiết kế lại logo CLB", "Lướt mạng tìm nhạc nền"} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Bàn giao Nhiệm kỳ", Data = new EisenhowerData { UI = new[]{"Làm báo cáo tài chính", "Phỏng vấn Ban chủ nhiệm mới"}, NUI = new[]{"Viết cẩm nang hoạt động", "Lên kế hoạch năm sau"}, UNI = new[]{"Làm file Excel danh sách cũ", "Dọn kho CLB"}, NUNI = new[]{"Tổ chức liên hoan chia tay (chưa cần gấp)", "Chơi ma sói"} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new EisenhowerData { UI = new[]{"In Flashcard (Sáng mai dùng)", "Phát tài liệu cho các nhóm"}, NUI = new[]{"Viết luật chơi chi tiết", "Thiết kế Flashcard chương tiếp theo"}, UNI = new[]{"Cắt viền bo góc cho thẻ", "Sửa lỗi chính tả vài thẻ"}, NUNI = new[]{"Lên mạng tìm font chữ đẹp hơn", "Tranh cãi xem thẻ màu gì đẹp"} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new EisenhowerData { UI = new[]{"Thu tiền quỹ mua bình nước 20L", "Gặp cô chủ nhiệm xin phép"}, NUI = new[]{"Làm bảng theo dõi rác nhựa", "Tuyên truyền cho các lớp khác"}, UNI = new[]{"Dán decal trang trí bình nước", "Mua ly giấy dự phòng"}, NUNI = new[]{"Tranh luận với bạn bè bảo vệ môi trường", "Xem video về rác thải"} } });
                    break;
                case "five_s":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Đánh giá Bàn học ở nhà", Data = new FiveSData { Subject = "Bàn học cá nhân - Tuần 1" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Trực nhật Lớp học", Data = new FiveSData { Subject = "Trực nhật Tổ 2 - Thứ Sáu" } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Kiểm tra Tủ đựng đồ lớp", Data = new FiveSData { Subject = "Locker cá nhân - Cuối tháng" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Dọn dẹp Tủ quần áo", Data = new FiveSData { Subject = "Tủ quần áo Mùa Đông" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Dọn dẹp Máy tính (Desktop)", Data = new FiveSData { Subject = "Màn hình Desktop và thư mục rác" } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tổ chức lại Cặp xách", Data = new FiveSData { Subject = "Balo đi học hàng ngày" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Dọn Kho thiết bị CLB", Data = new FiveSData { Subject = "Kho dụng cụ Ban Sự Kiện" } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Đánh giá Phòng sinh hoạt", Data = new FiveSData { Subject = "Phòng sinh hoạt CLB sau sự kiện" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new FiveSData { Subject = "Kiểm kê bộ Flashcard sau giờ chơi" } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new FiveSData { Subject = "Khu vực đặt bình nước của lớp" } });
                    break;
                case "kanban":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Bài tập cuối tuần", Data = new KanbanData { Todo = new[]{("Đề Toán trang 45", "Xem lại lượng giác"), ("Viết Văn", "Bài Vội Vàng")}, Doing = new[]{("Báo cáo Lý", "Hạn nộp sáng thứ 2")}, Done = new[]{("Học 20 từ tiếng Anh", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Ôn thi Giữa kỳ", Data = new KanbanData { Todo = new[]{("Giải 3 đề Toán", ""), ("Học bảng tuần hoàn Hóa", "")}, Doing = new[]{("Làm Outline Sử", "Tổng hợp sự kiện")}, Done = new[]{("Thi Speaking Tiếng Anh", "Target 6.5")} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Thực hiện Project nhóm", Data = new KanbanData { Todo = new[]{("Tìm tài liệu", "Google Scholar"), ("Làm slide PPT", "")}, Doing = new[]{("Viết báo cáo Word", "Cần 10 trang")}, Done = new[]{("Chia nhóm và chọn đề tài", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Kế hoạch Nghỉ Hè", Data = new KanbanData { Todo = new[]{("Đọc 3 cuốn sách", "Tiểu thuyết"), ("Đi học bơi", "")}, Doing = new[]{("Học đàn Guitar", "Tự học trên YouTube")}, Done = new[]{("Về quê thăm ông bà", "Đã xong tuần 1")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Phát triển bản thân", Data = new KanbanData { Todo = new[]{("Học khóa Excel", "Coursera"), ("Làm CV", "Trên Canva")}, Doing = new[]{("Tập Gym 3 buổi/tuần", "")}, Done = new[]{("Cắt tóc", ""), ("Mua quần áo mới", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Chuẩn bị đi du lịch", Data = new KanbanData { Todo = new[]{("Book khách sạn", ""), ("Lên lịch trình", "")}, Doing = new[]{("Xin phép bố mẹ", ""), ("Mua vé máy bay", "")}, Done = new[]{("Chọn điểm đến", "Đà Lạt")} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Chạy Event Chào Tân", Data = new KanbanData { Todo = new[]{("Thuê âm thanh", ""), ("Mua bánh kẹo", "")}, Doing = new[]{("Duyệt văn nghệ", "Tại phòng đa năng")}, Done = new[]{("Lên ý tưởng", ""), ("Tuyển Tình nguyện viên", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Quản lý Fanpage CLB", Data = new KanbanData { Todo = new[]{("Viết content Minigame", ""), ("Thiết kế poster", "")}, Doing = new[]{("Chạy Ads Facebook", "Ngân sách 500k")}, Done = new[]{("Lên kế hoạch Content tháng", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new KanbanData { Todo = new[]{("Thiết kế Flashcard Chương 2", "Dùng Canva"), ("In và ép plastic", "")}, Doing = new[]{("Viết luật chơi trò mới", "Kahoot")}, Done = new[]{("Hoàn thành Flashcard Chương 1", "")} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new KanbanData { Todo = new[]{("Làm bảng theo dõi rác", ""), ("Tuyên truyền lớp khác", "")}, Doing = new[]{("Mua bình nước 20L", "Đang xin cô tiền quỹ")}, Done = new[]{("Khảo sát ý kiến các bạn", "100% đồng ý")} } });
                    break;
                case "kpi_okr":
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Chinh phục điểm 10 Toán", Data = new KpiOkrData { Obj = "Đạt điểm 10 tuyệt đối môn Toán", Data = new[]{("Giải đề thi thử mỗi tuần", "10", "8"), ("Học thuộc các công thức khó", "15", "15"), ("Lên bảng giải bài", "5", "3")} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Luyện IELTS 7.0", Data = new KpiOkrData { Obj = "Đạt 7.0 Overall kỳ thi IELTS", Data = new[]{("Học từ mới", "500", "320"), ("Luyện đề Reading", "20", "15"), ("Thu âm Speaking", "30", "12")} } });
                    list.Add(new WorkplaceTemplate { Category = "📚 Học tập", Name = "Đạt Học sinh Giỏi", Data = new KpiOkrData { Obj = "Điểm phẩy trung bình > 8.0", Data = new[]{("Điểm Hóa trên 8", "10", "8"), ("Điểm Văn trên 7.5", "10", "8"), ("Không đi học muộn", "30", "28")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Giảm 2kg trong 1 tháng", Data = new KpiOkrData { Obj = "Giảm 2kg để mặc vừa áo thun", Data = new[]{("Chạy bộ 30p mỗi ngày", "30", "18"), ("Số ngày KHÔNG uống trà sữa", "30", "25"), ("Uống đủ 2 lít nước", "30", "28")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Đọc 10 cuốn sách", Data = new KpiOkrData { Obj = "Đọc xong 10 cuốn sách trong hè", Data = new[]{("Đọc số trang mỗi ngày", "50", "40"), ("Viết review sách", "10", "6"), ("Không dùng điện thoại trước khi ngủ", "30", "20")} } });
                    list.Add(new WorkplaceTemplate { Category = "🌱 Cá nhân", Name = "Tiết kiệm 2 triệu mua giày", Data = new KpiOkrData { Obj = "Để dành 2 triệu trong 3 tháng", Data = new[]{("Bỏ ống heo mỗi ngày (K)", "20", "15"), ("Bán đồ cũ trên mạng", "5", "2"), ("Số ngày tự nấu ăn sáng", "30", "25")} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Tuyển 50 thành viên mới", Data = new KpiOkrData { Obj = "Tuyển thành công 50 TNV nhiệt huyết", Data = new[]{("Số đơn đăng ký (CV)", "150", "120"), ("Tỷ lệ tham gia phỏng vấn", "100", "85"), ("Số bài post Facebook", "10", "8")} } });
                    list.Add(new WorkplaceTemplate { Category = "🚀 CLB", Name = "Tổ chức Sự kiện thành công", Data = new KpiOkrData { Obj = "Chạy Event sinh nhật CLB hoành tráng", Data = new[]{("Số lượng vé bán ra", "500", "450"), ("Số tiền tài trợ thu được", "20", "15"), ("Mức độ hài lòng của khán giả (%)", "95", "90")} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "1. Dự án Giải Cứu Điểm Toán", Data = new KpiOkrData { Obj = "100% thành viên tổ đạt trên 7 điểm", Data = new[]{("Số buổi tự kiểm tra chéo", "10", "8"), ("Tỷ lệ thuộc Flashcard (%)", "100", "80"), ("Điểm kiểm tra 15p trung bình", "8.0", "7.5")} } });
                    list.Add(new WorkplaceTemplate { Category = "🔗 QCC", Name = "2. Lớp học Không Rác Nhựa", Data = new KpiOkrData { Obj = "Giảm 100% rác thải nhựa trong lớp", Data = new[]{("Số ly nhựa vứt vào thùng rác", "0", "5"), ("Số bạn mang bình nước cá nhân", "40", "35"), ("Số buổi căn tin dùng ly giấy", "20", "10")} } });
                    break;
            }
            return list;
        }
    }
}"""

with open(r'd:\JOB\QA SmartSchool\QA SmartClass_Document\QASmartClass_Dev\QASmartClass\LearningTools\Helpers\WorkplaceTemplateManager.cs', 'w', encoding='utf-8') as f:
    f.write(manager_code)

print("Generated WorkplaceTemplateManager.cs with 90 templates!")
